// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class BLOCK
    {
        public string BLK_ID { get; set; }
        public string BLK_DIVID { get; set; }
        public string BLK_ESTID { get; set; }
        public string BLK_CODE { get; set; }
        public decimal? BLK_LUAS { get; set; }
        public string ACTIVE { get; set; }
    }
}