// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class BLOCKTEMP
    {
        public string ESTATE { get; set; }
        public string DIVID { get; set; }
        public string BLOCKID { get; set; }
        public decimal TOTAREA { get; set; }
        public string PLANTINGDT { get; set; }
        public string PHASE { get; set; }
        public string COSTCTR { get; set; }
        public string WBS { get; set; }
        public decimal BJR { get; set; }
        public string TOPOGRAPI { get; set; }
        public short SPH { get; set; }
        public string JENISBIBIT { get; set; }
        public string KELASTANAH { get; set; }
    }
}