// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class DHS_DOKET
    {
        public DateTime DOK_TGLPANEN { get; set; }
        public DateTime DOK_JAMCATAT { get; set; }
        public string DOK_ID { get; set; }
        public string DOK_TPHCODE { get; set; }
        public string DOK_BLOCKID { get; set; }
        public string DOK_DIVID { get; set; }
        public string DOK_KERANIID { get; set; }
        public string DOK_MANDORID { get; set; }
        public string DOK_PEMANEN { get; set; }
        public string DOK_PEMBRONDOL { get; set; }
        public string DOK_FOTO { get; set; }
        public string DOK_LT { get; set; }
        public string DOK_LG { get; set; }
        public string DOK_CATATAN { get; set; }
        public string DOK_FOTO2 { get; set; }
        public string DOK_XDOKETID { get; set; }
        public string DOK_BLOCKCODE { get; set; }
        public string DOK_STATUS { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime? CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime? UPDATED { get; set; }
        public string DOK_CHECKERID { get; set; }
        public string DOK_ISRSPO { get; set; }

        public virtual MBLOCK DOK_BLOCKCODENavigation { get; set; }
    }
}