// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class DHS_SPB
    {
        public DateTime SPB_TANGGAL { get; set; }
        public string SPB_JAMCATAT { get; set; }
        public string SPB_ID { get; set; }
        public string SPB_KERANIID { get; set; }
        public string SPB_TKBM1 { get; set; }
        public string SPB_TKBM2 { get; set; }
        public string SPB_TKBM3 { get; set; }
        public string SPB_TRUCKID { get; set; }
        public string SPB_SOPIR { get; set; }
        public string SPB_SOPIRID { get; set; }
        public string SPB_SIM { get; set; }
        public string SPB_FOTO { get; set; }
        public string SPB_LT { get; set; }
        public string SPB_LG { get; set; }
        public string SPB_CATATAN { get; set; }
        public decimal? SPB_TOTALTBS { get; set; }
        public decimal? SPB_TOTALBRDL { get; set; }
        public decimal? SPB_BJR { get; set; }
        public decimal? SPB_TONASE { get; set; }
        public string SPB_PKS { get; set; }
        public string SPB_TIPETRUK { get; set; }
        public string SPB_ESTATE { get; set; }
        public string SPB_FOTO2 { get; set; }
        public decimal? SPB_JJGKETEK { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime? CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime? UPDATED { get; set; }
        public string SPB_ACTIVE { get; set; }
    }
}