// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class DimUnit
    {
        public string UnitId { get; set; }
        public string UnitInitial { get; set; }
        public string UnitName { get; set; }
        public string CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string RegionId { get; set; }
        public string RegionName { get; set; }
        public string AreaId { get; set; }
        public string AreaName { get; set; }
        public string Type { get; set; }
        public string GB { get; set; }
        public string GroupId { get; set; }
        public string GroupName { get; set; }
        public string Group { get; set; }
        public string IntiId { get; set; }
        public bool? Active { get; set; }
    }
}