// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class DOKETKG
    {
        public string DOKID { get; set; }
        public string SOURCE { get; set; }
        public decimal JJG { get; set; }
        public decimal BJR { get; set; }
        public decimal JJGKG { get; set; }
        public decimal BRDKG { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }
    }
}