// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class EM_TINSPECTION
    {
        public string id { get; set; }
        public DateTime? date { get; set; }
        public string title { get; set; }
        public string blockId { get; set; }
        public string actId { get; set; }
        public string note { get; set; }
        public string picturePathName { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public decimal? distance { get; set; }
        public decimal? distanceSet { get; set; }
        public string status { get; set; }
        public string upload { get; set; }
        public string createUser { get; set; }
        public DateTime? createDateTime { get; set; }
    }
}