// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model

{
    public partial class JOBSEMPLASTDATE
    {
        public DateTime TODAY { get; set; }
        public DateTime YESTERDAY { get; set; }
        public string UNITID { get; set; }
        public string EMPID { get; set; }
        public DateTime DATE { get; set; }
        public int? TYPESP { get; set; }
        public int? DAY { get; set; }
        public DateTime? STARTDATE { get; set; }
        public DateTime? ENDDATE { get; set; }
        public string SESSIONID { get; set; }
        public int ID { get; set; }
    }
}