// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class JOBSSTATUS
    {
        public string UNITID { get; set; }
        public string TYPE { get; set; }
        public DateTime DATE { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }
    }
}