// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class JOBSCHECKSUM
    {
        public string UNITID { get; set; }
        public string NAME { get; set; }
        public string NOTE { get; set; }
        public DateTime DATE { get; set; }
        public decimal VALUE1 { get; set; }
        public decimal VALUE2 { get; set; }
        public decimal VALUE3 { get; set; }
        public decimal VALUE4 { get; set; }
        public decimal VALUE5 { get; set; }
        public decimal VALUE6 { get; set; }
        public decimal VALUE7 { get; set; }
        public decimal VALUE8 { get; set; }
    }
}