// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MACCOUNT
    {
        public MACCOUNT()
        {
            InversePARENTCODENavigation = new HashSet<MACCOUNT>();
            MACTIVITYACCOUNTCEHKDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTCEMATDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTGAHKDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTGAMATDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTHKCREDNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTLCHKDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTLCMATDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTNHKDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTNMATDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTRAHKDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTRAMATDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTTBMHKDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTTBMMATDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTTMHKDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MACTIVITYACCOUNTTMMATDEBTNavigation = new HashSet<MACTIVITYACCOUNT>();
            MCARD = new HashSet<MCARD>();
            MMATERIAL = new HashSet<MMATERIAL>();
            MPAYROLLACCOUNTACCOUNT1Navigation = new HashSet<MPAYROLLACCOUNT>();
            MPAYROLLACCOUNTACCOUNT2Navigation = new HashSet<MPAYROLLACCOUNT>();
            MPAYROLLACCOUNTACCOUNT3Navigation = new HashSet<MPAYROLLACCOUNT>();
            MPAYROLLACCOUNTACCOUNT4Navigation = new HashSet<MPAYROLLACCOUNT>();
            TACCOUNTHISTORY = new HashSet<TACCOUNTHISTORY>();
            TGIITEM = new HashSet<TGIITEM>();
            TJOURNALITEM = new HashSet<TJOURNALITEM>();
        }

        public string CODE { get; set; }
        public string NAME { get; set; }
        public short TYPEID { get; set; }
        public bool PARENT { get; set; }
        public string PARENTCODE { get; set; }
        public short LEVEL { get; set; }
        public string NOTE { get; set; }
        public bool ACTIVE { get; set; }
        public bool RACOST { get; set; }
        public bool CECOST { get; set; }
        public bool GACOST { get; set; }
        public bool TMCOST { get; set; }
        public bool TBMCOST { get; set; }
        public bool HVCOST { get; set; }
        public bool CO { get; set; }
        public bool NUCOST { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACCOUNT PARENTCODENavigation { get; set; }
        public virtual MACCOUNTTYPE TYPE { get; set; }
        public virtual ICollection<MACCOUNT> InversePARENTCODENavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTCEHKDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTCEMATDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTGAHKDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTGAMATDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTHKCREDNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTLCHKDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTLCMATDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTNHKDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTNMATDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTRAHKDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTRAMATDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTTBMHKDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTTBMMATDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTTMHKDEBTNavigation { get; set; }
        public virtual ICollection<MACTIVITYACCOUNT> MACTIVITYACCOUNTTMMATDEBTNavigation { get; set; }
        public virtual ICollection<MCARD> MCARD { get; set; }
        public virtual ICollection<MMATERIAL> MMATERIAL { get; set; }
        public virtual ICollection<MPAYROLLACCOUNT> MPAYROLLACCOUNTACCOUNT1Navigation { get; set; }
        public virtual ICollection<MPAYROLLACCOUNT> MPAYROLLACCOUNTACCOUNT2Navigation { get; set; }
        public virtual ICollection<MPAYROLLACCOUNT> MPAYROLLACCOUNTACCOUNT3Navigation { get; set; }
        public virtual ICollection<MPAYROLLACCOUNT> MPAYROLLACCOUNTACCOUNT4Navigation { get; set; }
        public virtual ICollection<TACCOUNTHISTORY> TACCOUNTHISTORY { get; set; }
        public virtual ICollection<TGIITEM> TGIITEM { get; set; }
        public virtual ICollection<TJOURNALITEM> TJOURNALITEM { get; set; }
    }
}