// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MACCOUNTTYPE
    {
        public MACCOUNTTYPE()
        {
            MACCOUNT = new HashSet<MACCOUNT>();
        }

        public short ID { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
        public short SORT { get; set; }

        public virtual ICollection<MACCOUNT> MACCOUNT { get; set; }
    }
}