// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.EFCore.Model
{
    public partial class MACTIVITYACCOUNT
    {
        public string ACTIVITYID { get; set; }
        public string CE { get; set; }
        public string GAMATDEBT { get; set; }
        public string GAHKDEBT { get; set; }
        public string NMATDEBT { get; set; }
        public string NHKDEBT { get; set; }
        public string LCMATDEBT { get; set; }
        public string LCHKDEBT { get; set; }
        public string TBMMATDEBT { get; set; }
        public string TBMHKDEBT { get; set; }
        public string TMMATDEBT { get; set; }
        public string TMHKDEBT { get; set; }
        public string HKCRED { get; set; }
        public string HKCREDASST { get; set; }
        public string CEHKDEBT { get; set; }
        public string CEMATDEBT { get; set; }
        public string RAHKDEBT { get; set; }
        public string RAMATDEBT { get; set; }

        public virtual MACTIVITY ACTIVITY { get; set; }
        public virtual MACCOUNT CEHKDEBTNavigation { get; set; }
        public virtual MACCOUNT CEMATDEBTNavigation { get; set; }
        public virtual MACCOUNT GAHKDEBTNavigation { get; set; }
        public virtual MACCOUNT GAMATDEBTNavigation { get; set; }
        public virtual MACCOUNT HKCREDNavigation { get; set; }
        public virtual MACCOUNT LCHKDEBTNavigation { get; set; }
        public virtual MACCOUNT LCMATDEBTNavigation { get; set; }
        public virtual MACCOUNT NHKDEBTNavigation { get; set; }
        public virtual MACCOUNT NMATDEBTNavigation { get; set; }
        public virtual MACCOUNT RAHKDEBTNavigation { get; set; }
        public virtual MACCOUNT RAMATDEBTNavigation { get; set; }
        public virtual MACCOUNT TBMHKDEBTNavigation { get; set; }
        public virtual MACCOUNT TBMMATDEBTNavigation { get; set; }
        public virtual MACCOUNT TMHKDEBTNavigation { get; set; }
        public virtual MACCOUNT TMMATDEBTNavigation { get; set; }

        //custom
        [NotMapped]
        public string COSTELEMENT
        {
            get { return CE; }
            set { CE = value; }
        }
    }
}