// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MACTIVITY
    {
        public MACTIVITY()
        {
            MACTIVITYRATE = new HashSet<MACTIVITYRATE>();
            MPREMIMUAT = new HashSet<MPREMIMUAT>();
            MPREMIOPERATOR = new HashSet<MPREMIOPERATOR>();
            MPREMIPANEN = new HashSet<MPREMIPANEN>();
            TACTIVITYMATERIALMAP = new HashSet<TACTIVITYMATERIALMAP>();
            TCONTRACTITEM = new HashSet<TCONTRACTITEM>();
            TEQUIPTIMESHEETACTIVITY = new HashSet<TEQUIPTIMESHEETACTIVITY>();
            THARVESTPLANEMPLOYEECALC = new HashSet<THARVESTPLANEMPLOYEECALC>();
            THARVESTRESULT = new HashSet<THARVESTRESULT>();
            TOVERTIME = new HashSet<TOVERTIME>();
            TPREMIMANDOR = new HashSet<TPREMIMANDOR>();
            TPREMINONPANEN = new HashSet<TPREMINONPANEN>();
            TRKHACTUAL = new HashSet<TRKHACTUAL>();
            TRKHDETAIL = new HashSet<TRKHDETAIL>();
            TRKHMATERIAL = new HashSet<TRKHMATERIAL>();
            TSALARYITEM = new HashSet<TSALARYITEM>();
            TUPKEEP = new HashSet<TUPKEEP>();
            TUPKEEPMATERIAL = new HashSet<TUPKEEPMATERIAL>();
        }

        public string ACTIVITYID { get; set; }
        public string ACTIVITYNAME { get; set; }
        public string TYPEACTIVITY { get; set; }
        public string UOM1 { get; set; }
        public string UOM2 { get; set; }
        public bool REQMAT { get; set; }
        public bool ACTIVE { get; set; }
        public bool RA { get; set; }
        public bool CE { get; set; }
        public bool GA { get; set; }
        public bool NURSERY { get; set; }
        public bool LC { get; set; }
        public bool TBM { get; set; }
        public bool TM { get; set; }
        public bool HV { get; set; }
        public short HVTYPE { get; set; }
        public string RFID { get; set; }
        public short AUTO { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACTIVITYACCOUNT MACTIVITYACCOUNT { get; set; }
        public virtual MACTIVITYDETAIL MACTIVITYDETAIL { get; set; }
        public virtual MACTIVITYMAP MACTIVITYMAP { get; set; }
        public virtual ICollection<MACTIVITYRATE> MACTIVITYRATE { get; set; }
        public virtual ICollection<MPREMIMUAT> MPREMIMUAT { get; set; }
        public virtual ICollection<MPREMIOPERATOR> MPREMIOPERATOR { get; set; }
        public virtual ICollection<MPREMIPANEN> MPREMIPANEN { get; set; }
        public virtual ICollection<TACTIVITYMATERIALMAP> TACTIVITYMATERIALMAP { get; set; }
        public virtual ICollection<TCONTRACTITEM> TCONTRACTITEM { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETACTIVITY> TEQUIPTIMESHEETACTIVITY { get; set; }
        public virtual ICollection<THARVESTPLANEMPLOYEECALC> THARVESTPLANEMPLOYEECALC { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULT { get; set; }
        public virtual ICollection<TOVERTIME> TOVERTIME { get; set; }
        public virtual ICollection<TPREMIMANDOR> TPREMIMANDOR { get; set; }
        public virtual ICollection<TPREMINONPANEN> TPREMINONPANEN { get; set; }
        public virtual ICollection<TRKHACTUAL> TRKHACTUAL { get; set; }
        public virtual ICollection<TRKHDETAIL> TRKHDETAIL { get; set; }
        public virtual ICollection<TRKHMATERIAL> TRKHMATERIAL { get; set; }
        public virtual ICollection<TSALARYITEM> TSALARYITEM { get; set; }
        public virtual ICollection<TUPKEEP> TUPKEEP { get; set; }
        public virtual ICollection<TUPKEEPMATERIAL> TUPKEEPMATERIAL { get; set; }
    }
}