// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MACTIVITYMAP
    {
        public string ACTIVITYID { get; set; }
        public string ACTIVITYNAME { get; set; }
        public string ALK { get; set; }

        public virtual MACTIVITY ACTIVITY { get; set; }
    }
}