// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MACTIVITYDETAIL
    {
        public string ACTIVITYID { get; set; }
        public bool DOCBKM { get; set; }
        public bool DOCBKMBORONG { get; set; }
        public bool DOCBKU { get; set; }
        public bool DOCBKP { get; set; }

        public virtual MACTIVITY ACTIVITY { get; set; }
    }
}