// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MACTIVITYRATE
    {
        public string ID { get; set; }
        public string UNITID { get; set; }
        public string ACTID { get; set; }
        public decimal RPBORONG { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
    }
}