// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MATTMACHINE
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string IP { get; set; }
        public short PORT { get; set; }
        public short MACHINETYPE { get; set; }
        public bool ACTIVE { get; set; }
    }
}