// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MATTENDANCEGROUPITEM
    {
        public string ID { get; set; }
        public string GROUPID { get; set; }
        public short DAY { get; set; }
        public DateTime BREAKSTART { get; set; }
        public DateTime BREAKEND { get; set; }
        public DateTime OUTTIME { get; set; }
        public short WORKHOUR { get; set; }
        public string STATUS { get; set; }

        public virtual MATTENDANCEGROUP GROUP { get; set; }
    }
}