// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MBANK
    {
        public string BANKID { get; set; }
        public string BANKNAME { get; set; }
        public bool ACTIVE { get; set; }
        public DateTime? CREATED { get; set; }
        public string CREATEBY { get; set; }
        public DateTime? UPDATED { get; set; }
        public string UPDATEBY { get; set; }
    }
}