// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MBLOCK
    {
        public MBLOCK()
        {
            DHS_DOKET = new HashSet<DHS_DOKET>();
            MPREMIMUATBLOCK = new HashSet<MPREMIMUATBLOCK>();
            MPREMIPANENBLOCK = new HashSet<MPREMIPANENBLOCK>();
            TGIITEM = new HashSet<TGIITEM>();
            THARVESTBLOCK = new HashSet<THARVESTBLOCK>();
            THARVESTCOLLECT = new HashSet<THARVESTCOLLECT>();
            THARVESTFINE = new HashSet<THARVESTFINE>();
            THARVESTPLANBLOCK = new HashSet<THARVESTPLANBLOCK>();
            THARVESTRESULT = new HashSet<THARVESTRESULT>();
            TLOADINGBLOCK = new HashSet<TLOADINGBLOCK>();
            TLOADINGCOLLECT = new HashSet<TLOADINGCOLLECT>();
            TRUNNINGACCOUNTBLOCK = new HashSet<TRUNNINGACCOUNTBLOCK>();
            TSPBDETAIL = new HashSet<TSPBDETAIL>();
            TSTOCKMOVEMENT = new HashSet<TSTOCKMOVEMENT>();
            TUPKEEPBLOCK = new HashSet<TUPKEEPBLOCK>();
            TUPKEEPMATERIALBATCH = new HashSet<TUPKEEPMATERIAL>();
            TUPKEEPMATERIALBLOCK = new HashSet<TUPKEEPMATERIAL>();
            TSPEKSI = new HashSet<TSPEKSI>();
            THARVESTWFMAXBRONDOLDETAIL = new HashSet<THARVESTWFMAXBRONDOLDETAIL>();
        }

        public string BLOCKID { get; set; }
        public string DIVID { get; set; }
        public short BLNTANAM { get; set; }
        public short THNTANAM { get; set; }
        public string JENISBIBIT { get; set; }
        public decimal LUASBLOCK { get; set; }
        public decimal CURRENTPLANTED { get; set; }
        public string TOPOGRAPI { get; set; }
        public string KELASTANAH { get; set; }
        public decimal BJR { get; set; }
        public short SPH { get; set; }
        public short PHASE { get; set; }
        public string COSTCTR { get; set; }
        public string WBS { get; set; }
        public DateTime EFFDATE { get; set; }

        public virtual MORGANIZATION BLOCK { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual ICollection<DHS_DOKET> DHS_DOKET { get; set; }
        public virtual ICollection<MPREMIMUATBLOCK> MPREMIMUATBLOCK { get; set; }
        public virtual ICollection<MPREMIPANENBLOCK> MPREMIPANENBLOCK { get; set; }
        public virtual ICollection<TGIITEM> TGIITEM { get; set; }
        public virtual ICollection<THARVESTBLOCK> THARVESTBLOCK { get; set; }
        public virtual ICollection<THARVESTCOLLECT> THARVESTCOLLECT { get; set; }
        public virtual ICollection<THARVESTFINE> THARVESTFINE { get; set; }
        public virtual ICollection<THARVESTPLANBLOCK> THARVESTPLANBLOCK { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULT { get; set; }
        public virtual ICollection<TLOADINGBLOCK> TLOADINGBLOCK { get; set; }
        public virtual ICollection<TLOADINGCOLLECT> TLOADINGCOLLECT { get; set; }
        public virtual ICollection<TRUNNINGACCOUNTBLOCK> TRUNNINGACCOUNTBLOCK { get; set; }
        public virtual ICollection<TSPBDETAIL> TSPBDETAIL { get; set; }
        public virtual ICollection<TSTOCKMOVEMENT> TSTOCKMOVEMENT { get; set; }
        public virtual ICollection<TUPKEEPBLOCK> TUPKEEPBLOCK { get; set; }
        public virtual ICollection<TUPKEEPMATERIAL> TUPKEEPMATERIALBATCH { get; set; }
        public virtual ICollection<TUPKEEPMATERIAL> TUPKEEPMATERIALBLOCK { get; set; }
        public virtual ICollection<TSPEKSI> TSPEKSI { get; set; }

        //custom
        public virtual ICollection<THARVESTBLOCKRESULT> THARVESTBLOCKRESULT { get; set; }
        public virtual ICollection<THARVESTWFMAXBRONDOLDETAIL> THARVESTWFMAXBRONDOLDETAIL { get; set; }
    }
}