// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MBLOCKHIST
    {
        public string BLOCKID { get; set; }
        public DateTime STARTDATE { get; set; }
        public DateTime? ENDDATE { get; set; }
        public string DIVID { get; set; }
        public short BLNTANAM { get; set; }
        public short THNTANAM { get; set; }
        public string JENISBIBIT { get; set; }
        public decimal LUASBLOCK { get; set; }
        public decimal CURRENTPLANTED { get; set; }
        public string TOPOGRAPI { get; set; }
        public string KELASTANAH { get; set; }
        public decimal BJR { get; set; }
        public short SPH { get; set; }
        public short PHASE { get; set; }
        public string COSTCTR { get; set; }
        public string WBS { get; set; }

        public virtual MORGANIZATION BLOCK { get; set; }
        public virtual MDIVISI DIV { get; set; }
    }
}