// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MCARD
    {
        public MCARD()
        {
            TCONTRACT = new HashSet<TCONTRACT>();
            TGREXPCODENavigation = new HashSet<TGR>();
            TGRVENDORCODENavigation = new HashSet<TGR>();
        }

        public string CODE { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public string ACCOUNTCODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACCOUNT ACCOUNTCODENavigation { get; set; }
        public virtual ICollection<TCONTRACT> TCONTRACT { get; set; }
        public virtual ICollection<TGR> TGREXPCODENavigation { get; set; }
        public virtual ICollection<TGR> TGRVENDORCODENavigation { get; set; }
    }
}