// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MCOMPANY
    {
        public MCOMPANY()
        {
            MUNIT = new HashSet<MUNIT>();
        }

        public string LEGALID { get; set; }
        public string NPWP { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string ADDR3 { get; set; }
        public string POSTALCODE { get; set; }
        public byte[] LOGO { get; set; }

        public virtual MORGANIZATION LEGAL { get; set; }
        public virtual ICollection<MUNIT> MUNIT { get; set; }
    }
}