// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MCURRENCY
    {
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string COUNTRY { get; set; }
        public string SYMBOL { get; set; }
        public decimal RATE { get; set; }
        public bool DEFAULT { get; set; }
    }
}