// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MDEPARTMENT
    {
        public MDEPARTMENT()
        {
            TICR = new HashSet<TICR>();
        }

        public string DEPTID { get; set; }
        public string DEPTNAME { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<TICR> TICR { get; set; }
    }
}