// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MDOCSTATUS
    {
        public MDOCSTATUS()
        {
            MPREMIMUAT = new HashSet<MPREMIMUAT>();
            MPREMIPANEN = new HashSet<MPREMIPANEN>();
            MPREMIRUNNINGACCOUNT = new HashSet<MPREMIRUNNINGACCOUNT>();
            TACCOUNTHISTORY = new HashSet<TACCOUNTHISTORY>();
            TGM = new HashSet<TGM>();
            TGR = new HashSet<TGR>();
            THARVEST = new HashSet<THARVEST>();
            THARVESTPLAN = new HashSet<THARVESTPLAN>();
            TJOURNAL = new HashSet<TJOURNAL>();
            TLOADING = new HashSet<TLOADING>();
            TOVERTIME = new HashSet<TOVERTIME>();
            TPAYMENT = new HashSet<TPAYMENT>();
            TRUNNINGACCOUNT = new HashSet<TRUNNINGACCOUNT>();
            TSPB = new HashSet<TSPB>();
            TSTOCKMOVEMENT = new HashSet<TSTOCKMOVEMENT>();
            TUPKEEP = new HashSet<TUPKEEP>();
            TSPEKSI = new HashSet<TSPEKSI>();
            TTRAVEL = new HashSet<TTRAVEL>();
            TCAPPINGEMP = new HashSet<TCAPPINGEMP>();
        }

        public string CODE { get; set; }
        public string NAME { get; set; }

        public virtual ICollection<MPREMIMUAT> MPREMIMUAT { get; set; }
        public virtual ICollection<MPREMIPANEN> MPREMIPANEN { get; set; }
        public virtual ICollection<MPREMIRUNNINGACCOUNT> MPREMIRUNNINGACCOUNT { get; set; }
        public virtual ICollection<TACCOUNTHISTORY> TACCOUNTHISTORY { get; set; }
        public virtual ICollection<TGM> TGM { get; set; }
        public virtual ICollection<TGR> TGR { get; set; }
        public virtual ICollection<THARVEST> THARVEST { get; set; }
        public virtual ICollection<THARVESTPLAN> THARVESTPLAN { get; set; }
        public virtual ICollection<TJOURNAL> TJOURNAL { get; set; }
        public virtual ICollection<TLOADING> TLOADING { get; set; }
        public virtual ICollection<TMILLGRADING> TMILLGRADING { get; set; }
        public virtual ICollection<TOVERTIME> TOVERTIME { get; set; }
        public virtual ICollection<TPAYMENT> TPAYMENT { get; set; }
        public virtual ICollection<TRUNNINGACCOUNT> TRUNNINGACCOUNT { get; set; }
        public virtual ICollection<TSPB> TSPB { get; set; }
        public virtual ICollection<TSTOCKMOVEMENT> TSTOCKMOVEMENT { get; set; }
        public virtual ICollection<TUPKEEP> TUPKEEP { get; set; }
        public virtual ICollection<TSPEKSI> TSPEKSI { get; set; }
        public virtual ICollection<TTRAVEL> TTRAVEL { get; set; }
        public virtual ICollection<TCAPPINGEMP> TCAPPINGEMP { get; set; }
    }
}