// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MEMPLOYEEFAMILY
    {
        public string EMPID { get; set; }
        public string KTPID { get; set; }
        public string FULLNAME { get; set; }
        public string GENDER { get; set; }
        public string PLACEOFBIRTH { get; set; }
        public DateTime BIRTHDAY { get; set; }
        public string EDUCATION { get; set; }
        public string RELATIONSHIP { get; set; }

        public virtual MEMPLOYEE EMP { get; set; }
    }
}