// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.EFCore.Model
{
    public partial class MEMPLOYEE
    {
        public MEMPLOYEE()
        {
            MEMPLOYEEFAMILY = new HashSet<MEMPLOYEEFAMILY>();
            MEMPLOYEEFILE = new HashSet<MEMPLOYEEFILE>();
            MEMPLOYEEHISTORY = new HashSet<MEMPLOYEEHISTORY>();
            MSCHEDULEEMPLOYEE = new HashSet<MSCHEDULEEMPLOYEE>();
            MVEHICLEDRIVERNavigation = new HashSet<MVEHICLE>();
            MVEHICLEHELPER = new HashSet<MVEHICLE>();
            TATTENDANCE = new HashSet<TATTENDANCE>();
            TATTENDANCESPL = new HashSet<TATTENDANCESPL>();
            TEMPLOYEEREGISTRATION = new HashSet<TEMPLOYEEREGISTRATION>();
            TEQUIPTIMESHEETACTIVITYHELPER = new HashSet<TEQUIPTIMESHEETACTIVITY>();
            TEQUIPTIMESHEETACTIVITYOPR = new HashSet<TEQUIPTIMESHEETACTIVITY>();
            TEQUIPTIMESHEETEMPLOYEE = new HashSet<TEQUIPTIMESHEETEMPLOYEE>();
            THARVESTBASE = new HashSet<THARVESTBASE>();
            THARVESTBLOCK = new HashSet<THARVESTBLOCK>();
            THARVESTCHECKER = new HashSet<THARVEST>();
            THARVESTCOLLECT = new HashSet<THARVESTCOLLECT>();
            THARVESTEMPLOYEEEMPLOYEE = new HashSet<THARVESTEMPLOYEE>();
            THARVESTEMPLOYEEGEMP = new HashSet<THARVESTEMPLOYEE>();
            THARVESTFINE = new HashSet<THARVESTFINE>();
            THARVESTKRANI = new HashSet<THARVEST>();
            THARVESTMANDOR = new HashSet<THARVEST>();
            THARVESTMANDOR1 = new HashSet<THARVEST>();
            THARVESTPLANCHECKER = new HashSet<THARVESTPLAN>();
            THARVESTPLANEMPLOYEE = new HashSet<THARVESTPLANEMPLOYEE>();
            THARVESTPLANEMPLOYEECALC = new HashSet<THARVESTPLANEMPLOYEECALC>();
            THARVESTPLANKRANI = new HashSet<THARVESTPLAN>();
            THARVESTPLANMANDOR = new HashSet<THARVESTPLAN>();
            THARVESTPLANMANDOR1 = new HashSet<THARVESTPLAN>();
            THARVESTRESULTEMPLOYEE = new HashSet<THARVESTRESULT>();
            THARVESTRESULTKRANI = new HashSet<THARVESTRESULT>();
            THARVESTRESULTMANDOR = new HashSet<THARVESTRESULT>();
            THARVESTRESULTMANDOR1 = new HashSet<THARVESTRESULT>();
            THARVESTRESULTSUPERVISOR = new HashSet<THARVESTRESULT>();
            TLOADING = new HashSet<TLOADING>();
            TLOADINGBASE = new HashSet<TLOADINGBASE>();
            TLOADINGBLOCK = new HashSet<TLOADINGBLOCK>();
            TLOADINGCOLLECT = new HashSet<TLOADINGCOLLECT>();
            TLOADINGDRIVER = new HashSet<TLOADINGDRIVER>();
            TLOADINGEMPLOYEE = new HashSet<TLOADINGEMPLOYEE>();
            TOVERTIME = new HashSet<TOVERTIME>();
            TPAYMENTATTREMP = new HashSet<TPAYMENTATTREMP>();
            TPAYMENTDETAILEMP = new HashSet<TPAYMENTDETAIL>();
            TPAYMENTDETAILSUPERVISOR = new HashSet<TPAYMENTDETAIL>();
            TPAYMENTITEM = new HashSet<TPAYMENTITEM>();
            TPREMICHECKER = new HashSet<TPREMICHECKER>();
            TPREMIMANDOR1 = new HashSet<TPREMIMANDOR1>();
            TPREMIMANDORKRANI = new HashSet<TPREMIMANDOR>();
            TPREMIMANDORMANDOR = new HashSet<TPREMIMANDOR>();
            TPREMIMANDORMANDOR1 = new HashSet<TPREMIMANDOR>();
            TPREMINONPANEN = new HashSet<TPREMINONPANEN>();
            TRKHACTUAL = new HashSet<TRKHACTUAL>();
            TRKHDETAIL = new HashSet<TRKHDETAIL>();
            TRUNNINGACCOUNT = new HashSet<TRUNNINGACCOUNT>();
            TSALARYITEM = new HashSet<TSALARYITEM>();
            TSALARYTYPEMAP = new HashSet<TSALARYTYPEMAP>();
            TSURATPERINGATAN = new HashSet<TSURATPERINGATAN>();
            TUPKEEP = new HashSet<TUPKEEP>();
            TUPKEEPEMPLOYEE = new HashSet<TUPKEEPEMPLOYEE>();
            TATTENDANCELOG = new HashSet<TATTENDANCELOG>();
            TATTENDANCETRX = new HashSet<TATTENDANCETRX>();
            TLOANEMP = new HashSet<TLOANEMP>();
            TSPEKSIEMP = new HashSet<TSPEKSI>();
            TSPEKSIMDR = new HashSet<TSPEKSI>();
            TTRAVEL = new HashSet<TTRAVEL>();
            TCAPPINGEMP = new HashSet<TCAPPINGEMP>();
            TATTENDANCEPROBLEMEMPLOYEE = new HashSet<TATTENDANCEPROBLEMEMPLOYEE>();
            THARVESTWFLEBIHBASISDETAIL = new HashSet<THARVESTWFLEBIHBASISDETAIL>();
            TPAYMENTWFADJUSTHKDETAIL = new HashSet<TPAYMENTWFADJUSTHKDETAIL>();
        }

        public string EMPID { get; set; }
        public string UNITCODE { get; set; }
        public string EMPCODE { get; set; }
        public string EMPNAME { get; set; }
        public string DIVID { get; set; }
        public string POSITIONID { get; set; }
        public string SUPERVISORID { get; set; }
        public string EMPTYPE { get; set; }
        public string STATUSID { get; set; }
        public decimal BASICWAGES { get; set; }
        public decimal KOPERASIDEDUCTION { get; set; }
        public string EMPSEX { get; set; }
        public decimal SALARYPRD1 { get; set; }
        public decimal SPSIDEDUCTION { get; set; }
        public DateTime BIRTHDAY { get; set; }
        public DateTime JOINTDATE { get; set; }
        
        public DateTime? STAFFDATE { get; set; }
        public DateTime? RESIGNEDDATE { get; set; }
        public short REMAININGLEAVE { get; set; }
        public short LEAVE { get; set; }
        public string GOLONGAN { get; set; }
        
        public bool PKWT { get; set; }
        public string NOSPK { get; set; }
        public string PLACEOFBIRTH { get; set; }
        public string RACE { get; set; }
        public string RELIGION { get; set; }
        public string EDUCATION { get; set; }
        public string KTPID { get; set; }
        public string KTPADDRESS { get; set; }
        public string NPWP { get; set; }
        public string KOTAASAL { get; set; }
        public string PROVINSI { get; set; }
        public string SPOUSEID { get; set; }
        public bool? BPJSKES { get; set; }
        public bool NATURA { get; set; }
        public int PINID { get; set; }
        public string ATTENDGROUPID { get; set; }
        public string STATUS { get; set; }
        public bool TRFHO { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEETYPE EMPTYPENavigation { get; set; }
        public virtual MPOSITION POSITION { get; set; }
        public virtual MSTATUS STATUSNavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
        public virtual MEMPLOYEEBANK MEMPLOYEEBANK { get; set; }
        public virtual ICollection<MEMPLOYEEFAMILY> MEMPLOYEEFAMILY { get; set; }
        public virtual ICollection<MEMPLOYEEFILE> MEMPLOYEEFILE { get; set; }
        public virtual ICollection<MEMPLOYEEHISTORY> MEMPLOYEEHISTORY { get; set; }
        public virtual ICollection<MSCHEDULEEMPLOYEE> MSCHEDULEEMPLOYEE { get; set; }
        public virtual ICollection<MVEHICLE> MVEHICLEDRIVERNavigation { get; set; }
        public virtual ICollection<MVEHICLE> MVEHICLEHELPER { get; set; }
        public virtual ICollection<TATTENDANCE> TATTENDANCE { get; set; }
        public virtual ICollection<TATTENDANCESPL> TATTENDANCESPL { get; set; }
        public virtual ICollection<TEMPLOYEEREGISTRATION> TEMPLOYEEREGISTRATION { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETACTIVITY> TEQUIPTIMESHEETACTIVITYHELPER { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETACTIVITY> TEQUIPTIMESHEETACTIVITYOPR { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETEMPLOYEE> TEQUIPTIMESHEETEMPLOYEE { get; set; }
        public virtual ICollection<THARVESTBASE> THARVESTBASE { get; set; }
        public virtual ICollection<THARVESTBLOCK> THARVESTBLOCK { get; set; }
        public virtual ICollection<THARVEST> THARVESTCHECKER { get; set; }
        public virtual ICollection<THARVESTCOLLECT> THARVESTCOLLECT { get; set; }
        public virtual ICollection<THARVESTEMPLOYEE> THARVESTEMPLOYEEEMPLOYEE { get; set; }
        public virtual ICollection<THARVESTEMPLOYEE> THARVESTEMPLOYEEGEMP { get; set; }
        public virtual ICollection<THARVESTFINE> THARVESTFINE { get; set; }
        public virtual ICollection<THARVEST> THARVESTKRANI { get; set; }
        public virtual ICollection<THARVEST> THARVESTMANDOR { get; set; }
        public virtual ICollection<THARVEST> THARVESTMANDOR1 { get; set; }
        public virtual ICollection<THARVESTPLAN> THARVESTPLANCHECKER { get; set; }
        public virtual ICollection<THARVESTPLANEMPLOYEE> THARVESTPLANEMPLOYEE { get; set; }
        public virtual ICollection<THARVESTPLANEMPLOYEECALC> THARVESTPLANEMPLOYEECALC { get; set; }
        public virtual ICollection<THARVESTPLAN> THARVESTPLANKRANI { get; set; }
        public virtual ICollection<THARVESTPLAN> THARVESTPLANMANDOR { get; set; }
        public virtual ICollection<THARVESTPLAN> THARVESTPLANMANDOR1 { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULTEMPLOYEE { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULTKRANI { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULTMANDOR { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULTMANDOR1 { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULTSUPERVISOR { get; set; }
        public virtual ICollection<TLOADING> TLOADING { get; set; }
        public virtual ICollection<TLOADINGBASE> TLOADINGBASE { get; set; }
        public virtual ICollection<TLOADINGBLOCK> TLOADINGBLOCK { get; set; }
        public virtual ICollection<TLOADINGCOLLECT> TLOADINGCOLLECT { get; set; }
        public virtual ICollection<TLOADINGDRIVER> TLOADINGDRIVER { get; set; }
        public virtual ICollection<TLOADINGEMPLOYEE> TLOADINGEMPLOYEE { get; set; }
        public virtual ICollection<TOVERTIME> TOVERTIME { get; set; }
        public virtual ICollection<TPAYMENTATTREMP> TPAYMENTATTREMP { get; set; }
        public virtual ICollection<TPAYMENTDETAIL> TPAYMENTDETAILEMP { get; set; }
        public virtual ICollection<TPAYMENTDETAIL> TPAYMENTDETAILSUPERVISOR { get; set; }
        public virtual ICollection<TPAYMENTITEM> TPAYMENTITEM { get; set; }
        public virtual ICollection<TPREMICHECKER> TPREMICHECKER { get; set; }
        public virtual ICollection<TPREMIMANDOR1> TPREMIMANDOR1 { get; set; }
        public virtual ICollection<TPREMIMANDOR> TPREMIMANDORKRANI { get; set; }
        public virtual ICollection<TPREMIMANDOR> TPREMIMANDORMANDOR { get; set; }
        public virtual ICollection<TPREMIMANDOR> TPREMIMANDORMANDOR1 { get; set; }
        public virtual ICollection<TPREMINONPANEN> TPREMINONPANEN { get; set; }
        public virtual ICollection<TRKHACTUAL> TRKHACTUAL { get; set; }
        public virtual ICollection<TRKHDETAIL> TRKHDETAIL { get; set; }
        public virtual ICollection<TRUNNINGACCOUNT> TRUNNINGACCOUNT { get; set; }
        public virtual ICollection<TSALARYITEM> TSALARYITEM { get; set; }
        public virtual ICollection<TSALARYTYPEMAP> TSALARYTYPEMAP { get; set; }
        public virtual ICollection<TSURATPERINGATAN> TSURATPERINGATAN { get; set; }
        public virtual ICollection<TUPKEEP> TUPKEEP { get; set; }
        public virtual ICollection<TUPKEEPEMPLOYEE> TUPKEEPEMPLOYEE { get; set; }
        public virtual ICollection<TLOANEMP> TLOANEMP { get; set; }
        public virtual ICollection<TSPEKSI> TSPEKSIEMP { get; set; }
        public virtual ICollection<TSPEKSI> TSPEKSIMDR { get; set; }
        public virtual ICollection<TTRAVEL> TTRAVEL { get; set; }
        public virtual ICollection<TCAPPINGEMP> TCAPPINGEMP { get; set; }

        //custom
        public virtual ICollection<TATTENDANCELOG> TATTENDANCELOG { get; set; }
        public virtual ICollection<TATTENDANCETRX> TATTENDANCETRX { get; set; }
        public virtual ICollection<TATTENDANCEPROBLEMEMPLOYEE> TATTENDANCEPROBLEMEMPLOYEE { get; set; }
        public virtual ICollection<THARVESTWFLEBIHBASISDETAIL> THARVESTWFLEBIHBASISDETAIL { get; set; }
        public virtual ICollection<TPAYMENTWFADJUSTHKDETAIL> TPAYMENTWFADJUSTHKDETAIL { get; set; }
    }
}