// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MEMPLOYEEPINRANGE
    {
        public int ID { get; set; }
        public int MINPIN { get; set; }
        public int MAXPIN { get; set; }
    }
}