// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MEMPLOYEEFILE
    {
        public string EMPID { get; set; }
        public long FILEID { get; set; }
        public string DESCRIPTION { get; set; }
        public string FILENAME { get; set; }
        public string FILETYPE { get; set; }
        public int FILESIZE { get; set; }

        public virtual MEMPLOYEE EMP { get; set; }
    }
}