// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MEMPLOYEEDEL
    {
        public long ID { get; set; }
        public string UNITCODE { get; set; }
        public string DOCNO { get; set; }
        public string EMPID { get; set; }
        public decimal TOTSALARY { get; set; }
        public bool FLAG { get; set; }
        public DateTime? UPDATED { get; set; }
    }
}