// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MEMPLOYEEBANK
    {
        public string EMPID { get; set; }
        public string BANKID { get; set; }
        public string NO { get; set; }
        public string NAME { get; set; }
        public bool BPJSJKK { get; set; }
        public bool BPJSJHT { get; set; }
        public bool BPJSJP { get; set; }
        public string BPJSKESEHATANNO { get; set; }
        public string BPJSKESEHATANET { get; set; }
        public string BPJSKETENAGAKERJAANNO { get; set; }
        public string BPJSKETENAGAKERJAANNPP { get; set; }
        public decimal BPJSBASE { get; set; }
        public decimal BPJSKESEHATANBASE { get; set; }

        public virtual MEMPLOYEE EMP { get; set; }
    }
}