// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MEMPLOYEETYPE
    {
        public MEMPLOYEETYPE()
        {
            MEMPLOYEE = new HashSet<MEMPLOYEE>();
            MEMPLOYEEHISTORY = new HashSet<MEMPLOYEEHISTORY>();
            TEMPLOYEECHANGEEMPTYPENavigation = new HashSet<TEMPLOYEECHANGE>();
            TEMPLOYEECHANGENEWEMPTYPENavigation = new HashSet<TEMPLOYEECHANGE>();
            TEMPLOYEEREGISTRATION = new HashSet<TEMPLOYEEREGISTRATION>();
        }

        public string ID { get; set; }
        public string CODE { get; set; }
        public string HVTCODE { get; set; }
        public string NAME { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<MEMPLOYEE> MEMPLOYEE { get; set; }
        public virtual ICollection<MEMPLOYEEHISTORY> MEMPLOYEEHISTORY { get; set; }
        public virtual ICollection<TEMPLOYEECHANGE> TEMPLOYEECHANGEEMPTYPENavigation { get; set; }
        public virtual ICollection<TEMPLOYEECHANGE> TEMPLOYEECHANGENEWEMPTYPENavigation { get; set; }
        public virtual ICollection<TEMPLOYEEREGISTRATION> TEMPLOYEEREGISTRATION { get; set; }
    }
}