// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MEMPLOYEEHISTORY
    {
        public string EMPID { get; set; }
        public DateTime STARTDATE { get; set; }
        public DateTime? ENDDATE { get; set; }
        public string UNITCODE { get; set; }
        public string DIVID { get; set; }
        public string POSITIONID { get; set; }
        public string EMPTYPE { get; set; }
        public string STATUSID { get; set; }
        public decimal BASICWAGES { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE EMP { get; set; }
        public virtual MEMPLOYEETYPE EMPTYPENavigation { get; set; }
        public virtual MPOSITION POSITION { get; set; }
        public virtual MSTATUS STATUS { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}