// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MHARVESTTYPE
    {
        public MHARVESTTYPE()
        {
            THARVEST = new HashSet<THARVEST>();
            THARVESTPLAN = new HashSet<THARVESTPLAN>();
            TLOADING = new HashSet<TLOADING>();
        }

        public short CODE { get; set; }
        public string NAME { get; set; }

        public virtual ICollection<THARVEST> THARVEST { get; set; }
        public virtual ICollection<THARVESTPLAN> THARVESTPLAN { get; set; }
        public virtual ICollection<TLOADING> TLOADING { get; set; }
    }
}