// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MICRAPP
    {
        public MICRAPP()
        {
            TICRAPP = new HashSet<TICRAPP>();
        }

        public string APPID { get; set; }
        public string APPNAME { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<TICRAPP> TICRAPP { get; set; }
    }
}