// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MJAMSOSTEK
    {
        public string UNITCODE { get; set; }
        public decimal JKK { get; set; }
        public decimal JKM { get; set; }
        public decimal EMPLOYEE { get; set; }
        public decimal ENTERPRISE { get; set; }
        public decimal KESEMP { get; set; }
        public decimal KESCOMP { get; set; }
        public decimal JPEMP { get; set; }
        public decimal JPCOMP { get; set; }
        public decimal JPMAX { get; set; }
        public decimal BKSPPS { get; set; }
        public decimal PTKPS { get; set; }
        public decimal PTKPM { get; set; }
        public decimal PTKPM1 { get; set; }
        public decimal PTKPM2 { get; set; }
        public decimal PTKPM3 { get; set; }
        public decimal POSBENEFIT { get; set; }
        public decimal MAXPOSBENEFIT { get; set; }
        public decimal NPWP { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}