// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MJOURNALTYPE
    {
        public MJOURNALTYPE()
        {
            TACCOUNTHISTORY = new HashSet<TACCOUNTHISTORY>();
            TJOURNAL = new HashSet<TJOURNAL>();
        }

        public string CODE { get; set; }
        public string MODUL { get; set; }
        public string NAME { get; set; }

        public virtual ICollection<TACCOUNTHISTORY> TACCOUNTHISTORY { get; set; }
        public virtual ICollection<TJOURNAL> TJOURNAL { get; set; }
    }
}