// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MMATERIAL
    {
        public MMATERIAL()
        {
            TACTIVITYMATERIALMAP = new HashSet<TACTIVITYMATERIALMAP>();
            TCOGS = new HashSet<TCOGS>();
            TEQUIPTIMESHEETMATERIAL = new HashSet<TEQUIPTIMESHEETMATERIAL>();
            TGIITEM = new HashSet<TGIITEM>();
            TGMITEM = new HashSet<TGMITEM>();
            TGRITEM = new HashSet<TGRITEM>();
            TRKHHERBISIDA = new HashSet<TRKHHERBISIDA>();
            TRKHMATERIAL = new HashSet<TRKHMATERIAL>();
            TSTOCK = new HashSet<TSTOCK>();
            TSTOCKADJUST = new HashSet<TSTOCKADJUST>();
            TSTOCKMOVEMENT = new HashSet<TSTOCKMOVEMENT>();
            TUPKEEPMATERIAL = new HashSet<TUPKEEPMATERIAL>();
        }

        public string MATERIALID { get; set; }
        public string MATERIALNAME { get; set; }
        public string UOM { get; set; }
        public string ACCOUNTCODE { get; set; }
        public bool ACTIVE { get; set; }
        public bool REQBATCH { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACCOUNT ACCOUNTCODENavigation { get; set; }
        public virtual ICollection<TACTIVITYMATERIALMAP> TACTIVITYMATERIALMAP { get; set; }
        public virtual ICollection<TCOGS> TCOGS { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETMATERIAL> TEQUIPTIMESHEETMATERIAL { get; set; }
        public virtual ICollection<TGIITEM> TGIITEM { get; set; }
        public virtual ICollection<TGMITEM> TGMITEM { get; set; }
        public virtual ICollection<TGRITEM> TGRITEM { get; set; }
        public virtual ICollection<TRKHHERBISIDA> TRKHHERBISIDA { get; set; }
        public virtual ICollection<TRKHMATERIAL> TRKHMATERIAL { get; set; }
        public virtual ICollection<TSTOCK> TSTOCK { get; set; }
        public virtual ICollection<TSTOCKADJUST> TSTOCKADJUST { get; set; }
        public virtual ICollection<TSTOCKMOVEMENT> TSTOCKMOVEMENT { get; set; }
        public virtual ICollection<TUPKEEPMATERIAL> TUPKEEPMATERIAL { get; set; }
    }
}