// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MMENUACCESS
    {
        public string CODE { get; set; }
        public string PART { get; set; }
        public string PERMISSION { get; set; }

        public virtual MMENU CODENavigation { get; set; }
    }
}