// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MMENU
    {
        public MMENU()
        {
            MMENUACCESS = new HashSet<MMENUACCESS>();
            MROLEFORM = new HashSet<MROLEFORM>();
        }

        public string MENUCODE { get; set; }
        public string ALIAS { get; set; }
        public string TEXT { get; set; }
        public string PARENTCODE { get; set; }
        public bool ISPARENT { get; set; }
        public bool VISIBLE { get; set; }
        public bool ENABLE { get; set; }
        public short SORT { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<MMENUACCESS> MMENUACCESS { get; set; }
        public virtual ICollection<MROLEFORM> MROLEFORM { get; set; }
    }
}