// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MMILL
    {
        public MMILL()
        {
            TSPB = new HashSet<TSPB>();
        }

        public string MILLCODE { get; set; }
        public string MILLNAME { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<TSPB> TSPB { get; set; }
    }
}