// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MORGANIZATION
    {
        public MORGANIZATION()
        {
            MACTIVITYRATE = new HashSet<MACTIVITYRATE>();
            MBLOCKHIST = new HashSet<MBLOCKHIST>();
            MPOSITIONDETAIL = new HashSet<MPOSITIONDETAIL>();
            MRANGEFROMNavigation = new HashSet<MRANGE>();
            MRANGETONavigation = new HashSet<MRANGE>();
            MSTORELOCATION = new HashSet<MSTORELOCATION>();
            MTPH = new HashSet<MTPH>();
            MVEHICLE = new HashSet<MVEHICLE>();
            TACCOUNTHISTORY = new HashSet<TACCOUNTHISTORY>();
            TATTENDANCESPL = new HashSet<TATTENDANCESPL>();
            TCLOSEYEAR = new HashSet<TCLOSEYEAR>();
            TCONTRACT = new HashSet<TCONTRACT>();
            TEQUIPTIMESHEETACTIVITYBLOCKFROM = new HashSet<TEQUIPTIMESHEETACTIVITY>();
            TEQUIPTIMESHEETACTIVITYBLOCKTO = new HashSet<TEQUIPTIMESHEETACTIVITY>();
            TEQUIPTIMESHEETACTIVITYREC = new HashSet<TEQUIPTIMESHEETACTIVITY>();
            TEQUIPTIMESHEETDIV = new HashSet<TEQUIPTIMESHEET>();
            TEQUIPTIMESHEETUNIT = new HashSet<TEQUIPTIMESHEET>();
            THARVESTASIS = new HashSet<THARVESTASIS>();
            THARVESTBASE = new HashSet<THARVESTBASE>();
            THARVESTBLOCKRESULT = new HashSet<THARVESTBLOCKRESULT>();
            THARVESTROT = new HashSet<THARVESTROT>();
            TJOURNALITEM = new HashSet<TJOURNALITEM>();
            TLOADINGASIS = new HashSet<TLOADINGASIS>();
            TLOADINGBASE = new HashSet<TLOADINGBASE>();
            TLOADINGBLOCKRESULT = new HashSet<TLOADINGBLOCKRESULT>();
            TLOADINGROT = new HashSet<TLOADINGROT>();
            TOVERTIME = new HashSet<TOVERTIME>();
            TPREMICHECKER = new HashSet<TPREMICHECKER>();
            TPREMIMANDOR1 = new HashSet<TPREMIMANDOR1>();
            TRKH = new HashSet<TRKH>();
            TRKHDETAIL = new HashSet<TRKHDETAIL>();
            TRKHTAKSASI = new HashSet<TRKHTAKSASI>();
            TSALARYITEM = new HashSet<TSALARYITEM>();
            TSALARYTYPEMAP = new HashSet<TSALARYTYPEMAP>();
        }

        public string ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MBLOCK MBLOCK { get; set; }
        public virtual MCOMPANY MCOMPANY { get; set; }
        public virtual MDIVISI MDIVISI { get; set; }
        public virtual MUNIT MUNIT { get; set; }
        public virtual ICollection<MACTIVITYRATE> MACTIVITYRATE { get; set; }
        public virtual ICollection<MBLOCKHIST> MBLOCKHIST { get; set; }
        public virtual ICollection<MPOSITIONDETAIL> MPOSITIONDETAIL { get; set; }
        public virtual ICollection<MRANGE> MRANGEFROMNavigation { get; set; }
        public virtual ICollection<MRANGE> MRANGETONavigation { get; set; }
        public virtual ICollection<MSTORELOCATION> MSTORELOCATION { get; set; }
        public virtual ICollection<MTPH> MTPH { get; set; }
        public virtual ICollection<MVEHICLE> MVEHICLE { get; set; }
        public virtual ICollection<TACCOUNTHISTORY> TACCOUNTHISTORY { get; set; }
        public virtual ICollection<TATTENDANCESPL> TATTENDANCESPL { get; set; }
        public virtual ICollection<TCLOSEYEAR> TCLOSEYEAR { get; set; }
        public virtual ICollection<TCONTRACT> TCONTRACT { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETACTIVITY> TEQUIPTIMESHEETACTIVITYBLOCKFROM { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETACTIVITY> TEQUIPTIMESHEETACTIVITYBLOCKTO { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETACTIVITY> TEQUIPTIMESHEETACTIVITYREC { get; set; }
        public virtual ICollection<TEQUIPTIMESHEET> TEQUIPTIMESHEETDIV { get; set; }
        public virtual ICollection<TEQUIPTIMESHEET> TEQUIPTIMESHEETUNIT { get; set; }
        public virtual ICollection<THARVESTASIS> THARVESTASIS { get; set; }
        public virtual ICollection<THARVESTBASE> THARVESTBASE { get; set; }
        public virtual ICollection<THARVESTBLOCKRESULT> THARVESTBLOCKRESULT { get; set; }
        public virtual ICollection<THARVESTROT> THARVESTROT { get; set; }
        public virtual ICollection<TJOURNALITEM> TJOURNALITEM { get; set; }
        public virtual ICollection<TLOADINGASIS> TLOADINGASIS { get; set; }
        public virtual ICollection<TLOADINGBASE> TLOADINGBASE { get; set; }
        public virtual ICollection<TLOADINGBLOCKRESULT> TLOADINGBLOCKRESULT { get; set; }
        public virtual ICollection<TLOADINGROT> TLOADINGROT { get; set; }
        public virtual ICollection<TOVERTIME> TOVERTIME { get; set; }
        public virtual ICollection<TPREMICHECKER> TPREMICHECKER { get; set; }
        public virtual ICollection<TPREMIMANDOR1> TPREMIMANDOR1 { get; set; }
        public virtual ICollection<TRKH> TRKH { get; set; }
        public virtual ICollection<TRKHDETAIL> TRKHDETAIL { get; set; }
        public virtual ICollection<TRKHTAKSASI> TRKHTAKSASI { get; set; }
        public virtual ICollection<TSALARYITEM> TSALARYITEM { get; set; }
        public virtual ICollection<TSALARYTYPEMAP> TSALARYTYPEMAP { get; set; }
    }
}