// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPAYROLLACCOUNT
    {
        public string CODE { get; set; }
        public string ACCOUNT1 { get; set; }
        public string ACCOUNT2 { get; set; }
        public string ACCOUNT3 { get; set; }
        public string ACCOUNT4 { get; set; }
        public bool FLAG { get; set; }

        public virtual MACCOUNT ACCOUNT1Navigation { get; set; }
        public virtual MACCOUNT ACCOUNT2Navigation { get; set; }
        public virtual MACCOUNT ACCOUNT3Navigation { get; set; }
        public virtual MACCOUNT ACCOUNT4Navigation { get; set; }
    }
}