// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPAYMENTSCHEME
    {
        public string UNITCODE { get; set; }
        public decimal PENSIONFUND { get; set; }
        public decimal PENSIONEMPLOYEE { get; set; }
        public decimal PENSIONCOMPANY { get; set; }
        public decimal RICEEMPLOYEE { get; set; }
        public decimal RICEWIFE { get; set; }
        public decimal RICECHILDREN { get; set; }
        public short TOTALDAYS { get; set; }
        public decimal PROVINCEWAGES { get; set; }
        public decimal TAXPAIDBYGOVERMENT { get; set; }
        public bool BHLPAIDTWICE { get; set; }
        public string RICEPAIDASMONEY { get; set; }
        public bool RICEPRICEDISPLAYED { get; set; }
        public decimal SKUDAILYWAGES { get; set; }
        public decimal BHLDAILYWAGES { get; set; }
        public string PREMIBASEDCALCULATION { get; set; }
        public decimal MANDORPREMIPCT { get; set; }
        public decimal MANDORPREMIPCTBHL { get; set; }
        public decimal MANDORPENALTYPCT { get; set; }
        public decimal MANDORBRONDOLPREMIPCT { get; set; }
        public decimal MANDORBRONDOLPREMIPCTBHL { get; set; }
        public decimal MANDORBRONDOLPENALTYPCT { get; set; }
        public decimal MANDOR1PREMIPCT { get; set; }
        public decimal MANDOR1PENALTYPCT { get; set; }
        public decimal KRANIPREMIPCT { get; set; }
        public decimal KRANIPREMIPCTBHL { get; set; }
        public decimal KRANIPENALTYPCT { get; set; }
        public decimal KRANIBRONDOLSKU { get; set; }
        public decimal KRANIBRONDOLBHL { get; set; }
        public decimal CHECKERPREMIPCT { get; set; }
        public string PREMISYSTEM { get; set; }
        public int MINEMPLOYEE { get; set; }
        public short MININSKU { get; set; }
        public decimal RATEINSKU { get; set; }
        public short MININBHL { get; set; }
        public decimal RATEINBHL { get; set; }
        public short MININMDR { get; set; }
        public decimal RATEINNDR { get; set; }
        public short MININKRN { get; set; }
        public decimal RATEINKRN { get; set; }
        public short MININMDR1 { get; set; }
        public decimal RATEINMDR1 { get; set; }
        public bool BHLTOBASE { get; set; }
        public bool OVERTIMERICEADD { get; set; }
        public bool HARVESTKBHK { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MPREMISYSTEM PREMISYSTEMNavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}