// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPENALTYTYPE
    {
        public MPENALTYTYPE()
        {
            MPENALTY = new HashSet<MPENALTY>();
            THARVESTFINE = new HashSet<THARVESTFINE>();
        }

        public string PENALTYCODE { get; set; }
        public short PENALTYTYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<MPENALTY> MPENALTY { get; set; }
        public virtual ICollection<THARVESTFINE> THARVESTFINE { get; set; }
    }
}