// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPENALTY
    {
        public string PENALTYID { get; set; }
        public string UNITCODE { get; set; }
        public string PENALTYCODE { get; set; }
        public decimal QTY { get; set; }
        public decimal AMOUNT { get; set; }
        public string REMARK { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATEDDATE { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATEDDATE { get; set; }

        public virtual MPENALTYTYPE PENALTYCODENavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}