// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPERIOD
    {
        public string PERIODCODE { get; set; }
        public string UNITCODE { get; set; }
        public short MONTH { get; set; }
        public short YEAR { get; set; }
        public DateTime FROM1 { get; set; }
        public DateTime FROM2 { get; set; }
        public DateTime TO1 { get; set; }
        public DateTime TO2 { get; set; }
        public decimal RICEPRICE1 { get; set; }
        public decimal RICEPRICE2 { get; set; }
        public bool ACTIVE1 { get; set; }
        public bool ACTIVE2 { get; set; }
        public string REMARK { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MUNIT UNIT { get; set; }
    }
}