// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPOSITION
    {
        public MPOSITION()
        {
            MEMPLOYEE = new HashSet<MEMPLOYEE>();
            MEMPLOYEEHISTORY = new HashSet<MEMPLOYEEHISTORY>();
            MPOSITIONDETAIL = new HashSet<MPOSITIONDETAIL>();
            TEMPLOYEECHANGENEWPOSITION = new HashSet<TEMPLOYEECHANGE>();
            TEMPLOYEECHANGEPOSITION = new HashSet<TEMPLOYEECHANGE>();
            TEMPLOYEEREGISTRATION = new HashSet<TEMPLOYEEREGISTRATION>();
            THARVESTRESULT = new HashSet<THARVESTRESULT>();
            TPAYMENTDETAIL = new HashSet<TPAYMENTDETAIL>();
            TSALARYTYPEMAP = new HashSet<TSALARYTYPEMAP>();
        }

        public string POSITIONID { get; set; }
        public string POSITIONNAME { get; set; }
        public short? GROUPID { get; set; }
        public short POSFLAG { get; set; }
        public string GENDERFLAG { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MPOSITIONGROUP GROUP { get; set; }
        public virtual ICollection<MEMPLOYEE> MEMPLOYEE { get; set; }
        public virtual ICollection<MEMPLOYEEHISTORY> MEMPLOYEEHISTORY { get; set; }
        public virtual ICollection<MPOSITIONDETAIL> MPOSITIONDETAIL { get; set; }
        public virtual ICollection<TEMPLOYEECHANGE> TEMPLOYEECHANGENEWPOSITION { get; set; }
        public virtual ICollection<TEMPLOYEECHANGE> TEMPLOYEECHANGEPOSITION { get; set; }
        public virtual ICollection<TEMPLOYEEREGISTRATION> TEMPLOYEEREGISTRATION { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULT { get; set; }
        public virtual ICollection<TPAYMENTDETAIL> TPAYMENTDETAIL { get; set; }
        public virtual ICollection<TSALARYTYPEMAP> TSALARYTYPEMAP { get; set; }
    }
}