// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPOSITIONDETAIL
    {
        public string UNITID { get; set; }
        public string POSID { get; set; }
        public bool ALLOWOVERTIME { get; set; }
        public bool ALLOWBORONG { get; set; }
        public bool ALLOWSCHEDULE { get; set; }
        public short MAXEMP { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MPOSITION POS { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
    }
}