// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPREMIRUNNINGACCOUNTID
    {
        public string PREMIRUNNINGACCOUNTID { get; set; }
        public string RUNNINGACCOUNTID { get; set; }
        public string STATUS { get; set; }
    }
}