// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPREMIRUNNINGACCOUNT
    {
        public string PREMIRUNNINGACCOUNTID { get; set; }
        public string UNITCODE { get; set; }
        public string BASISGROUP { get; set; }
        public string RUNNINGACCOUNTTYPE { get; set; }
        public string OPERATORTYPE { get; set; }
        public string ACTID { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal? RANGE1 { get; set; }
        public decimal? RANGE2 { get; set; }
        public decimal? BASE1 { get; set; }
        public decimal? PREMI1 { get; set; }
        public decimal? EXCEED1 { get; set; }
        public decimal? BASE2 { get; set; }
        public decimal? PREMI2 { get; set; }
        public decimal? EXCEED2 { get; set; }
        public decimal? BASE3 { get; set; }
        public decimal? PREMI3 { get; set; }
        public decimal? EXCEED3 { get; set; }
        public string PREMISYSTEM { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime? CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime? UPDATED { get; set; }

        public virtual MDOCSTATUS STATUSNavigation { get; set; }
    }
}