// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPREMIMUAT
    {
        public MPREMIMUAT()
        {
            MPREMIMUATBLOCK = new HashSet<MPREMIMUATBLOCK>();
        }

        public string PREMIMUATID { get; set; }
        public string UNITCODE { get; set; }
        public string BASISGROUP { get; set; }
        public string DESCRIPTION { get; set; }
        public string VEHICLETYPEID { get; set; }
        public string ACTID { get; set; }
        public short HARVESTTYPE { get; set; }
        public string EMPLOYEETYPE { get; set; }
        public decimal BASE1 { get; set; }
        public decimal BASE2 { get; set; }
        public decimal BASE3 { get; set; }
        public decimal BASE4 { get; set; }
        public decimal BASE5 { get; set; }
        public decimal BASE6 { get; set; }
        public decimal FRIDAY1 { get; set; }
        public decimal FRIDAY2 { get; set; }
        public decimal FRIDAY3 { get; set; }
        public decimal PREMI1 { get; set; }
        public decimal PREMI2 { get; set; }
        public decimal PREMI3 { get; set; }
        public decimal PREMI4 { get; set; }
        public decimal PREMI5 { get; set; }
        public decimal PREMI6 { get; set; }
        public decimal EXCEED1 { get; set; }
        public decimal EXCEED2 { get; set; }
        public decimal EXCEED3 { get; set; }
        public decimal EXCEED4 { get; set; }
        public decimal EXCEED5 { get; set; }
        public decimal EXCEED6 { get; set; }
        public decimal RPBORONG { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
        public virtual ICollection<MPREMIMUATBLOCK> MPREMIMUATBLOCK { get; set; }
    }
}