// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPREMIPANEN
    {
        public MPREMIPANEN()
        {
            MPREMIPANENBLOCK = new HashSet<MPREMIPANENBLOCK>();
        }

        public string PREMIPANENID { get; set; }
        public string UNITCODE { get; set; }
        public string BASISGROUP { get; set; }
        public string DESCRIPTION { get; set; }
        public string ACTID { get; set; }
        public short HARVESTTYPE { get; set; }
        public string EMPLOYEETYPE { get; set; }
        public decimal BASE1 { get; set; }
        public decimal BASE2 { get; set; }
        public decimal BASE3 { get; set; }
        public decimal FRIDAY1 { get; set; }
        public decimal FRIDAY2 { get; set; }
        public decimal FRIDAY3 { get; set; }
        public decimal PREMI1 { get; set; }
        public decimal PREMI2 { get; set; }
        public decimal PREMI3 { get; set; }
        public decimal EXCEED1 { get; set; }
        public decimal EXCEED2 { get; set; }
        public decimal EXCEED3 { get; set; }
        public decimal DBASE1 { get; set; }
        public decimal DBASE2 { get; set; }
        public decimal DBASE3 { get; set; }
        public decimal DPREMI1 { get; set; }
        public decimal DPREMI2 { get; set; }
        public decimal DPREMI3 { get; set; }
        public decimal DEXCEED1 { get; set; }
        public decimal DEXCEED2 { get; set; }
        public decimal DEXCEED3 { get; set; }
        public decimal GBASE1 { get; set; }
        public decimal GBASE2 { get; set; }
        public decimal GBASE3 { get; set; }
        public decimal GPREMI1 { get; set; }
        public decimal GPREMI2 { get; set; }
        public decimal GPREMI3 { get; set; }
        public decimal GEXCEED1 { get; set; }
        public decimal GEXCEED2 { get; set; }
        public decimal GEXCEED3 { get; set; }
        public decimal PKKTGI { get; set; }
        public decimal HABASE { get; set; }
        public decimal HAPREMI { get; set; }
        public decimal ATTPREMI { get; set; }
        public decimal GERDANBASE { get; set; }
        public decimal RPBORONG { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
        public virtual ICollection<MPREMIPANENBLOCK> MPREMIPANENBLOCK { get; set; }
    }
}