// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MPRODUCT
    {
        public MPRODUCT()
        {
            MPREMIOPERATOR = new HashSet<MPREMIOPERATOR>();
        }

        public short ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public bool ACTIVE { get; set; }

        public virtual ICollection<MPREMIOPERATOR> MPREMIOPERATOR { get; set; }
    }
}