// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MQLYCAT
    {
        public short ID { get; set; }
        public string NAME { get; set; }
        public string PROD { get; set; }
    }
}