// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MROLEUSER
    {
        public MROLEUSER()
        {
            MROLEFORM = new HashSet<MROLEFORM>();
            MUSERMASTER = new HashSet<MUSERMASTER>();
        }

        public string ROLEID { get; set; }
        public string ROLENAME { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<MROLEFORM> MROLEFORM { get; set; }
        public virtual ICollection<MUSERMASTER> MUSERMASTER { get; set; }
    }
}