// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MROLEFORM
    {
        public string ROLEID { get; set; }
        public string MENUCODE { get; set; }
        public bool FADD { get; set; }
        public bool FDEL { get; set; }
        public bool FEDIT { get; set; }
        public bool FAPPR { get; set; }
        public bool FCANCEL { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MMENU MENU { get; set; }
        public virtual MROLEUSER ROLE { get; set; }
    }
}