// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MRUNNUMBER
    {
        public string CODE { get; set; }
        public int NUMBER { get; set; }
        public int MAX { get; set; }
    }
}