// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MRUNNINGACCOUNT
    {
        public MRUNNINGACCOUNT()
        {
            TRUNNINGACCOUNT = new HashSet<TRUNNINGACCOUNT>();
        }

        public string UNITCODE { get; set; }
        public string RUNNINGACCOUNTID { get; set; }
        public string RUNNINGACCOUNTNAME { get; set; }
        public string RUNNINGACCOUNTYPE { get; set; }
        public string UOM { get; set; }
        public int? YEAR { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MRUNNINGACCOUNTTYPE RUNNINGACCOUNTYPENavigation { get; set; }
        public virtual ICollection<TRUNNINGACCOUNT> TRUNNINGACCOUNT { get; set; }
    }
}