// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MRUNNINGACCOUNTTYPE
    {
        public MRUNNINGACCOUNTTYPE()
        {
            MRUNNINGACCOUNT = new HashSet<MRUNNINGACCOUNT>();
        }

        public string CODE { get; set; }
        public string NAME { get; set; }
        public string UOM { get; set; }

        public virtual ICollection<MRUNNINGACCOUNT> MRUNNINGACCOUNT { get; set; }
    }
}