// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MSALARYTYPE
    {
        public MSALARYTYPE()
        {
            TPAYMENTITEM = new HashSet<TPAYMENTITEM>();
            TSALARYITEM = new HashSet<TSALARYITEM>();
            TSALARYTYPEMAP = new HashSet<TSALARYTYPEMAP>();
        }

        public string ID { get; set; }
        public string NAME { get; set; }
        public string SYSCODE { get; set; }
        public string PAYCODE { get; set; }
        public bool? DEDUCT { get; set; }
        public string SLIPNAME { get; set; }
        public bool? AUTO { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<TPAYMENTITEM> TPAYMENTITEM { get; set; }
        public virtual ICollection<TSALARYITEM> TSALARYITEM { get; set; }
        public virtual ICollection<TSALARYTYPEMAP> TSALARYTYPEMAP { get; set; }
    }
}