// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MSCHEDULEEMPLOYEE
    {
        public string ID { get; set; }
        public string UNITID { get; set; }
        public string EMPLOYEEID { get; set; }
        public DateTime DATE { get; set; }
        public bool HOLIDAY { get; set; }
        public DateTime INSTART { get; set; }
        public DateTime INEND { get; set; }
        public DateTime OUTSTART { get; set; }
        public DateTime OUTEND { get; set; }
        public DateTime BREAKSTART { get; set; }
        public DateTime BREAKEND { get; set; }
        public DateTime INTIME { get; set; }
        public DateTime OUTTIME { get; set; }
        public short WORKHOUR { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MEMPLOYEE EMPLOYEE { get; set; }
    }
}