// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MSTATUS
    {
        public MSTATUS()
        {
            MEMPLOYEE = new HashSet<MEMPLOYEE>();
            MEMPLOYEEHISTORY = new HashSet<MEMPLOYEEHISTORY>();
            TEMPLOYEECHANGENEWSTATUS = new HashSet<TEMPLOYEECHANGE>();
            TEMPLOYEECHANGESTATUS = new HashSet<TEMPLOYEECHANGE>();
            TEMPLOYEEREGISTRATION = new HashSet<TEMPLOYEEREGISTRATION>();
            THARVESTRESULT = new HashSet<THARVESTRESULT>();
            TPAYMENTDETAIL = new HashSet<TPAYMENTDETAIL>();
        }

        public string STATUSID { get; set; }
        public string STATUSNAME { get; set; }
        public short SPOUSE { get; set; }
        public short CHILDREN { get; set; }
        public string FAMILYSTATUS { get; set; }
        public string TAXSTATUS { get; set; }
        public string ABSENSEX { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<MEMPLOYEE> MEMPLOYEE { get; set; }
        public virtual ICollection<MEMPLOYEEHISTORY> MEMPLOYEEHISTORY { get; set; }
        public virtual ICollection<TEMPLOYEECHANGE> TEMPLOYEECHANGENEWSTATUS { get; set; }
        public virtual ICollection<TEMPLOYEECHANGE> TEMPLOYEECHANGESTATUS { get; set; }
        public virtual ICollection<TEMPLOYEEREGISTRATION> TEMPLOYEEREGISTRATION { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULT { get; set; }
        public virtual ICollection<TPAYMENTDETAIL> TPAYMENTDETAIL { get; set; }
    }
}