// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MSTORELOCATION
    {
        public MSTORELOCATION()
        {
            TGI = new HashSet<TGI>();
            TGMDESTCODENavigation = new HashSet<TGM>();
            TGMSRCCODENavigation = new HashSet<TGM>();
            TGR = new HashSet<TGR>();
            TSTOCK = new HashSet<TSTOCK>();
            TSTOCKADJUST = new HashSet<TSTOCKADJUST>();
            TSTOCKMOVEMENT = new HashSet<TSTOCKMOVEMENT>();
        }

        public string CODE { get; set; }
        public string LOCID { get; set; }
        public string NAME { get; set; }
        public bool ACTIVE { get; set; }
        public bool? CSPO { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MORGANIZATION LOC { get; set; }
        public virtual ICollection<TGI> TGI { get; set; }
        public virtual ICollection<TGM> TGMDESTCODENavigation { get; set; }
        public virtual ICollection<TGM> TGMSRCCODENavigation { get; set; }
        public virtual ICollection<TGR> TGR { get; set; }
        public virtual ICollection<TSTOCK> TSTOCK { get; set; }
        public virtual ICollection<TSTOCKADJUST> TSTOCKADJUST { get; set; }
        public virtual ICollection<TSTOCKMOVEMENT> TSTOCKMOVEMENT { get; set; }
    }
}