// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MTPH
    {
        public string TPHID { get; set; }
        public string UNITID { get; set; }
        public string DIVID { get; set; }
        public string BLOCKID { get; set; }
        public string CODE { get; set; }
        public bool ISRSPO { get; set; }
        public string LAT { get; set; }
        public string LONG { get; set; }
        public bool ACTIVE { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MORGANIZATION BLOCK { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual MUNIT UNIT { get; set; }
    }
}