// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MUNITDBSERVER
    {
        public string UNITCODE { get; set; }
        public string ALIAS { get; set; }
        public string SERVERNAME { get; set; }
        public string DBNAME { get; set; }
        public string DBUSER { get; set; }
        public string DBPASSWORD { get; set; }
    }
}