// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MUPKEEPTYPE
    {
        public MUPKEEPTYPE()
        {
            TUPKEEP = new HashSet<TUPKEEP>();
        }

        public short CODE { get; set; }
        public string NAME { get; set; }

        public virtual ICollection<TUPKEEP> TUPKEEP { get; set; }
    }
}