// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MUSERMASTER
    {
        public string USERID { get; set; }
        public string USERPASS { get; set; }
        public string USERNAME { get; set; }
        public DateTime EXPIRED { get; set; }
        public string ROLEID { get; set; }
        public string LOCID { get; set; }
        public short INVALID { get; set; }
        public bool LOCKED { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MROLEUSER ROLE { get; set; }
    }
}