// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MVEHICLETYPE
    {
        public MVEHICLETYPE()
        {
            MPREMIOPERATOR = new HashSet<MPREMIOPERATOR>();
        }

        public string ID { get; set; }
        public string NAME { get; set; }
        public string HMKM { get; set; }
        public bool DHS { get; set; }
        public bool? ACTIVE { get; set; }

        public virtual ICollection<MPREMIOPERATOR> MPREMIOPERATOR { get; set; }
    }
}