// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class MVEHICLE
    {
        public MVEHICLE()
        {
            TEQUIPTIMESHEET = new HashSet<TEQUIPTIMESHEET>();
        }

        public string ID { get; set; }
        public string UNITID { get; set; }
        public string TYPEID { get; set; }
        public string CODE { get; set; }
        public string NO { get; set; }
        public string NAME { get; set; }
        public string DRIVERID { get; set; }
        public string HELPERID { get; set; }
        public string DRIVER { get; set; }
        public string SIM { get; set; }
        public short ROT { get; set; }
        public bool ACTIVE { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MEMPLOYEE DRIVERNavigation { get; set; }
        public virtual MEMPLOYEE HELPER { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
        public virtual ICollection<TEQUIPTIMESHEET> TEQUIPTIMESHEET { get; set; }
    }
}