// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class REMPATT
    {
        public string ID { get; set; }
        public string UNITID { get; set; }
        public short MONTH { get; set; }
        public short YEAR { get; set; }
        public decimal HK { get; set; }
        public decimal UPSKUBQTY { get; set; }
        public decimal UPSKUBHK { get; set; }
        public decimal UPSKUHQTY { get; set; }
        public decimal UPSKUHHK { get; set; }
        public decimal UPBHLQTY { get; set; }
        public decimal UPBHLHK { get; set; }
        public decimal HVTSKUBQTY { get; set; }
        public decimal HVTSKUBHK { get; set; }
        public decimal HVTSKUHQTY { get; set; }
        public decimal HVTSKUHHK { get; set; }
        public decimal HVTBHLQTY { get; set; }
        public decimal HVTBHLHK { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MUNIT UNIT { get; set; }
    }
}