// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class RLABOURITM
    {
        public string ID { get; set; }
        public string LABID { get; set; }
        public short POSID { get; set; }
        public short STAFF0B { get; set; }
        public short STAFF1B { get; set; }
        public short SKUB0B { get; set; }
        public short SKUB1B { get; set; }
        public short SKUH0B { get; set; }
        public short SKUH1B { get; set; }
        public short BHL0B { get; set; }
        public short BHL1B { get; set; }
        public short STAFF0R { get; set; }
        public short STAFF1R { get; set; }
        public short SKUB0R { get; set; }
        public short SKUB1R { get; set; }
        public short SKUH0R { get; set; }
        public short SKUH1R { get; set; }
        public short BHL0R { get; set; }
        public short BHL1R { get; set; }
        public short STAFF0A { get; set; }
        public short STAFF1A { get; set; }
        public short SKUB0A { get; set; }
        public short SKUB1A { get; set; }
        public short SKUH0A { get; set; }
        public short SKUH1A { get; set; }
        public short BHL0A { get; set; }
        public short BHL1A { get; set; }
        public short STAFF0S { get; set; }
        public short STAFF1S { get; set; }
        public short SKUB0S { get; set; }
        public short SKUB1S { get; set; }
        public short SKUH0S { get; set; }
        public short SKUH1S { get; set; }
        public short BHL0S { get; set; }
        public short BHL1S { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }

        public virtual RLABOUR LAB { get; set; }
        public virtual RPOS POS { get; set; }
    }
}