// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class RLABOUR
    {
        public RLABOUR()
        {
            RLABOURITM = new HashSet<RLABOURITM>();
        }

        public string ID { get; set; }
        public string UNITID { get; set; }
        public DateTime DATE { get; set; }
        public decimal MATAREA { get; set; }
        public decimal IMATAREA { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<RLABOURITM> RLABOURITM { get; set; }
    }
}