// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class RPOS
    {
        public RPOS()
        {
            RLABOURITM = new HashSet<RLABOURITM>();
        }

        public short ID { get; set; }
        public short GROUPID { get; set; }
        public string NAME { get; set; }

        public virtual RPOSGROUP GROUP { get; set; }
        public virtual ICollection<RLABOURITM> RLABOURITM { get; set; }
    }
}