// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class RPOSGROUP
    {
        public RPOSGROUP()
        {
            RPOS = new HashSet<RPOS>();
        }

        public short ID { get; set; }
        public string NAME { get; set; }

        public virtual ICollection<RPOS> RPOS { get; set; }
    }
}