// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class SAPPAYROLLCOSTCTR
    {
        public string DIVID { get; set; }
        public string POSID { get; set; }
        public string COSTCTR { get; set; }
    }
}