// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class SAPPOSTINGHEADER
    {
        public SAPPOSTINGHEADER()
        {
            SAPPOSTING = new HashSet<SAPPOSTING>();
        }

        //public int ID { get; set; }
        public string PMS_DOC_NO { get; set; }
        public string TYPE { get; set; }
        public string POSTING { get; set; }
        //public string SAP_DOC_NO { get; set; }
        public DateTime? TRANS_DATE { get; set; }
        public string CANCEL { get; set; }
        //public string SAP_DOC_NO_CANCEL { get; set; }
        public DateTime? CANCEL_DATE { get; set; }

        public virtual ICollection<SAPPOSTING> SAPPOSTING { get; set; }
    }
}