// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class SAPPAYROLLACCOUNT
    {
        public string NAME { get; set; }
        public string PK1 { get; set; }
        public string ACC1 { get; set; }
        public string PK2 { get; set; }
        public string Acc2 { get; set; }
    }
}