// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class SAPPOSTING
    {
        public int ID { get; set; }
        public string PMS_DOC_NO { get; set; }
        public string ITEMID { get; set; }
        public string DOCTYPE { get; set; }
        public string POSTING { get; set; }
        public string SAP_DOC_NO { get; set; }
        public DateTime? TRANS_DATE { get; set; }
        public string CANCEL { get; set; }
        public string SAP_DOC_NO_CANCEL { get; set; }
        public DateTime? CANCEL_DATE { get; set; }
        public string PLANT { get; set; }
        public string BLOCK { get; set; }
        public string DIV { get; set; }
        public decimal? AREA { get; set; }
        public string SPLANT { get; set; }
        public string RPLANT { get; set; }
        public string ACT { get; set; }
        public string MATID { get; set; }
        public decimal? QTY { get; set; }
        public string BATCH { get; set; }
        public string CE { get; set; }
        public string EMPTYPE { get; set; }
        public string BOR { get; set; }
        public string CURR { get; set; }
        public string SEQ { get; set; }
        public short? YEAR { get; set; }
        public DateTime? TIME { get; set; }
        public string VEH { get; set; }
        public string DRIVER { get; set; }
        public decimal? TBS { get; set; }
        public decimal? JJG { get; set; }
        public decimal? JJGKG { get; set; }
        public decimal? BRD { get; set; }
        public string NOKRTTB { get; set; }
        public string ORDER_ { get; set; }
        public string EQUIP { get; set; }
        public string EQUIPLOC { get; set; }
        public string WORKLOC { get; set; }
        public string ORDER1 { get; set; }
        public string OPRID { get; set; }
        public string COSTCTR { get; set; }
        public string WBS { get; set; }
        public string ORDER2 { get; set; }
        public string ACT2 { get; set; }
        public DateTime? TIMESTART { get; set; }
        public DateTime? TIMEEND { get; set; }
        public decimal? KMSTART { get; set; }
        public decimal? KMEND { get; set; }
        public decimal? VOL { get; set; }
        public string UOM { get; set; }
        public string NOTE { get; set; }
        public string STATE { get; set; }
        public string MSG_ERROR { get; set; }

        public virtual SAPPOSTINGHEADER SAPHEADER { get; set; }
    }
}