// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class SAPUPKEEPRESULT
    {
        public string CODE { get; set; }
        public DateTime DATETIME { get; set; }
        public string NOTE { get; set; }
    }
}