// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class SAPUNIT
    {
        public string UNITCODE { get; set; }
        public bool ACTIVE { get; set; }
        public string MAIL { get; set; }
    }
}