// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class SPBKG
    {
        public string SPBID { get; set; }
        public string SOURCE { get; set; }
        public DateTime DATEIN { get; set; }
        public decimal WEIGHT1 { get; set; }
        public decimal WEIGHT2 { get; set; }
        public decimal NETTO { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }
    }
}