// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class SYNCTABLELIST
    {
        public string NAME { get; set; }
        public string QUERY { get; set; }
        public string UPDATED { get; set; }
        public string PKEYS { get; set; }
        public bool DIRECT { get; set; }
        public int ORDERNO { get; set; }
        public bool STATUS { get; set; }
    }
}