// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class SYNCDOWNLOAD
    {
        public string SOURCE { get; set; }
        public DateTime STARTDATE { get; set; }
        public string UNITID { get; set; }
        public bool DIRECT { get; set; }
    }
}