// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TACCOUNTHISTORY
    {
        public string CODE { get; set; }
        public short SEQ { get; set; }
        public string NO { get; set; }
        public string TYPE { get; set; }
        public DateTime DATE { get; set; }
        public string UNITCODE { get; set; }
        public string STATUS { get; set; }
        public string ACCOUNTCODE { get; set; }
        public string NOTE { get; set; }
        public decimal AMOUNT { get; set; }
        public string BLOCKID { get; set; }

        public virtual MACCOUNT ACCOUNTCODENavigation { get; set; }
        public virtual MORGANIZATION BLOCK { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual MJOURNALTYPE TYPENavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}