// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TACTIVITYMATERIALMAP
    {
        public string ACTIVITYID { get; set; }
        public string MATERIALID { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACTIVITY ACTIVITY { get; set; }
        public virtual MMATERIAL MATERIAL { get; set; }
    }
}