// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.EFCore.Model
{
    public partial class TATTENDANCE
    {
        public string ID { get; set; }
        public string DIVID { get; set; }
        public string EMPLOYEEID { get; set; }
        public DateTime DATE { get; set; }
        public bool PRESENT { get; set; }
        public string REMARK { get; set; }
        public decimal HK { get; set; }
        public string ABSENTCODE { get; set; }
        public string STATUS { get; set; }
        public string REF { get; set; }
        public bool AUTO { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATEDDATE { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATEDDATE { get; set; }

        public virtual MABSENTTYPE ABSENTCODENavigation { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE EMPLOYEE { get; set; }

        //custom
        [NotMapped]
        public string S_PRESENT
        {
            get { return PRESENT.ToString(); }
            set { PRESENT = Convert.ToBoolean(value); }
        }
    }
}