// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.EFCore.Model
{
    public partial class TATTENDANCETRX
    {
        [NotMapped]
        public string ID { get { return $"{UNITID}_{EMPID}_{DATE.Date.ToString("yyyyMMdd")}"; } }

        public string UNITID { get; set; }
        public string PIN { get; set; }
        public string EMPID { get; set; }
        public DateTime DATE { get; set; }
        public DateTime? CHECKIN { get; set; }
        public DateTime? CHECKOUT { get; set; }
        public string INSTATUS { get; set; }
        public string OUTSTATUS { get; set; }
        public string CARDIN { get; set; }
        public string CARDOUT { get; set; }
        public DateTime INSTART { get; set; }
        public DateTime INEND { get; set; }
        public DateTime OUTSTART { get; set; }
        public DateTime OUTEND { get; set; }
        public DateTime BREAKSTART { get; set; }
        public DateTime BREAKEND { get; set; }
        public DateTime INTIME { get; set; }
        public DateTime OUTTIME { get; set; }
        public short WORKLIMIT { get; set; }
        public bool CARDVALID { get; set; }
        public short CARDQUOTA { get; set; }
        public DateTime WORKACTUAL { get; set; }
        public decimal HKPAID { get; set; }
        public decimal OVERTIME { get; set; }
        public decimal OT150 { get; set; }
        public decimal OT200 { get; set; }
        public decimal OT300 { get; set; }
        public decimal OT400 { get; set; }
        public bool HOLIDAY { get; set; }
        public decimal SPL { get; set; }
        public string ATTSTATUS { get; set; }
        public bool AUTO { get; set; }
        public string STATUS { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MEMPLOYEE EMPLOYEE { get; set; }
    }
}