// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TATTENDANCEPROBLEM
    {
        public TATTENDANCEPROBLEM()
        {
            TATTENDANCEPROBLEMEMPLOYEE = new HashSet<TATTENDANCEPROBLEMEMPLOYEE>();
        }

        public string ID { get; set; }
        public DateTime DATE { get; set; }
        public string UNITCODE { get; set; }
        public string NOTES { get; set; }
        public long? ATTACHMENTFILEID { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCSTATUS { get; set; }
        public string WFDOCSTATUSTEXT { get; set; }
        public string STATUS { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MUNIT UNITCODENavigation { get; set; }
        public virtual ICollection<TATTENDANCEPROBLEMEMPLOYEE> TATTENDANCEPROBLEMEMPLOYEE { get; set; }
    }
}