// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TATTENDANCESPL
    {
        public string ID { get; set; }
        public string UNITID { get; set; }
        public string NO { get; set; }
        public DateTime DATE { get; set; }
        public string EMPID { get; set; }
        public decimal OVERTIME { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MEMPLOYEE EMP { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
    }
}