// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TATTENDANCELOG
    {
        public string EMPID { get; set; }
        public int PIN { get; set; }
        public DateTime DATETIME { get; set; }
        public short VERIFY { get; set; }
        public short INOUTMODE { get; set; }
        public short WORKCODE { get; set; }
        public string DEVICE { get; set; }
        public DateTime UPDATED { get; set; }

        //Custom
        public virtual MEMPLOYEE EMPLOYEE { get; set; }
    }

}