// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TATTENDANCEPROBLEMEMPLOYEE
    {
        public string ID { get; set; }
        public int LINENO { get; set; }
        public string EMPID { get; set; }
        public string REASONID { get; set; }
        public string REASONTEXT { get; set; }
        public bool FAILEDFINGER { get; set; }
        public DateTime? TIME { get; set; }
        public string NOTES { get; set; }
        public long? ATTACHMENTFILE1 { get; set; }
        public long? ATTACHMENTFILE2 { get; set; }
        public long? ATTACHMENTFILE3 { get; set; }
        public bool? APPROVED { get; set; }
        public string REJECTIONREASON { get; set; }
        public string REJECTEDBY { get; set; }
        public DateTime? REJECTEDDATE { get; set; }

        public virtual MEMPLOYEE EMP { get; set; }
        public virtual TATTENDANCEPROBLEM IDNavigation { get; set; }
    }
}