// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TBUDGETPROD
    {
        public string ID { get; set; }
        public string DIVID { get; set; }
        public DateTime DATE { get; set; }
        public decimal QTY { get; set; }
        public string STATUS { get; set; }
    }
}