// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.EFCore.Model
{
    public partial class TCALENDAR
    {
        [NotMapped]
        public string ID { get { return $"{UNITCODE}_{DTDATE.Date.ToString("yyyyMMdd")}"; } }

        public string UNITCODE { get; set; }
        public DateTime DTDATE { get; set; }
        public bool HOLIDAY { get; set; }
        public bool SUNDAY { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MUNIT UNITCODENavigation { get; set; }

        [NotMapped]
        public string DAYTYPE
        {
            get
            {
                if (HOLIDAY)
                    return "HOLIDAY";
                else
                    return "SUNDAY";
            }
            set
            {
                if (value == "HOLIDAY")
                    HOLIDAY = true;
                SUNDAY = !HOLIDAY;
            }
        }
    }
}