// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TCLOSEYEAR
    {
        public string ID { get; set; }
        public string UNITCODE { get; set; }
        public short YEAR { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MORGANIZATION UNITCODENavigation { get; set; }
    }
}