// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TCOGS
    {
        public string CODE { get; set; }
        public string UNITCODE { get; set; }
        public string MATERIALID { get; set; }
        public DateTime DATE { get; set; }
        public decimal PRICE { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MMATERIAL MATERIAL { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}