// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TCONTRACTITEM
    {
        public string CONTID { get; set; }
        public string ACTID { get; set; }
        public decimal OUTPUT { get; set; }
        public decimal USED { get; set; }
        public decimal PRICE { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual TCONTRACT CONT { get; set; }
    }
}