// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TCONTRACT
    {
        public TCONTRACT()
        {
            TCONTRACTITEM = new HashSet<TCONTRACTITEM>();
        }

        public string ID { get; set; }
        public string UNITID { get; set; }
        public DateTime DATE { get; set; }
        public string CARDID { get; set; }
        public DateTime STARTDATE { get; set; }
        public DateTime ENDDATE { get; set; }
        public string NOTE { get; set; }
        public bool CLOSE { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MCARD CARD { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
        public virtual ICollection<TCONTRACTITEM> TCONTRACTITEM { get; set; }
    }
}