// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TEMPLOYEECHANGE
    {
        public string ID { get; set; }
        public string EMPID { get; set; }

        public DateTime EFFECTIVEDATE { get; set; }
        public string UNITCODE { get; set; }
        public string DIVID { get; set; }
        public string POSITIONID { get; set; }
        public string EMPTYPE { get; set; }
        public string RECORDSTATUS { get; set; }
        public string STATUSID { get; set; }
        public decimal BASICWAGES { get; set; }
        public string NEWUNITCODE { get; set; }
        public string NEWDIVID { get; set; }
        public string NEWPOSITIONID { get; set; }
        public string NEWEMPTYPE { get; set; }
        public string NEWSTATUSID { get; set; }
        public string NEWRECORDSTATUS { get; set; }
        public decimal? NEWBASICWAGES { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCSTATUS { get; set; }
        public string WFDOCSTATUSTEXT { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEETYPE EMPTYPENavigation { get; set; }
        public virtual MDIVISI NEWDIV { get; set; }
        public virtual MEMPLOYEETYPE NEWEMPTYPENavigation { get; set; }
        public virtual MPOSITION NEWPOSITION { get; set; }
        public virtual MSTATUS NEWSTATUS { get; set; }
        public virtual MUNIT NEWUNITCODENavigation { get; set; }
        public virtual MPOSITION POSITION { get; set; }
        public virtual MSTATUS STATUS { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}