// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TEMPLOYEEREGISTRATION
    {
        public TEMPLOYEEREGISTRATION()
        {
            TEMPLOYEEREGISTRATIONFAMILY = new HashSet<TEMPLOYEEREGISTRATIONFAMILY>();
            TEMPLOYEEREGISTRATIONFILE = new HashSet<TEMPLOYEEREGISTRATIONFILE>();
        }

        public string REGISTRATIONID { get; set; }
        public string UNITCODE { get; set; }
        public string EMPNAME { get; set; }
        public string DIVID { get; set; }
        public string POSITIONID { get; set; }
        public string EMPTYPE { get; set; }
        public string STATUSID { get; set; }
        public decimal BASICWAGES { get; set; }
        public DateTime BIRTHDAY { get; set; }
        public DateTime JOINTDATE { get; set; }
        public string PLACEOFBIRTH { get; set; }
        public string EMPSEX { get; set; }
        public string RACE { get; set; }
        public string RELIGION { get; set; }
        public string EDUCATION { get; set; }
        public string KTPID { get; set; }
        public string KTPADDRESS { get; set; }
        public string NPWP { get; set; }
        public bool NATURA { get; set; }
        public string BANKID { get; set; }
        public string BANKACCNO { get; set; }
        public string BANKACCNAME { get; set; }
        public bool BPJSKES { get; set; }
        public bool BPJSJKK { get; set; }
        public bool BPJSJHT { get; set; }
        public bool BPJSJP { get; set; }
        public string BPJSKESEHATANNO { get; set; }
        public string BPJSKESEHATANET { get; set; }
        public string BPJSKETENAGAKERJAANNO { get; set; }
        public string BPJSKETENAGAKERJAANNPP { get; set; }
        public decimal BPJSBASE { get; set; }
        public decimal BPJSKESEHATANBASE { get; set; }
        public string EMPID { get; set; }
        public int PINID { get; set; }
        public bool PKWT { get; set; }
        public string NOSPK { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCSTATUS { get; set; }
        public string WFDOCSTATUSTEXT { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE EMP { get; set; }
        public virtual MEMPLOYEETYPE EMPTYPENavigation { get; set; }
        public virtual MPOSITION POSITION { get; set; }
        public virtual MSTATUS STATUS { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
        public virtual ICollection<TEMPLOYEEREGISTRATIONFAMILY> TEMPLOYEEREGISTRATIONFAMILY { get; set; }
        public virtual ICollection<TEMPLOYEEREGISTRATIONFILE> TEMPLOYEEREGISTRATIONFILE { get; set; }
    }
}