// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TEQUIPTIMESHEETACTIVITY
    {
        public string ID { get; set; }
        public string EQUIPTIMESHEETID { get; set; }
        public string ACTID { get; set; }
        public string OPRID { get; set; }
        public string HELPERID { get; set; }
        public decimal VOL { get; set; }
        public string BLOCKFROMID { get; set; }
        public string BLOCKTOID { get; set; }
        public string RECID { get; set; }
        public string NOTE { get; set; }
        public DateTime TIMESTART { get; set; }
        public DateTime TIMEEND { get; set; }
        public decimal KMSTART { get; set; }
        public decimal KMEND { get; set; }
        public bool ORDER { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual MORGANIZATION BLOCKFROM { get; set; }
        public virtual MORGANIZATION BLOCKTO { get; set; }
        public virtual TEQUIPTIMESHEET EQUIPTIMESHEET { get; set; }
        public virtual MEMPLOYEE HELPER { get; set; }
        public virtual MEMPLOYEE OPR { get; set; }
        public virtual MORGANIZATION REC { get; set; }
    }
}