// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TEQUIPTIMESHEETMATERIAL
    {
        public string ID { get; set; }
        public string EQUIPTIMESHEETID { get; set; }
        public string MATID { get; set; }
        public decimal QTY { get; set; }

        public virtual TEQUIPTIMESHEET EQUIPTIMESHEET { get; set; }
        public virtual MMATERIAL MAT { get; set; }
    }
}