// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TEQUIPTIMESHEETEMPLOYEE
    {
        public string ID { get; set; }
        public string EQUIPTIMESHEETID { get; set; }
        public string EMPID { get; set; }
        public decimal VALUE { get; set; }

        public virtual MEMPLOYEE EMP { get; set; }
        public virtual TEQUIPTIMESHEET EQUIPTIMESHEET { get; set; }
    }
}