// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TEQUIPTIMESHEET
    {
        public TEQUIPTIMESHEET()
        {
            TEQUIPTIMESHEETACTIVITY = new HashSet<TEQUIPTIMESHEETACTIVITY>();
            TEQUIPTIMESHEETEMPLOYEE = new HashSet<TEQUIPTIMESHEETEMPLOYEE>();
            TEQUIPTIMESHEETMATERIAL = new HashSet<TEQUIPTIMESHEETMATERIAL>();

            VBKUEMPLOYEEREF = new HashSet<VBKUEMPLOYEE>();
            VBKUACTIVITYREF = new HashSet<VBKUACTIVITY>();
            VBKUMATERIALREF = new HashSet<VBKUMATERIAL>();

        }

        public string ID { get; set; }
        public string UNITID { get; set; }
        public string DIVID { get; set; }
        public DateTime DATE { get; set; }
        public string EQUIPID { get; set; }
        public short ROT { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MORGANIZATION DIV { get; set; }
        public virtual MVEHICLE EQUIP { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETACTIVITY> TEQUIPTIMESHEETACTIVITY { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETEMPLOYEE> TEQUIPTIMESHEETEMPLOYEE { get; set; }
        public virtual ICollection<TEQUIPTIMESHEETMATERIAL> TEQUIPTIMESHEETMATERIAL { get; set; }

            //Custom

        public virtual ICollection<VBKUEMPLOYEE> VBKUEMPLOYEEREF { get; set; }
        public virtual ICollection<VBKUACTIVITY> VBKUACTIVITYREF { get; set; }
        public virtual ICollection<VBKUMATERIAL> VBKUMATERIALREF { get; set; }

    }
}