// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TGIITEM
    {
        public string CODE { get; set; }
        public string NO { get; set; }
        public short SEQ { get; set; }
        public string MATERIALID { get; set; }
        public string ACCOUNTCODE { get; set; }
        public decimal STOCK { get; set; }
        public decimal QTY { get; set; }
        public decimal PRICE { get; set; }
        public string NOTE { get; set; }
        public string BLOCKID { get; set; }

        public virtual MACCOUNT ACCOUNTCODENavigation { get; set; }
        public virtual MBLOCK BLOCK { get; set; }
        public virtual MMATERIAL MATERIAL { get; set; }
        public virtual TGI NONavigation { get; set; }
    }
}