// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TGM
    {
        public string NO { get; set; }
        public DateTime DATE { get; set; }
        public string UNITCODE { get; set; }
        public string SRCCODE { get; set; }
        public string DESTCODE { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MSTORELOCATION DESTCODENavigation { get; set; }
        public virtual MSTORELOCATION SRCCODENavigation { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}