// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TGR
    {
        public TGR()
        {
            TGRITEM = new HashSet<TGRITEM>();
        }

        public string NO { get; set; }
        public string VOUCHERNO { get; set; }
        public DateTime DATE { get; set; }
        public string UNITCODE { get; set; }
        public string LOCCODE { get; set; }
        public string VENDORCODE { get; set; }
        public string EXPCODE { get; set; }
        public decimal EXPVALUE { get; set; }
        public string REVCODE { get; set; }
        public string NOTE { get; set; }
        public string REF { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MCARD EXPCODENavigation { get; set; }
        public virtual MSTORELOCATION LOCCODENavigation { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
        public virtual MCARD VENDORCODENavigation { get; set; }
        public virtual ICollection<TGRITEM> TGRITEM { get; set; }
    }
}