// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTBLOCKRESULT
    {
        public string ID { get; set; }
        public string SOURCE { get; set; }
        public string NOSPB { get; set; }
        public DateTime DATE { get; set; }
        public string VEHID { get; set; }
        public string DRIVER { get; set; }
        public string BLOCKID { get; set; }
        public short ROT { get; set; }
        public decimal NETTO { get; set; }
        public decimal BJR { get; set; }
        public decimal JJG { get; set; }
        public decimal BRD { get; set; }
        public decimal QTY { get; set; }
        public decimal PAG { get; set; }
        public bool AUTO { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MORGANIZATION BLOCK { get; set; }

        //custom 
        public virtual MBLOCK BLOCKDETAIL { get; set; }

    }
}