// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTBLOCKQLY
    {
        public string ID { get; set; }
        public string NOSPB { get; set; }
        public string DIVID { get; set; }
        public DateTime DATE { get; set; }
        public short QLYCATID { get; set; }
        public decimal VALUE { get; set; }
        public bool AUTO { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }
    }
}