// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTPLAN
    {
        public THARVESTPLAN()
        {
            THARVESTPLANBLOCK = new HashSet<THARVESTPLANBLOCK>();
            THARVESTPLANEMPLOYEE = new HashSet<THARVESTPLANEMPLOYEE>();
        }

        public string HARVESTPLANCODE { get; set; }
        public string DIVID { get; set; }
        public DateTime HARVESTPLANDATE { get; set; }
        public short HARVESTPLANTYPE { get; set; }
        public string ACTIVITYID { get; set; }
        public string MANDORID { get; set; }
        public string KRANIID { get; set; }
        public string MANDOR1ID { get; set; }
        public string CHECKERID { get; set; }
        public string REMARK { get; set; }
        public string DOCID { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }
        public string CANCELEDCOMMENT { get; set; }

        public virtual MEMPLOYEE CHECKER { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual MHARVESTTYPE HARVESTPLANTYPENavigation { get; set; }
        public virtual MEMPLOYEE KRANI { get; set; }
        public virtual MEMPLOYEE MANDOR { get; set; }
        public virtual MEMPLOYEE MANDOR1 { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual ICollection<THARVESTPLANBLOCK> THARVESTPLANBLOCK { get; set; }
        public virtual ICollection<THARVESTPLANEMPLOYEE> THARVESTPLANEMPLOYEE { get; set; }
    }
}