// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTPLANEMPLOYEECALC
    {
        public string ID { get; set; }
        public string EMPID { get; set; }
        public DateTime DATE { get; set; }
        public string ACTID { get; set; }
        public decimal QTY { get; set; }
        public string RKHID { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATEDDATE { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual MEMPLOYEE EMP { get; set; }
    }
}