// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTRESULT
    {
        public DateTime STARTDATE { get; set; }
        public DateTime ENDDATE { get; set; }
        public string EMPLOYEEID { get; set; }
        public DateTime HARVESTDATE { get; set; }
        public string BLOCKID { get; set; }
        public string BASISGROUP { get; set; }
        public string DIVID { get; set; }
        public string MANDORID { get; set; }
        public string MANDOR1ID { get; set; }
        public string KRANIID { get; set; }
        public string CHECKERID { get; set; }
        public short HARVESTTYPE { get; set; }
        public short HARVESTPAYMENTTYPE { get; set; }
        public string EMPLOYEETYPE { get; set; }
        public string GEMPID { get; set; }
        public decimal ORIBASE1 { get; set; }
        public decimal BASE1 { get; set; }
        public decimal BASE2 { get; set; }
        public decimal BASE3 { get; set; }
        public decimal FRIDAY1 { get; set; }
        public decimal FRIDAY2 { get; set; }
        public decimal FRIDAY3 { get; set; }
        public decimal PREMI1 { get; set; }
        public decimal PREMI2 { get; set; }
        public decimal PREMI3 { get; set; }
        public decimal EXCEED1 { get; set; }
        public decimal EXCEED2 { get; set; }
        public decimal EXCEED3 { get; set; }
        public decimal FINEQTY { get; set; }
        public decimal FINEAMOUNT { get; set; }
        public decimal QTYJJG { get; set; }
        public decimal QTYKG { get; set; }
        public decimal HASILPANEN { get; set; }
        public decimal TOTALPANEN { get; set; }
        public decimal PCTORIBASIS1 { get; set; }
        public decimal PCTBASIS1 { get; set; }
        public decimal PCTBASIS2 { get; set; }
        public decimal PCTBASIS3 { get; set; }
        public decimal TOTALPCTORIBASIS1 { get; set; }
        public decimal TOTALPCTBASIS1 { get; set; }
        public decimal TOTALPCTBASIS2 { get; set; }
        public decimal TOTALPCTBASIS3 { get; set; }
        public decimal NEWORIBASISPCT1 { get; set; }
        public decimal NEWBASISPCT1 { get; set; }
        public decimal NEWORIBASIS1 { get; set; }
        public decimal NEWBASIS1 { get; set; }
        public decimal NEWPREMISIAP1 { get; set; }
        public decimal NEWBASISPCT2 { get; set; }
        public decimal NEWBASIS2 { get; set; }
        public decimal NEWPREMISIAP2 { get; set; }
        public decimal NEWBASISPCT3 { get; set; }
        public decimal NEWBASIS3 { get; set; }
        public decimal NEWPREMISIAP3 { get; set; }
        public decimal NEWHASIL1 { get; set; }
        public decimal NEWPREMILEBIH1 { get; set; }
        public decimal NEWINCENTIVE1 { get; set; }
        public decimal NEWHASIL2 { get; set; }
        public decimal NEWPREMILEBIH2 { get; set; }
        public decimal NEWINCENTIVE2 { get; set; }
        public decimal NEWHASIL3 { get; set; }
        public decimal NEWPREMILEBIH3 { get; set; }
        public decimal NEWINCENTIVE3 { get; set; }
        public decimal PREMIPKKTGI { get; set; }
        public decimal INCENTIVEPKKTGI { get; set; }
        public decimal HAHASIL { get; set; }
        public decimal HABASE { get; set; }
        public decimal HAPREMI { get; set; }
        public decimal HAPCT { get; set; }
        public decimal NEWHAPCT { get; set; }
        public decimal NEWHABASE { get; set; }
        public decimal NEWHAPREMI { get; set; }
        public decimal HAINCENTIVE { get; set; }
        public decimal ATTPREMI { get; set; }
        public decimal NEWATTPREMI { get; set; }
        public decimal ATTINCENTIVE { get; set; }
        public decimal GERDANBASE { get; set; }
        public decimal MANDOR1INCENTIVE { get; set; }
        public decimal MANDORINCENTIVE { get; set; }
        public decimal KRANIINCENTIVE { get; set; }
        public decimal CHECKERINCENTIVE { get; set; }
        public string ACTIVITYID { get; set; }
        public string UNITCODE { get; set; }
        public string PAYMENTNO { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string POSITIONID { get; set; }
        public string FAMILYSTATUS { get; set; }
        public string TAXSTATUS { get; set; }
        public string STATUSID { get; set; }
        public short REMAININGLEAVE { get; set; }
        public short LEAVE { get; set; }
        public string GOLONGAN { get; set; }
        public string SUPERVISORID { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }

        public virtual MACTIVITY ACTIVITY { get; set; }
        public virtual MBLOCK BLOCK { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE EMPLOYEE { get; set; }
        public virtual MEMPLOYEE KRANI { get; set; }
        public virtual MEMPLOYEE MANDOR { get; set; }
        public virtual MEMPLOYEE MANDOR1 { get; set; }
        public virtual TPAYMENT PAYMENTNONavigation { get; set; }
        public virtual MPOSITION POSITION { get; set; }
        public virtual MSTATUS STATUS { get; set; }
        public virtual MEMPLOYEE SUPERVISOR { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}