// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTWFMAXBRONDOLDETAIL
    {
        public string ID { get; set; }
        public string BLOCKID { get; set; }
        public decimal JJG { get; set; }
        public decimal BRONDOL { get; set; }
        public decimal CURRENTBRONDOL { get; set; }
        public decimal RATIO { get; set; }
        public bool? APPROVED { get; set; }
        public string REJECTEDBY { get; set; }
        public string REJECTIONREASON { get; set; }
        public DateTime? REJECTEDDATE { get; set; }

        public virtual MBLOCK BLOCK { get; set; }
        public virtual THARVESTWFMAXBRONDOL THARVESTWFMAXBRONDOL { get; set; }
    }
}