// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTWFDAYVALIDATION
    {
        public string ID { get; set; }
        public string HARVESTCODE { get; set; }
        public int WFSEQUENCE { get; set; }
        public int ALLOWEDDAYS { get; set; }
        public DateTime DATE { get; set; }
        public string UNITCODE { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCSTATUS { get; set; }
        public string WFDOCSTATUSTEXT { get; set; }
        public string WFERRORTEXT { get; set; }
        public string STATUS { get; set; }
        public bool? SYNCTOESTATE { get; set; }
        public DateTime? SYNCDATE { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime? CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime? UPDATED { get; set; }

        public virtual THARVEST THARVEST { get; set; }
        public virtual MUNIT MUNIT { get; set; }
    }
}