// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTPLANEMPLOYEE
    {
        public string HARVESTPLANCODE { get; set; }
        public string EMPLOYEEID { get; set; }

        public virtual MEMPLOYEE EMPLOYEE { get; set; }
        public virtual THARVESTPLAN HARVESTPLANCODENavigation { get; set; }
    }
}