// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTROT
    {
        public string UNITID { get; set; }
        public short ROT { get; set; }
        public decimal QTY { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MORGANIZATION UNIT { get; set; }
    }
}