// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTWFLEBIHBASISDETAIL
    {
        public string ID { get; set; }
        public string EMPID { get; set; }
        public decimal JJG { get; set; }
        public decimal KG { get; set; }
        public decimal BASE { get; set; }
        public bool? APPROVED { get; set; }
        public string REJECTEDBY { get; set; }
        public string REJECTIONREASON { get; set; }
        public DateTime? REJECTEDDATE { get; set; }

        public virtual MEMPLOYEE MEMPLOYEE { get; set; }
        public virtual THARVESTWFLEBIHBASIS THARVESTWFLEBIHBASIS { get; set; }
    }
}