// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTFINE
    {
        public string HARVESTCODE { get; set; }
        public string EMPLOYEEID { get; set; }
        public string BLOCKID { get; set; }
        public string FINECODE { get; set; }
        public decimal QTY { get; set; }
        public bool AUTO { get; set; }

        public virtual MBLOCK BLOCK { get; set; }
        public virtual MEMPLOYEE EMPLOYEE { get; set; }
        public virtual MPENALTYTYPE FINECODENavigation { get; set; }
        public virtual THARVEST HARVESTCODENavigation { get; set; }
    }
}