// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTASIS
    {
        public string HARVESTCODE { get; set; }
        public string UNITID { get; set; }

        public virtual THARVEST HARVESTCODENavigation { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
    }
}