// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTPLANBLOCK
    {
        public string HARVESTPLANCODE { get; set; }
        public string BLOCKID { get; set; }

        public virtual MBLOCK BLOCK { get; set; }
        public virtual THARVESTPLAN HARVESTPLANCODENavigation { get; set; }
    }
}