// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTBASE
    {
        public string HARVESTCODE { get; set; }
        public string BLOCKID { get; set; }
        public string EMPID { get; set; }
        public decimal BASE1 { get; set; }

        public virtual MORGANIZATION BLOCK { get; set; }
        public virtual MEMPLOYEE EMP { get; set; }
        public virtual THARVEST HARVESTCODENavigation { get; set; }
    }
}