// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVEST
    {
        public THARVEST()
        {
            THARVESTASIS = new HashSet<THARVESTASIS>();
            THARVESTBASE = new HashSet<THARVESTBASE>();
            THARVESTBLOCK = new HashSet<THARVESTBLOCK>();
            THARVESTCOLLECT = new HashSet<THARVESTCOLLECT>();
            THARVESTEMPLOYEE = new HashSet<THARVESTEMPLOYEE>();
            THARVESTFINE = new HashSet<THARVESTFINE>();
            THARVESTWFLEBIHBASIS = new HashSet<THARVESTWFLEBIHBASIS>();
            THARVESTWFMAXBRONDOL = new HashSet<THARVESTWFMAXBRONDOL>();
            THARVESTWFDAYVALIDATION = new HashSet<THARVESTWFDAYVALIDATION>();
        }

        public string HARVESTCODE { get; set; }
        public string DIVID { get; set; }
        public DateTime HARVESTDATE { get; set; }
        public short HARVESTTYPE { get; set; }
        public short? HARVESTPAYMENTTYPE { get; set; }
        public string ACTIVITYID { get; set; }
        public string MANDORID { get; set; }
        public short MANDORPEN { get; set; }
        public string KRANIID { get; set; }
        public short KRANIPEN { get; set; }
        public string MANDOR1ID { get; set; }
        public short MANDOR1PEN { get; set; }
        public string CHECKERID { get; set; }
        public string REMARK { get; set; }
        public string DOCID { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }
        public string CANCELEDCOMMENT { get; set; }
        public short UPLOAD { get; set; }
        public DateTime? UPLOADED { get; set; }

        public virtual MEMPLOYEE CHECKER { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual MHARVESTTYPE HARVESTTYPENavigation { get; set; }
        public virtual MEMPLOYEE KRANI { get; set; }
        public virtual MEMPLOYEE MANDOR { get; set; }
        public virtual MEMPLOYEE MANDOR1 { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual ICollection<THARVESTASIS> THARVESTASIS { get; set; }
        public virtual ICollection<THARVESTBASE> THARVESTBASE { get; set; }
        public virtual ICollection<THARVESTBLOCK> THARVESTBLOCK { get; set; }
        public virtual ICollection<THARVESTCOLLECT> THARVESTCOLLECT { get; set; }
        public virtual ICollection<THARVESTEMPLOYEE> THARVESTEMPLOYEE { get; set; }
        public virtual ICollection<THARVESTFINE> THARVESTFINE { get; set; }
        public virtual ICollection<THARVESTWFLEBIHBASIS> THARVESTWFLEBIHBASIS { get; set; }
        
        public virtual ICollection<THARVESTWFMAXBRONDOL> THARVESTWFMAXBRONDOL { get; set; }
        public virtual ICollection<THARVESTWFDAYVALIDATION> THARVESTWFDAYVALIDATION { get; set; }

        
    }
}