// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class THARVESTEMPLOYEE
    {
        public string HARVESTCODE { get; set; }
        public string EMPLOYEEID { get; set; }
        public string GEMPID { get; set; }
        public decimal VALUECALC { get; set; }
        public decimal VALUE { get; set; }
        public decimal GVALUECALC { get; set; }
        public decimal GVALUE { get; set; }
        public bool ALLOWQTY { get; set; }

        public virtual MEMPLOYEE EMPLOYEE { get; set; }
        public virtual MEMPLOYEE GEMP { get; set; }
        public virtual THARVEST HARVESTCODENavigation { get; set; }
    }
}