// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TICRAPP
    {
        public string ICRNO { get; set; }
        public string APPID { get; set; }

        public virtual MICRAPP APP { get; set; }
        public virtual TICR ICRNONavigation { get; set; }
    }
}