// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TICR
    {
        public TICR()
        {
            TICRAPP = new HashSet<TICRAPP>();
        }

        public string ICRNO { get; set; }
        public string TITLE { get; set; }
        public DateTime ICRDATE { get; set; }
        public string UNITID { get; set; }
        public string DEPTID { get; set; }
        public string DESCRIPTION { get; set; }
        public string REASON { get; set; }
        public int PRIORITYLEVEL { get; set; }
        public int IMPACTLEVEL { get; set; }
        public bool IMPACTTOSW { get; set; }
        public bool IMPACTTOHW { get; set; }
        public bool IMPACTTODB { get; set; }
        public bool IMPACTTONETW { get; set; }
        public bool IMPACTTOPROC { get; set; }
        public bool IMPACTTOSEC { get; set; }
        public bool IMPACTTOSCHED { get; set; }
        public bool IMPACTTOOS { get; set; }
        public string ACTIONTYPE { get; set; }
        public string ACTION { get; set; }
        public string RESOURCES { get; set; }
        public string TESTPLAN { get; set; }
        public string ROLLBACKPLAN { get; set; }
        public string TESTRESULT { get; set; }
        public DateTime? DEVSTARTPLAN { get; set; }
        public DateTime? DEVSTARTACTUAL { get; set; }
        public DateTime? DEVENDPLAN { get; set; }
        public DateTime? DEVENDACTUAL { get; set; }
        public DateTime? UATSTARTPLAN { get; set; }
        public DateTime? UATSTARTACTUAL { get; set; }
        public DateTime? UATENDPLAN { get; set; }
        public DateTime? UATENDACTUAL { get; set; }
        public DateTime? DEPLOYSTARTPLAN { get; set; }
        public DateTime? DEPLOYSTARTACTUAL { get; set; }
        public DateTime? DEPLOYENDPLAN { get; set; }
        public DateTime? DEPLOYENDACTUAL { get; set; }
        public DateTime? ACTIONSTARTPLAN { get; set; }
        public DateTime? ACTIONSTARTACTUAL { get; set; }
        public DateTime? ACTIONENDPLAN { get; set; }
        public DateTime? ACTIONENDACTUAL { get; set; }
        public DateTime? FINISHDATE { get; set; }
        public long? FILEATTACHMENT1 { get; set; }
        public long? FILEATTACHMENT2 { get; set; }
        public long? FILEATTACHMENT3 { get; set; }
        public long? FILESCENARIOTEST { get; set; }
        public long? FILEUAT { get; set; }
        public long? FILERELEASENOTE { get; set; }
        public long? FILEBADEPLOYMENT { get; set; }
        public long? FILEBAEXECUTION { get; set; }
        public string UATNO { get; set; }
        public string RN { get; set; }
        public string RNNO { get; set; }
        public DateTime? RNDATE { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCSTATUS { get; set; }
        public string WFDOCSTATUSTEXT { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MDEPARTMENT DEPT { get; set; }
        public virtual MUNIT UNIT { get; set; }
        public virtual ICollection<TICRAPP> TICRAPP { get; set; }
    }
}