// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TINCMANDORPERIOD
    {
        public string ID { get; set; }
        public string UNITID { get; set; }
        public short MONTH { get; set; }
        public short YEAR { get; set; }
        public short TYPEID { get; set; }
        public DateTime STARTDATE { get; set; }
        public DateTime ENDDATE { get; set; }
        public short EMPCOUNT { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal MINPROD { get; set; }
        public decimal MINMATANG { get; set; }
        public decimal MAXMENTAH { get; set; }
        public decimal MAXJANGKOS { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }
    }
}