// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TITEMAILREQUEST
    {
        public string REGISTERID { get; set; }
        public string UNITID { get; set; }
        public string DEPTID { get; set; }
        public DateTime REGISTERDATE { get; set; }
        public string REQUESTER { get; set; }
        public DateTime REQUESTDATE { get; set; }
        public long? REQUESTFILE { get; set; }
        public string NOTES { get; set; }
        public string EMAIL { get; set; }
        public DateTime? EXECUTIONDATE { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCSTATUS { get; set; }
        public string WFDOCSTATUSTEXT { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }
    }
}