// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



//namespace PMS.EFCore.Model
//{
//    public partial class TITINVOICEDETAIL
//    {
//        public string REGISTERID { get; set; }
//        public string INVOICENO { get; set; }
//        public DateTime INVOICEDATE { get; set; }
//        public long? INVOICEFILE { get; set; }
//        public string CURRENCYCODE { get; set; }
//        public decimal AMOUNT { get; set; }
//        public DateTime DUEDATE { get; set; }
//        public string NOTES { get; set; }
//        public bool APPROVED { get; set; }
//        public string REJECTEDBY { get; set; }
//        public string REJECTIONREASON { get; set; }
//        public DateTime? REJECTEDDATE { get; set; }

//        public virtual TITINVOICE REGISTER { get; set; }
//    }
//}