// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TITIOM
    {
        public string REGISTERID { get; set; }
        public string UNITID { get; set; }
        public string DEPTID { get; set; }
        public DateTime REGISTERDATE { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public long? FILEIOM { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCSTATUS { get; set; }
        public string WFDOCSTATUSTEXT { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }
    }
}