// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TITINVOICE
    {
        public TITINVOICE()
        {
            //TITINVOICEDETAIL = new HashSet<TITINVOICEDETAIL>();
        }

        public string REGISTERID { get; set; }
        public string UNITID { get; set; }
        public string DEPTID { get; set; }
        public string INVOICETYPE { get; set; }
        public DateTime REGISTERDATE { get; set; }
        public string VENDORID { get; set; }
        public string VENDORNAME { get; set; }
        public string INVOICENO { get; set; }
        public DateTime INVOICEDATE { get; set; }
        public long? INVOICEFILE { get; set; }
        public decimal AMOUNT { get; set; }
        public string CURRENCYCODE { get; set; }
        public DateTime DUEDATE { get; set; }
        public string NOTES { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCSTATUS { get; set; }
        public string WFDOCSTATUSTEXT { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }

        //public virtual ICollection<TITINVOICEDETAIL> TITINVOICEDETAIL { get; set; }
    }
}