// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TJOURNALITEM
    {
        public string CODE { get; set; }
        public short SEQ { get; set; }
        public string ACCOUNTCODE { get; set; }
        public string NOTE { get; set; }
        public decimal AMOUNT { get; set; }
        public string BLOCKID { get; set; }

        public virtual MACCOUNT ACCOUNTCODENavigation { get; set; }
        public virtual MORGANIZATION BLOCK { get; set; }
        public virtual TJOURNAL CODENavigation { get; set; }
    }
}