// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TJOURNAL
    {
        public TJOURNAL()
        {
            TJOURNALITEM = new HashSet<TJOURNALITEM>();
        }

        public string CODE { get; set; }
        public string NO { get; set; }
        public string TYPE { get; set; }
        public DateTime DATE { get; set; }
        public string UNITCODE { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public string REF { get; set; }
        public string CHEQUE { get; set; }
        public string PAYEE { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual MJOURNALTYPE TYPENavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
        public virtual ICollection<TJOURNALITEM> TJOURNALITEM { get; set; }
    }
}