// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TKARTUTIMBANG
    {
        public string SPBNO { get; set; }
        public DateTime CHECKDATE { get; set; }
        public short SRNO { get; set; }
        public decimal WEIGHT { get; set; }
        public string UOM { get; set; }
        public decimal ATTEMPNO { get; set; }

        public virtual TSPB SPBNONavigation { get; set; }
    }
}