// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TLOADINGBLOCKRESULT
    {
        public string ID { get; set; }
        public string SOURCE { get; set; }
        public DateTime DATE { get; set; }
        public string BLOCKID { get; set; }
        public short ROT { get; set; }
        public decimal QTY { get; set; }
        public decimal PAG { get; set; }
        public bool AUTO { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MORGANIZATION BLOCK { get; set; }
    }
}