// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TLOADING
    {
        public TLOADING()
        {
            TLOADINGASIS = new HashSet<TLOADINGASIS>();
            TLOADINGBASE = new HashSet<TLOADINGBASE>();
            TLOADINGBLOCK = new HashSet<TLOADINGBLOCK>();
            TLOADINGCOLLECT = new HashSet<TLOADINGCOLLECT>();
            TLOADINGDRIVER = new HashSet<TLOADINGDRIVER>();
            TLOADINGEMPLOYEE = new HashSet<TLOADINGEMPLOYEE>();

            VLOADINGBLOCKREF = new HashSet<VLOADINGBLOCK>();
            VLOADINGEMPLOYEEREF = new HashSet<VLOADINGEMPLOYEE>();
        }

        public string LOADINGCODE { get; set; }
        public string DIVID { get; set; }
        public DateTime LOADINGDATE { get; set; }
        public short PRODUCTID { get; set; }
        public short LOADINGTYPE { get; set; }
        public short SPBDATATYPE { get; set; }
        public string NOSPB { get; set; }
        public string VEHICLEID { get; set; }
        public string VEHICLETYPEID { get; set; }
        public short LOADINGPAYMENTTYPE { get; set; }
        public string ACTIVITYID { get; set; }
        public string KRANIID { get; set; }
        public short KRANIPEN { get; set; }
        public string DRIVERID { get; set; }
        public string ACTIVITYDRIVERID { get; set; }
        public string DESTINATIONID { get; set; }
        public string REMARK { get; set; }
        public string DOCID { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }
        public string CANCELEDCOMMENT { get; set; }
        public short UPLOAD { get; set; }
        public DateTime? UPLOADED { get; set; }

        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE KRANI { get; set; }
        public virtual MHARVESTTYPE LOADINGTYPENavigation { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual ICollection<TLOADINGASIS> TLOADINGASIS { get; set; }
        public virtual ICollection<TLOADINGBASE> TLOADINGBASE { get; set; }
        public virtual ICollection<TLOADINGBLOCK> TLOADINGBLOCK { get; set; }
        public virtual ICollection<TLOADINGCOLLECT> TLOADINGCOLLECT { get; set; }
        public virtual ICollection<TLOADINGDRIVER> TLOADINGDRIVER { get; set; }
        public virtual ICollection<TLOADINGEMPLOYEE> TLOADINGEMPLOYEE { get; set; }

        //custom
        public MACTIVITY MACTIVITY { get; set; }
        public virtual ICollection<VLOADINGBLOCK> VLOADINGBLOCKREF { get; set; }
        public virtual ICollection<VLOADINGEMPLOYEE> VLOADINGEMPLOYEEREF { get; set; }
    }
}