// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TLOANEMPTENOR

    {
        public string ID { get; set; }
        public DateTime TENORDATE { get; set; }
        public string UNITID { get; set; }
        public string EMPID { get; set; }
        public string TYPE { get; set; }
        public decimal AMOUNT { get; set; }
        public int TENOR { get; set; }
        public decimal INSTALLMENT { get; set; }
        public string REF { get; set; }
        public string PAYMENTNO { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public string CREATEDBY { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public DateTime UPDATED { get; set; }
    }
}