// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TLOADINGBLOCK
    {
        public string LOADINGCODE { get; set; }
        public string BLOCKID { get; set; }
        public string EMPLOYEEID { get; set; }
        public decimal VALUE { get; set; }
        public decimal QTY { get; set; }
        public decimal QTYKG { get; set; }
        public decimal KG { get; set; }

        public virtual MBLOCK BLOCK { get; set; }
        public virtual MEMPLOYEE EMPLOYEE { get; set; }
        public virtual TLOADING LOADINGCODENavigation { get; set; }
    }
}