// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TLOANEMP

    {
        public TLOANEMP()
        {
            TLOANEMPITEM = new HashSet<TLOANEMPITEM>();
        }

        public string TRANID { get; set; }
        public DateTime LOANDATE { get; set; }
        public string UNITID { get; set; }
        public string EMPID { get; set; }
        public string NOTE { get; set; }
        public int TENOR { get; set; }
        public decimal TOTAL { get; set; }
        public string STATUS { get; set; }
        public string CREATEDBY { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public DateTime UPDATED { get; set; }
   
        public virtual ICollection<TLOANEMPITEM> TLOANEMPITEM { get; set; }
        public virtual MEMPLOYEE MEMPLOYEE { get; set; }


    }
}