// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TLOADINGBASE
    {
        public string LOADINGCODE { get; set; }
        public string BLOCKID { get; set; }
        public string EMPID { get; set; }
        public decimal BASE1 { get; set; }

        public virtual MORGANIZATION BLOCK { get; set; }
        public virtual MEMPLOYEE EMP { get; set; }
        public virtual TLOADING LOADINGCODENavigation { get; set; }
    }
}