// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TLOADINGASIS
    {
        public string LOADINGCODE { get; set; }
        public string UNITID { get; set; }

        public virtual TLOADING LOADINGCODENavigation { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
    }
}