// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TLOADINGDRIVER
    {
        public string LOADINGCODE { get; set; }
        public string DRIVERID { get; set; }
        public decimal? VALUECALC { get; set; }
        public decimal? VALUE { get; set; }
        public bool ALLOWQTY { get; set; }

        public virtual MEMPLOYEE DRIVER { get; set; }
        public virtual TLOADING LOADINGCODENavigation { get; set; }
    }
}