// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TLOANEMPITEM
    {
        public string TRANID { get; set; }
        public string ID { get; set; }
        public short SEQ { get; set; }
        public string MATERIALID { get; set; }
        public string ACCOUNTCODE { get; set; }
        public decimal QTY { get; set; }
        public decimal PRICE { get; set; }
        public string BLOCKID { get; set; }
        public string DETAILNOTE { get; set; }
       
        public virtual TLOANEMP LOAN { get; set; }
        
    }
}