// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using PMS.Shared;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.EFCore.Model
{
    public partial class TMANDORFINE
    {
        public string ID { get; set; }
        public string UNITID { get; set; }
        public string EMPID { get; set; }
        public DateTime DATE { get; set; }

        
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        
        
    }
}