// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TOVERTIME
    {
        public string DOCNO { get; set; }
        public string DIVID { get; set; }
        public string EMPLOYEEID { get; set; }
        public DateTime DOCDATE { get; set; }
        public string REMARK { get; set; }
        public decimal OT150 { get; set; }
        public decimal OT200 { get; set; }
        public decimal OT300 { get; set; }
        public decimal OT400 { get; set; }
        public decimal POSBENEFIT { get; set; }
        public decimal OTHERWAGES { get; set; }
        public decimal DEBIT { get; set; }
        public decimal CREDIT { get; set; }
        public string ACTID { get; set; }
        public string LOCID { get; set; }
        public string EQUIPID { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE EMPLOYEE { get; set; }
        public virtual MORGANIZATION LOC { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
    }
}