// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPAYMENTDETAILTRX
    {
        public string DOCNO { get; set; }
        public string EMPID { get; set; }
        public string EMPCODE { get; set; }
        public DateTime DOCDATE { get; set; }
        public short? PERIOD { get; set; }
        public string UNITCODE { get; set; }
        public bool? AUTO { get; set; }
        public string STATUS { get; set; }
        public string TYPEMANUAL { get; set; }
        public string NOTES { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime? CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime? UPDATED { get; set; }
    }
}