// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPAYMENTTAX
    {
        public string DOCNO { get; set; }
        public string EMPID { get; set; }
        public decimal BASICWAGESBRUTO { get; set; }
        public decimal BASICWAGES { get; set; }
        public decimal JAMSOSTEKINC { get; set; }
        public decimal JAMSOSTEKDEDUCT { get; set; }
        public decimal PREMI { get; set; }
        public decimal OVERTIME { get; set; }
        public decimal NATURA { get; set; }
        public decimal TAXINCENTIVE { get; set; }
        public decimal GROSSINCOME { get; set; }
        public decimal POSITIONCOST { get; set; }
        public decimal NETINCOMEMONTH { get; set; }
        public decimal NETINCOMEYEAR { get; set; }
        public decimal INCENTIVE { get; set; }
        public decimal NONTAXABLE { get; set; }
        public decimal TAXABLE { get; set; }
        public decimal TAXYEAR { get; set; }
        public decimal TAXPAID { get; set; }
        public decimal TAXMONTH { get; set; }
    }
}