// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPAYMENTITEM
    {
        public string DOCNO { get; set; }
        public string TYPEID { get; set; }
        public string EMPID { get; set; }
        public decimal AMOUNT { get; set; }

        public virtual TPAYMENT DOCNONavigation { get; set; }
        public virtual MEMPLOYEE EMP { get; set; }
        public virtual MSALARYTYPE TYPE { get; set; }
    }
}