// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPAYMENT
    {
        public TPAYMENT()
        {
            THARVESTRESULT = new HashSet<THARVESTRESULT>();
            TPAYMENTATTR = new HashSet<TPAYMENTATTR>();
            TPAYMENTATTREMP = new HashSet<TPAYMENTATTREMP>();
            TPAYMENTDETAIL = new HashSet<TPAYMENTDETAIL>();
            TPAYMENTITEM = new HashSet<TPAYMENTITEM>();
            TPREMICHECKER = new HashSet<TPREMICHECKER>();
            TPREMIMANDOR = new HashSet<TPREMIMANDOR>();
            TPREMIMANDOR1 = new HashSet<TPREMIMANDOR1>();
            TSALARYITEM = new HashSet<TSALARYITEM>();
        }

        public string DOCNO { get; set; }
        public string UNITCODE { get; set; }
        public DateTime DOCDATE { get; set; }
        public short PERIOD { get; set; }
        public DateTime STARTDATE { get; set; }
        public DateTime ENDDATE { get; set; }
        public string MANAGER { get; set; }
        public string KTU { get; set; }
        public decimal TOTAL { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
        public virtual TPAYMENTSCHEME TPAYMENTSCHEME { get; set; }
        public virtual ICollection<THARVESTRESULT> THARVESTRESULT { get; set; }
        public virtual ICollection<TPAYMENTATTR> TPAYMENTATTR { get; set; }
        public virtual ICollection<TPAYMENTATTREMP> TPAYMENTATTREMP { get; set; }
        public virtual ICollection<TPAYMENTDETAIL> TPAYMENTDETAIL { get; set; }
        public virtual ICollection<TPAYMENTITEM> TPAYMENTITEM { get; set; }
        public virtual ICollection<TPREMICHECKER> TPREMICHECKER { get; set; }
        public virtual ICollection<TPREMIMANDOR> TPREMIMANDOR { get; set; }
        public virtual ICollection<TPREMIMANDOR1> TPREMIMANDOR1 { get; set; }
        public virtual ICollection<TSALARYITEM> TSALARYITEM { get; set; }
    }
}