// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPAYMENTATTR
    {
        public string DOCNO { get; set; }
        public string TYPEID { get; set; }
        public string TVALUE { get; set; }
        public decimal NVALUE { get; set; }

        public virtual TPAYMENT DOCNONavigation { get; set; }
    }
}