// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPAYMENTWFADJUSTHK
    {
        public TPAYMENTWFADJUSTHK()
        {
            TPAYMENTWFADJUSTHKDETAIL = new HashSet<TPAYMENTWFADJUSTHKDETAIL>();
        }

        public string ID { get; set; }
        public string PAYMENTDOCNO { get; set; }
        public int WFSEQUENCE { get; set; }
        public DateTime DATE { get; set; }
        public string UNITCODE { get; set; }
        public DateTime STARTDATE { get; set; }
        public DateTime ENDDATE { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCSTATUS { get; set; }
        public string WFDOCSTATUSTEXT { get; set; }
        public string WFERRORTEXT { get; set; }
        public string STATUS { get; set; }
        public bool? SYNCTOESTATE { get; set; }
        public DateTime? SYNCDATE { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime? CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime? UPDATED { get; set; }

        public virtual MUNIT UNITCODENavigation { get; set; }
        public virtual ICollection<TPAYMENTWFADJUSTHKDETAIL> TPAYMENTWFADJUSTHKDETAIL { get; set; }
    }
}