// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPAYMENTDETAIL
    {
        public string DOCNO { get; set; }
        public string EMPID { get; set; }
        public string EMPCODE { get; set; }
        public string COSTCENTER { get; set; }
        public decimal BASICWAGES { get; set; }
        public decimal BASICWAGESBRUTO { get; set; }
        public decimal PREMIPANEN { get; set; }
        public decimal PREMIPANENKONTAN { get; set; }
        public decimal PREMINONPANEN { get; set; }
        public decimal PREMIHADIR { get; set; }
        public decimal PENALTY { get; set; }
        public short DAYS { get; set; }
        public short HOLIDAY { get; set; }
        public short SUNDAY { get; set; }
        public short PRESENT { get; set; }
        public decimal HK { get; set; }
        public decimal HKC { get; set; }
        public decimal HKH1 { get; set; }
        public decimal HKH2 { get; set; }
        public decimal HKP1 { get; set; }
        public decimal HKP2 { get; set; }
        public decimal HKP3 { get; set; }
        public decimal HKP4 { get; set; }
        public decimal HKS1 { get; set; }
        public decimal HKS2 { get; set; }
        public decimal MANGKIR { get; set; }
        public decimal OVERTIMEHOUR { get; set; }
        public decimal OVERTIME { get; set; }
        public string RICEPAIDASMONEY { get; set; }
        public decimal NATURA { get; set; }
        public decimal NATURAINCOME { get; set; }
        public decimal NATURAINCOMEEMPLOYEE { get; set; }
        public decimal NATURADEDUCTION { get; set; }
        public decimal TAXINCENTIVE { get; set; }
        public decimal INCENTIVE { get; set; }
        public decimal PERIOD1 { get; set; }
        public decimal JAMSOSTEKINCENTIVE { get; set; }
        public decimal JAMSOSTEKDEDUCTION { get; set; }
        public decimal KOPERASI { get; set; }
        public decimal TAX { get; set; }
        public decimal DEBIT { get; set; }
        public decimal SPSI { get; set; }
        public decimal TOTALSALARY { get; set; }
        public string EMPNAME { get; set; }
        public string EMPTYPE { get; set; }
        public string POSITIONID { get; set; }
        public DateTime? JOINTDATE { get; set; }
        public string FAMILYSTATUS { get; set; }
        public string TAXSTATUS { get; set; }
        public string STATUSID { get; set; }
        public short REMAININGLEAVE { get; set; }
        public short LEAVE { get; set; }
        public string GOLONGAN { get; set; }
        public string SUPERVISORID { get; set; }

        public virtual TPAYMENT DOCNONavigation { get; set; }
        public virtual MEMPLOYEE EMP { get; set; }
        public virtual MPOSITION POSITION { get; set; }
        public virtual MSTATUS STATUS { get; set; }
        public virtual MEMPLOYEE SUPERVISOR { get; set; }
    }
}