// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPAYMENTWFADJUSTHKDETAIL
    {
        public string ID { get; set; }
        public string EMPID { get; set; }
        public string HARVESTCODE { get; set; }
        public DateTime HARVESTDATE { get; set; }
        public decimal HK { get; set; }
        public decimal ADJUSTEDHK { get; set; }
        public string NOTE { get; set; }
        public bool? APPROVED { get; set; }


        public bool? CANCEL { get; set; }

        public string ATTDOCID { get; set; }
        public int PROCESS { get; set; }
        public string PROCESSSTATUS { get; set; }
        public string REJECTEDBY { get; set; }
        public string REJECTIONREASON { get; set; }
        public DateTime? REJECTEDDATE { get; set; }

        
        public virtual TPAYMENTWFADJUSTHK TPAYMENTWFADJUSTHK { get; set; }
    }
}