// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPREMIMANDOR
    {
        public string UNITCODE { get; set; }
        public string DIVID { get; set; }
        public DateTime HARVESTDATE { get; set; }
        public string MANDORID { get; set; }
        public string MANDOR1ID { get; set; }
        public string KRANIID { get; set; }
        public short HARVESTTYPE { get; set; }
        public short HARVESTPAYMENTTYPE { get; set; }
        public string EMPTYPE { get; set; }
        public short EMPCOUNT { get; set; }
        public short TOTALEMP { get; set; }
        public decimal PREMIMANDORPCT { get; set; }
        public decimal PREMIKRANIPCT { get; set; }
        public decimal PREMIEMP { get; set; }
        public decimal PREMIMANDOR { get; set; }
        public decimal MANDORFINE { get; set; }
        public decimal PREMIKRANI { get; set; }
        public decimal KRANIFINE { get; set; }
        public string PAYMENTNO { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string ACTIVITYID { get; set; }

        public virtual MACTIVITY ACTIVITY { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE KRANI { get; set; }
        public virtual MEMPLOYEE MANDOR { get; set; }
        public virtual MEMPLOYEE MANDOR1 { get; set; }
        public virtual TPAYMENT PAYMENTNONavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}