// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPREMIMANDOR1
    {
        public string UNITID { get; set; }
        public DateTime DATE { get; set; }
        public string MANDORID { get; set; }
        public short HARVESTPAYMENTTYPE { get; set; }
        public decimal EMPPREMI { get; set; }
        public short EMPCOUNT { get; set; }
        public decimal PREMIPCT { get; set; }
        public decimal PREMI { get; set; }
        public decimal FINE { get; set; }
        public string PAYMENTNO { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MEMPLOYEE MANDOR { get; set; }
        public virtual TPAYMENT PAYMENTNONavigation { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
    }
}