// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TPREMINONPANEN
    {
        public string DOCNO { get; set; }
        public string DIVID { get; set; }
        public string EMPLOYEEID { get; set; }
        public string ACTIVITYID { get; set; }
        public DateTime PREMIDATE { get; set; }
        public decimal PREMIHK { get; set; }
        public decimal PREMIAMOUNT { get; set; }
        public string REMARK { get; set; }
        public string REF { get; set; }
        public string PAYMENTNO { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACTIVITY ACTIVITY { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE EMPLOYEE { get; set; }
    }
}