// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TRKHMATERIAL
    {
        public string RKHID { get; set; }
        public string ACTID { get; set; }
        public string MATID { get; set; }
        public decimal QTY { get; set; }
        public string UOM { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual MMATERIAL MAT { get; set; }
        public virtual TRKH RKH { get; set; }
    }
}