// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TRKHHASILKERJA
    {
        public string RKHID { get; set; }
        public decimal PRODKG { get; set; }
        public decimal BRONDOLKG { get; set; }
        public decimal BRONDOLPCT { get; set; }
        public short PANENTK { get; set; }
        public decimal OUTPUTPANEN { get; set; }
        public decimal PUPUKKG { get; set; }
        public short PUPUKTK { get; set; }
        public decimal OUTPUTPUPUK { get; set; }
        public decimal KLEENUP { get; set; }
        public decimal ALLY { get; set; }
        public short SEMPROTTK { get; set; }
        public decimal OUTPUTSEMPROT { get; set; }

        public virtual TRKH RKH { get; set; }
    }
}