// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TRKHESTPANEN
    {
        public string RKHID { get; set; }
        public decimal BASIS { get; set; }
        public decimal LEBIH { get; set; }
        public decimal OUTPUTPANEN { get; set; }
        public decimal ESTTKPANEN { get; set; }
        public decimal ANCAKPANEN { get; set; }
        public decimal OUTPUTANGKUT { get; set; }
        public decimal RITASI { get; set; }
        public decimal ESTBRONDOLPCT { get; set; }
        public decimal ESTBRONDOLKG { get; set; }
        public decimal OUTPUTKUTIP { get; set; }
        public decimal ESTTKBRONDOL { get; set; }
        public decimal RATIO { get; set; }

        public virtual TRKH RKH { get; set; }
    }
}