// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TRKHTAKSASI
    {
        public string RKHID { get; set; }
        public string BLOCKID { get; set; }
        public decimal BLOCKAREA { get; set; }
        public decimal WORKAREA { get; set; }
        public decimal SPH { get; set; }
        public decimal AKP { get; set; }
        public decimal JANJANG { get; set; }
        public decimal BJR { get; set; }
        public decimal KG { get; set; }
        public string TOPOGRAFI { get; set; }
        public decimal BASIS { get; set; }
        public decimal LEBIHBASIS { get; set; }
        public decimal OUTPUTPANEN { get; set; }
        public decimal ESTBUTUHPANEN { get; set; }
        public decimal ANCAKTK { get; set; }

        public virtual MORGANIZATION BLOCK { get; set; }
        public virtual TRKH RKH { get; set; }
    }
}