// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TRKH
    {
        public TRKH()
        {
            TRKHACTUAL = new HashSet<TRKHACTUAL>();
            TRKHDETAIL = new HashSet<TRKHDETAIL>();
            TRKHHERBISIDA = new HashSet<TRKHHERBISIDA>();
            TRKHMATERIAL = new HashSet<TRKHMATERIAL>();
            TRKHTAKSASI = new HashSet<TRKHTAKSASI>();            
            

            VRKHACTIVITYREF = new HashSet<VRKHACTIVITY>();
            VRKHBLOCKREF = new HashSet<VRKHBLOCK>();
            VRKHMANDORREF = new HashSet<VRKHMANDOR>();
            VRKHMATERIALREF = new HashSet<VRKHMATERIAL>();
        }

        public string ID { get; set; }
        public string DIVID { get; set; }
        public DateTime DATE { get; set; }
        public DateTime ACTDATE { get; set; }
        public short PAYMENTTYPE { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MORGANIZATION DIV { get; set; }
        public virtual TRKHESTPANEN TRKHESTPANEN { get; set; }
        public virtual TRKHHASILKERJA TRKHHASILKERJA { get; set; }
        public virtual ICollection<TRKHACTUAL> TRKHACTUAL { get; set; }
        public virtual ICollection<TRKHDETAIL> TRKHDETAIL { get; set; }
        public virtual ICollection<TRKHHERBISIDA> TRKHHERBISIDA { get; set; }
        public virtual ICollection<TRKHMATERIAL> TRKHMATERIAL { get; set; }
        public virtual ICollection<TRKHTAKSASI> TRKHTAKSASI { get; set; }


        //Custom
        
        public virtual ICollection<VRKHACTIVITY> VRKHACTIVITYREF { get; set; }
        public virtual ICollection<VRKHBLOCK> VRKHBLOCKREF { get; set; }
        public virtual ICollection<VRKHMANDOR> VRKHMANDORREF { get; set; }
        public virtual ICollection<VRKHMATERIAL> VRKHMATERIALREF { get; set; }


    }
}