// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TRKHACTUAL
    {
        public string RKHID { get; set; }
        public string ACTID { get; set; }
        public string SPVID { get; set; }
        public short EMPCOUNT { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual TRKH RKH { get; set; }
        public virtual MEMPLOYEE SPV { get; set; }
    }
}