// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TRUNNINGACCOUNTBLOCK
    {
        public string TRUNNINGACCOUNTCODE { get; set; }
        public string ACTIVITYID { get; set; }
        public string BLOCKID { get; set; }
        public decimal OUTPUTAREA { get; set; }
        public decimal OUTPUTKONVERSI { get; set; }
        public decimal? RANGE { get; set; }
        public decimal HMBEGIN { get; set; }
        public decimal HMEND { get; set; }
        public DateTime HOURBEGIN { get; set; }
        public DateTime HOUREND { get; set; }
        public decimal VALUE { get; set; }

        public virtual MBLOCK BLOCK { get; set; }
        public virtual TRUNNINGACCOUNT TRUNNINGACCOUNTCODENavigation { get; set; }
    }
}