// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TRUNNINGACCOUNT
    {
        public TRUNNINGACCOUNT()
        {
            TRUNNINGACCOUNTBLOCK = new HashSet<TRUNNINGACCOUNTBLOCK>();
        }

        public string TRUNNINGACCOUNTCODE { get; set; }
        public string DIVID { get; set; }
        public DateTime? TRUNNINGACCOUNTDATE { get; set; }
        public string RUNNINGACCOUNTID { get; set; }
        public string OPERATOR { get; set; }
        public string HELPER { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime? CREATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime? UPDATEDDATE { get; set; }
        public string CANCELEDCOMMENT { get; set; }

        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE OPERATORNavigation { get; set; }
        public virtual MRUNNINGACCOUNT RUNNINGACCOUNT { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual ICollection<TRUNNINGACCOUNTBLOCK> TRUNNINGACCOUNTBLOCK { get; set; }
    }
}