// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TSALARYITEM
    {
        public string ID { get; set; }
        public string UNITID { get; set; }
        public string TYPEID { get; set; }
        public string EMPID { get; set; }
        public string ACTID { get; set; }
        public string EQUIPID { get; set; }
        public DateTime DATE { get; set; }
        public decimal AMOUNT { get; set; }
        public string PAYMENTNO { get; set; }
        public string MAPREF { get; set; }
        public bool AUTO { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MACTIVITY ACT { get; set; }
        public virtual MEMPLOYEE EMP { get; set; }
        public virtual TPAYMENT PAYMENTNONavigation { get; set; }
        public virtual MSALARYTYPE TYPE { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
    }
}