// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TSALARYTYPEMAP
    {
        public string ID { get; set; }
        public string UNITID { get; set; }
        public string TYPEID { get; set; }
        public string FREQ { get; set; }
        public string POSID { get; set; }
        public string GOL { get; set; }
        public string EMPID { get; set; }
        public decimal HKMIN { get; set; }
        public decimal AMOUNT { get; set; }
        public string STATUS { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual MEMPLOYEE EMP { get; set; }
        public virtual MPOSITION POS { get; set; }
        public virtual MSALARYTYPE TYPE { get; set; }
        public virtual MORGANIZATION UNIT { get; set; }
    }
}