// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TSPBDETAIL
    {
        public string SPBNO { get; set; }
        public string BLOCKID { get; set; }
        public short PLANTINGMONTH { get; set; }
        public short PLANTINGYEAR { get; set; }
        public decimal FRUITCOUNT { get; set; }
        public decimal ESTIMATEDFRUITBUNCH { get; set; }
        public decimal ESTIMATEDFRUITPIECES { get; set; }
        public DateTime TIMESEND { get; set; }

        public virtual MBLOCK BLOCK { get; set; }
        public virtual TSPB SPBNONavigation { get; set; }
    }
}