// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;

namespace PMS.EFCore.Model
{
    public partial class TSPB
    {
        public TSPB()
        {
            TKARTUTIMBANG = new HashSet<TKARTUTIMBANG>();
            TSPBDETAIL = new HashSet<TSPBDETAIL>();
        }

        public string SPBNO { get; set; }
        public string SPBNODHS { get; set; }
        public string DIVID { get; set; }
        public DateTime SPBDATE { get; set; }
        public string MILLCODE { get; set; }
        public string VEHICLENO { get; set; }
        public string DRIVERNAME { get; set; }
        public string OPERATORNAME { get; set; }
        public string REMARK { get; set; }
        public decimal TOTALSPB { get; set; }
        public decimal TOTALKT { get; set; }
        public decimal TOTALTIMBANG { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATED { get; set; }
        public short? UPLOAD { get; set; }
        public DateTime? UPLOADDATE { get; set; }

        public virtual MDIVISI DIV { get; set; }
        public virtual MMILL MILLCODENavigation { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual ICollection<TKARTUTIMBANG> TKARTUTIMBANG { get; set; }
        public virtual ICollection<TSPBDETAIL> TSPBDETAIL { get; set; }

        //Custom Property
        public decimal TotalWeight
        {
            get
            {
                if (TKARTUTIMBANG == null) return 0;
                var q = TKARTUTIMBANG.Where(itm => itm.SRNO == 1).Select(itm => itm.WEIGHT);
                var r = TKARTUTIMBANG.Where(itm => itm.SRNO == 2).Select(itm => itm.WEIGHT);
                return q.Sum() - r.Sum();
            }
        }

        public decimal TotalFruit
        {
            get
            {
                if (TSPBDETAIL == null) return 0;
                var q = TSPBDETAIL.Select(itm => itm.FRUITCOUNT);
                return q.Sum();
            }
        }


    }
}