// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TSTOCK
    {
        public string LOCCODE { get; set; }
        public string MATERIALID { get; set; }
        public short YEAR { get; set; }
        public decimal IN0 { get; set; }
        public decimal IN1 { get; set; }
        public decimal IN2 { get; set; }
        public decimal IN3 { get; set; }
        public decimal IN4 { get; set; }
        public decimal IN5 { get; set; }
        public decimal IN6 { get; set; }
        public decimal IN7 { get; set; }
        public decimal IN8 { get; set; }
        public decimal IN9 { get; set; }
        public decimal IN10 { get; set; }
        public decimal IN11 { get; set; }
        public decimal IN12 { get; set; }
        public decimal OUT0 { get; set; }
        public decimal OUT1 { get; set; }
        public decimal OUT2 { get; set; }
        public decimal OUT3 { get; set; }
        public decimal OUT4 { get; set; }
        public decimal OUT5 { get; set; }
        public decimal OUT6 { get; set; }
        public decimal OUT7 { get; set; }
        public decimal OUT8 { get; set; }
        public decimal OUT9 { get; set; }
        public decimal OUT10 { get; set; }
        public decimal OUT11 { get; set; }
        public decimal OUT12 { get; set; }
        public decimal AMOUNTIN0 { get; set; }
        public decimal AMOUNTIN1 { get; set; }
        public decimal AMOUNTIN2 { get; set; }
        public decimal AMOUNTIN3 { get; set; }
        public decimal AMOUNTIN4 { get; set; }
        public decimal AMOUNTIN5 { get; set; }
        public decimal AMOUNTIN6 { get; set; }
        public decimal AMOUNTIN7 { get; set; }
        public decimal AMOUNTIN8 { get; set; }
        public decimal AMOUNTIN9 { get; set; }
        public decimal AMOUNTIN10 { get; set; }
        public decimal AMOUNTIN11 { get; set; }
        public decimal AMOUNTIN12 { get; set; }
        public decimal AMOUNTOUT1 { get; set; }
        public decimal AMOUNTOUT2 { get; set; }
        public decimal AMOUNTOUT3 { get; set; }
        public decimal AMOUNTOUT4 { get; set; }
        public decimal AMOUNTOUT5 { get; set; }
        public decimal AMOUNTOUT6 { get; set; }
        public decimal AMOUNTOUT7 { get; set; }
        public decimal AMOUNTOUT8 { get; set; }
        public decimal AMOUNTOUT9 { get; set; }
        public decimal AMOUNTOUT10 { get; set; }
        public decimal AMOUNTOUT11 { get; set; }
        public decimal AMOUNTOUT12 { get; set; }

        public virtual MSTORELOCATION LOCCODENavigation { get; set; }
        public virtual MMATERIAL MATERIAL { get; set; }
    }
}