// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TSTOCKADJUST
    {
        public string ID { get; set; }
        public string LOCCODE { get; set; }
        public string MATERIALID { get; set; }
        public short YEAR { get; set; }
        public short MONTH { get; set; }
        public decimal QTY { get; set; }
        public decimal AMOUNT { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }

        public virtual MSTORELOCATION LOCCODENavigation { get; set; }
        public virtual MMATERIAL MATERIAL { get; set; }
    }
}