// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TSTOCKMOVEMENT
    {
        public string CODE { get; set; }
        public string LOCCODE { get; set; }
        public string NO { get; set; }
        public DateTime DATE { get; set; }
        public string UNITCODE { get; set; }
        public string STATUS { get; set; }
        public string MATERIALID { get; set; }
        public string DIRECT { get; set; }
        public decimal STOCK { get; set; }
        public decimal QTY { get; set; }
        public decimal PRICE { get; set; }
        public decimal EXPVALUE { get; set; }
        public string NOTE { get; set; }
        public string BLOCKID { get; set; }

        public virtual MBLOCK BLOCK { get; set; }
        public virtual MSTORELOCATION LOCCODENavigation { get; set; }
        public virtual MMATERIAL MATERIAL { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual MUNIT UNITCODENavigation { get; set; }
    }
}