// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TSURATPERINGATAN
    {
        public string UNITCODE { get; set; }
        public string NOSP { get; set; }
        public DateTime? TGLSP { get; set; }
        public string TYPESP { get; set; }
        public string EMPID { get; set; }
        public string POSITIONID { get; set; }
        public DateTime? TGLAWALM { get; set; }
        public DateTime? TGLAKHIRM { get; set; }
        public DateTime? TGLPANGGILAN { get; set; }
        public string TEMPATPANGGILAN { get; set; }
        public string NOSP1 { get; set; }
        public string NOSP2 { get; set; }
        public string STATUS { get; set; }
        public string STATUSACCEPT { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }
        public string ISPROCESS { get; set; }
        public virtual MEMPLOYEE EMP { get; set; }
    }
}