// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TTRANMILLITM
    {
        public string ID { get; set; }
        public string TRANID { get; set; }
        public string BLOCKID { get; set; }
        public decimal BUNCH { get; set; }
        public decimal FRUIT { get; set; }
        public bool CSPO { get; set; }
        public decimal BJR { get; set; }
        public decimal BUNCHKG { get; set; }
        public decimal FRUITKG { get; set; }

        public virtual TTRANMILL TRAN { get; set; }
    }
}