// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TUPKEEPBLOCK
    {
        public string UPKEEPCODE { get; set; }
        public string BLOCKID { get; set; }
        public decimal OUTPUTAREA { get; set; }
        public decimal OUTPUTKONVERSI { get; set; }
        public decimal VALUE { get; set; }

        public virtual MBLOCK BLOCK { get; set; }
        public virtual TUPKEEP UPKEEP { get; set; }
    }
}