// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.EFCore.Model
{
    public partial class TUPKEEPMATERIAL
    {
        public string UPKEEPCODE { get; set; }
        public string ACTIVITYID { get; set; }
        public string BLOCKID { get; set; }
        public string MATERIALID { get; set; }
        public decimal QUANTITY { get; set; }
        public string BATCHID { get; set; }
        public decimal STOCK { get; set; }

        public virtual MACTIVITY ACTIVITY { get; set; }
        public virtual MBLOCK BATCH { get; set; }
        public virtual MBLOCK BLOCK { get; set; }
        public virtual MMATERIAL MATERIAL { get; set; }
        public virtual TUPKEEP UPKEEP { get; set; }
    }
}