// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TUPKEEPVENDOR
    {
        public string UPKEEPCODE { get; set; }
        public decimal OUTPUT { get; set; }
        public decimal PRICE { get; set; }
        public decimal VALUE { get; set; }

        public virtual TUPKEEP UPKEEP { get; set; }
    }
}