// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class TUPKEEP
    {
        public TUPKEEP()
        {
            TUPKEEPBLOCK = new HashSet<TUPKEEPBLOCK>();
            TUPKEEPEMPLOYEE = new HashSet<TUPKEEPEMPLOYEE>();
            TUPKEEPMATERIAL = new HashSet<TUPKEEPMATERIAL>();
            TUPKEEPCALC = new HashSet<TUPKEEPCALC>();
        }

        public string UPKEEPCODE { get; set; }
        public string DIVID { get; set; }
        public DateTime UPKEEPDATE { get; set; }
        public string ACTIVITYID { get; set; }
        public string MANDORID { get; set; }
        public short UPKEEPTYPE { get; set; }
        public string CONTID { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public string CREATEBY { get; set; }
        public DateTime CREATEDDATE { get; set; }
        public string UPDATEBY { get; set; }
        public DateTime UPDATEDDATE { get; set; }
        public string CANCELEDCOMMENT { get; set; }
        public short UPLOAD { get; set; }
        public DateTime? UPLOADDATE { get; set; }

        public virtual MACTIVITY ACTIVITY { get; set; }
        public virtual MDIVISI DIV { get; set; }
        public virtual MEMPLOYEE MANDOR { get; set; }
        public virtual MDOCSTATUS STATUSNavigation { get; set; }
        public virtual MUPKEEPTYPE UPKEEPTYPENavigation { get; set; }
        public virtual ICollection<TUPKEEPBLOCK> TUPKEEPBLOCK { get; set; }
        public virtual ICollection<TUPKEEPEMPLOYEE> TUPKEEPEMPLOYEE { get; set; }
        public virtual ICollection<TUPKEEPMATERIAL> TUPKEEPMATERIAL { get; set; }
        public virtual TUPKEEPVENDOR TUPKEEPVENDOR { get; set; }
        public virtual ICollection<TUPKEEPCALC> TUPKEEPCALC { get; set; }
    }
}