// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.EFCore.Model
{
    public partial class TUPKEEPCALC
    {
        public string UPKEEPCODE { get; set; }
        public string EMPLOYEEID { get; set; }
        public string BLOCKID { get; set; }
        public decimal VALUE { get; set; }
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        //public string CALCID { get; set; }

        public virtual TUPKEEP UPKEEP { get; set; }
    }
}