// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class WFDOCUMENTVIEW
    {
        public string CODE { get; set; }
        public string LASTACTIVITYNAME { get; set; }
        public string LASTACTIONTEXT { get; set; }
        public string DOCSTATUSTEXT { get; set; }
        public string LASTACTIVITY { get; set; }
        public string NEXTACTIVITYNAME { get; set; }

        public virtual WFDOCUMENT CODENavigation { get; set; }
    }
}