// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class WFDOCUMENT
    {
        public WFDOCUMENT()
        {
            WFDOCUMENTBAFDETAIL = new HashSet<WFDOCUMENTBAFDETAIL>();
        }

        public string CODE { get; set; }
        public long? WFDOCTRANSNO { get; set; }
        public string WFDOCNO { get; set; }
        public DateTime DOCDATE { get; set; }
        public string DOCTYPE { get; set; }
        public string DOCOWNER { get; set; }
        public string DOCSTATUS { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string UNITID { get; set; }
        public long? WORKFLOWTRANSACTIONNO { get; set; }
        public DateTime? LASTUPDATEDATE { get; set; }
        public string LASTUPDATEUSER { get; set; }
        public string ATTACHMENTPATH { get; set; }

        public virtual WFDOCUMENTPREMINONPANEN WFDOCUMENTPREMINONPANEN { get; set; }
        public virtual WFDOCUMENTVIEW WFDOCUMENTVIEW { get; set; }
        public virtual ICollection<WFDOCUMENTBAFDETAIL> WFDOCUMENTBAFDETAIL { get; set; }
    }
}