// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class WFDOCUMENTPREMINONPANEN
    {
        public string CODE { get; set; }
        public string PREMINO { get; set; }

        public virtual WFDOCUMENT CODENavigation { get; set; }
    }
}