// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class WFDOCUMENTBAFDETAIL
    {
        public string CODE { get; set; }
        public DateTime FINGERDATE { get; set; }
        public string EMPLOYEEID { get; set; }
        public string DIVISIONID { get; set; }
        public string CARD { get; set; }
        public string REASON { get; set; }
        public bool STATUS { get; set; }

        public virtual WFDOCUMENT CODENavigation { get; set; }
    }
}