// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class Z_TPH
    {
        public string ID { get; set; }
        public string LT { get; set; }
        public string LG { get; set; }
    }
}