// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PMS.EFCore.Model
{
    public partial class zKontanan
    {
        public string UNITID { get; set; }
        public string EMPID { get; set; }
        public DateTime DATE { get; set; }
        public string BLOCKID { get; set; }
        public decimal QTY { get; set; }
        public decimal BASE1 { get; set; }
        public decimal AMOUNT { get; set; }
    }
}