// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace FileStorage.EFCore
{
    public partial class File
    {
        public long FileID { get; set; }
        public byte[] FileContent { get; set; }
        public string FileType { get; set; }
        public DateTime? Created { get; set; }
        public string CreatedBy { get; set; }
        public string UsedBy { get; set; }
    }
}