// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class AutoNumberHistoryConfiguration : IEntityTypeConfiguration<AutoNumberHistory>
    {
        public void Configure(EntityTypeBuilder<AutoNumberHistory> entity)
        {
            entity.HasKey(e => e.DocNo)
                .HasName("PK__AutoNumb__3EF1E0568519E503");

            entity.Property(e => e.DocNo)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.DocDate).HasColumnType("datetime");

            entity.Property(e => e.DocTypeID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UnitID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        }
    }
}
