// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DelegationDocumentConfiguration : IEntityTypeConfiguration<DelegationDocument>
    {
        public void Configure(EntityTypeBuilder<DelegationDocument> entity)
        {
            entity.HasKey(e => new { e.DelegationNo, e.DocTransNo });

            entity.HasOne(d => d.DelegationNoNavigation)
                .WithMany(p => p.DelegationDocument)
                .HasForeignKey(d => d.DelegationNo)
                .HasConstraintName("FK_DelegationDocument_Delegation");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithMany(p => p.DelegationDocument)
                .HasForeignKey(d => d.DocTransNo)
                .HasConstraintName("FK_DelegationDocument_Document");
        }
    }
}
