// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DelegationConfiguration : IEntityTypeConfiguration<Delegation>
    {
        public void Configure(EntityTypeBuilder<Delegation> entity)
        {
            entity.HasKey(e => e.DelegationNo);

            entity.Property(e => e.DelegationNo).ValueGeneratedNever();

            entity.Property(e => e.ClosedReason)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.FromDate).HasColumnType("date");

            entity.Property(e => e.FromUser)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ToDate).HasColumnType("date");

            entity.Property(e => e.ToUser)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        }
    }
}
