// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentPTADetailsConfiguration : IEntityTypeConfiguration<DocumentPTADetails>
    {
        public void Configure(EntityTypeBuilder<DocumentPTADetails> entity)
        {
            entity.HasKey(e => new { e.DocTransNo, e.LineItem });

            entity.Property(e => e.BudgetCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.CJ32DocNo)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.CJ36DocNo)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.CostCenter)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.CostElement)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.CurrentBudgetNeeds).HasColumnType("decimal(20, 0)");

            entity.Property(e => e.LastError)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.LineDescription)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.PrevRealizedBudget).HasColumnType("decimal(20, 0)");

            entity.Property(e => e.TotalBudget).HasColumnType("decimal(20, 0)");

            entity.Property(e => e.WBSElement)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.CostElementNavigation)
                .WithMany(p => p.DocumentPTADetails)
                .HasForeignKey(d => d.CostElement)
                .HasConstraintName("FK_DocumentPTADetails_PTACostElement");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithMany(p => p.DocumentPTADetails)
                .HasForeignKey(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentPTADetails_DocumentPTA");

            entity.HasOne(d => d.WBSElementNavigation)
                .WithMany(p => p.DocumentPTADetails)
                .HasForeignKey(d => d.WBSElement)
                .HasConstraintName("FK_DocumentPTADetails_PTAWBSElement");
        }
    }
}
