// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentITRequestConfiguration : IEntityTypeConfiguration<DocumentITRequest>
    {
        public void Configure(EntityTypeBuilder<DocumentITRequest> entity)
        {
            entity.HasKey(e => e.DocTransNo);

            entity.Property(e => e.DocTransNo).ValueGeneratedNever();

            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ResourceReq)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.RollbackDesc)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.TestPlanDesc)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithOne(p => p.DocumentITRequest)
                .HasForeignKey<DocumentITRequest>(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentITRequest_Document");
        }
    }
}
