// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentPDOConfiguration : IEntityTypeConfiguration<DocumentPDO>
    {
        public void Configure(EntityTypeBuilder<DocumentPDO> entity)
        {
            entity.HasKey(e => e.DocTransNo)
                .HasName("PK_DocumentPDO_1");

            entity.Property(e => e.DocTransNo).ValueGeneratedNever();

            entity.Property(e => e.Period).HasColumnType("date");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithOne(p => p.DocumentPDO)
                .HasForeignKey<DocumentPDO>(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentPDO_Document");
        }
    }
}
