// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentViewTypeConfiguration : IEntityTypeConfiguration<DocumentViewType>
    {
        public void Configure(EntityTypeBuilder<DocumentViewType> entity)
        {
            entity.HasKey(e => e.DocViewID);

            entity.Property(e => e.DocViewID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.DocTypeID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DocViewName)
                .IsRequired()
                .HasMaxLength(120)
                .IsUnicode(false);

            entity.Property(e => e.EditControllerName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.IndexControllerName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.ViewDocumentName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.DocType)
                .WithMany(p => p.DocumentViewType)
                .HasForeignKey(d => d.DocTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentViewType_DocumentType");
        }
    }
}
