// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentBAFingerConfiguration : IEntityTypeConfiguration<DocumentBAFinger>
    {
        public void Configure(EntityTypeBuilder<DocumentBAFinger> entity)
        {
            entity.HasKey(e => e.DocTransNo)
                .HasName("PK__Document__B817723BA8F4BCED");

            entity.Property(e => e.DocTransNo).ValueGeneratedNever();

            entity.Property(e => e.DivisionID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.FingerDate).HasColumnType("datetime");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithOne(p => p.DocumentBAFinger)
                .HasForeignKey<DocumentBAFinger>(d => d.DocTransNo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentBAFinger_Document");
        }
    }
}
