// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentTypeConfiguration : IEntityTypeConfiguration<DocumentType>
    {
        public void Configure(EntityTypeBuilder<DocumentType> entity)
        {
            entity.HasKey(e => e.DocTypeID)
                .HasName("PK__tmp_ms_x__055E268317C286CF");

            entity.Property(e => e.DocTypeID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.AMAlias)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.ANFormat)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.ANNumberFormat)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ANPeriodFormat)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ANPeriodPartition)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false);

            entity.Property(e => e.ANPostFix)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.ANPrefix)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DefaultControllerName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.EmailTemplateID)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.IndexControllerName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.WorkflowID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.EmailTemplate)
                .WithMany(p => p.DocumentType)
                .HasForeignKey(d => d.EmailTemplateID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentType_EmailContentTemplate");

            entity.HasOne(d => d.Workflow)
                .WithMany(p => p.DocumentType)
                .HasForeignKey(d => d.WorkflowID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentType_Workflow");
        }
    }
}
