// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentHistoryConfiguration : IEntityTypeConfiguration<DocumentHistory>
    {
        public void Configure(EntityTypeBuilder<DocumentHistory> entity)
        {
            entity.HasKey(e => new { e.DocTransNo, e.SequenceNo });

            entity.Property(e => e.Date).HasColumnType("datetime");

            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.UserID)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithMany(p => p.DocumentHistory)
                .HasForeignKey(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentHistory_Document");
        }
    }
}
