// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentBAFingerDetailConfiguration : IEntityTypeConfiguration<DocumentBAFingerDetail>
    {
        public void Configure(EntityTypeBuilder<DocumentBAFingerDetail> entity)
        {
            entity.HasKey(e => new { e.DocTransNo, e.FingerDate, e.EmployeeID });

            entity.Property(e => e.FingerDate).HasColumnType("datetime");

            entity.Property(e => e.EmployeeID)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Card)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DivisionID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.MandorID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.MandorName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.NIK)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Reason)
                .HasMaxLength(999)
                .IsUnicode(false);

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithMany(p => p.DocumentBAFingerDetail)
                .HasForeignKey(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentBAFingerDetail_Document");
        }
    }
}
