// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentITRequestAppTypeConfiguration : IEntityTypeConfiguration<DocumentITRequestAppType>
    {
        public void Configure(EntityTypeBuilder<DocumentITRequestAppType> entity)
        {
            entity.HasKey(e => new { e.DocTransNo, e.AppType });

            entity.Property(e => e.AppType)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.AppTypeNavigation)
                .WithMany(p => p.DocumentITRequestAppType)
                .HasForeignKey(d => d.AppType)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentITRequestAppType_ITRequestAppType");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithMany(p => p.DocumentITRequestAppType)
                .HasForeignKey(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentITRequestAppType_DocumentITRequest");
        }
    }
}
