// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentITServiceConfiguration : IEntityTypeConfiguration<DocumentITService>
    {
        public void Configure(EntityTypeBuilder<DocumentITService> entity)
        {
            entity.HasKey(e => e.DocTransNo);

            entity.Property(e => e.DocTransNo).ValueGeneratedNever();

            entity.Property(e => e.AssetNo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.CheckingDate).HasColumnType("date");

            entity.Property(e => e.CheckingResult)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.DeviceOwner)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.DeviceSN)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.ITAssetManagerActionRec)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.ITAssetManagerRec)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.ITInfraRec)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.ITOfficerRec)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.PRNo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.PurchaseDate).HasColumnType("date");

            entity.Property(e => e.Specification)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ToolType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValueSql("('PC/Notebook')");

            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValueSql("('IT Service')");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithOne(p => p.DocumentITService)
                .HasForeignKey<DocumentITService>(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentITService_Document");
        }
    }
}
