// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentPDODetailAttachmentsConfiguration : IEntityTypeConfiguration<DocumentPDODetailAttachments>
    {
        public void Configure(EntityTypeBuilder<DocumentPDODetailAttachments> entity)
        {
            entity.HasKey(e => new { e.DocTransNo, e.LineItem, e.FileID });

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.FileType)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.HasOne(d => d.File)
                .WithMany(p => p.DocumentPDODetailAttachments)
                .HasForeignKey(d => d.FileID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentPDODetailAttachments_File");

            entity.HasOne(d => d.DocumentPDODetails)
                .WithMany(p => p.DocumentPDODetailAttachments)
                .HasForeignKey(d => new { d.DocTransNo, d.LineItem })
                .HasConstraintName("FK_DocumentPDODetailAttachments_DocumentPDODetails");
        }
    }
}
