// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentAccessTokenConfiguration : IEntityTypeConfiguration<DocumentAccessToken>
    {
        public void Configure(EntityTypeBuilder<DocumentAccessToken> entity)
        {
            entity.HasKey(e => e.TokenID);

            entity.Property(e => e.TokenID)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.AccessType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Bcc)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.Body)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.Cc)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.ExpiredDate).HasColumnType("datetime");

            entity.Property(e => e.IsHTML)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.LastErrorText)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.SentDate).HasColumnType("datetime");

            entity.Property(e => e.SessionID)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Status)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.Subject)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.To)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.UserID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        }
    }
}
