// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentPremiNonPanenConfiguration : IEntityTypeConfiguration<DocumentPremiNonPanen>
    {
        public void Configure(EntityTypeBuilder<DocumentPremiNonPanen> entity)
        {
            entity.HasKey(e => e.DocTransNo);

            entity.Property(e => e.DocTransNo).ValueGeneratedNever();

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.Date).HasColumnType("datetime");

            entity.Property(e => e.DivisionID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.EmployeeID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.No)
                .IsRequired()
                .HasMaxLength(22)
                .IsUnicode(false);

            entity.Property(e => e.Remark)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValueSql("('Proses')");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithOne(p => p.DocumentPremiNonPanen)
                .HasForeignKey<DocumentPremiNonPanen>(d => d.DocTransNo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentPremiNonPanen_Document");
        }
    }
}
