// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentAttachmentConfiguration : IEntityTypeConfiguration<DocumentAttachment>
    {
        public void Configure(EntityTypeBuilder<DocumentAttachment> entity)
        {
            entity.HasKey(e => new { e.DocTransNo, e.FileID })
                .HasName("PK__Document__5EE78BB2014935CB");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.FileType)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithMany(p => p.DocumentAttachment)
                .HasForeignKey(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentAttachment_Document");

            entity.HasOne(d => d.File)
                .WithMany(p => p.DocumentAttachment)
                .HasForeignKey(d => d.FileID)
                .HasConstraintName("FK_DocumentAttachment_File");
        }
    }
}
