// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentITAksesConfiguration : IEntityTypeConfiguration<DocumentITAkses>
    {
        public void Configure(EntityTypeBuilder<DocumentITAkses> entity)
        {
            entity.HasKey(e => e.DocTransNo)
                .HasName("PK_DocumentATEPI");

            entity.Property(e => e.DocTransNo).ValueGeneratedNever();

            entity.Property(e => e.AccessTypes)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.Grade)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.Internet)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.NIK)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.Position)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.Printer)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.Telp)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithOne(p => p.DocumentITAkses)
                .HasForeignKey<DocumentITAkses>(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentATEPI_Document");
        }
    }
}
