// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentTypeNotificationTemplateConfiguration : IEntityTypeConfiguration<DocumentTypeNotificationTemplate>
    {
        public void Configure(EntityTypeBuilder<DocumentTypeNotificationTemplate> entity)
        {
            entity.HasKey(e => new { e.DocTypeID, e.ActionTypeID })
                .HasName("PK__Document__5371C24333B1D03A");

            entity.Property(e => e.DocTypeID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.ActionTypeID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.NotifToNextApproversEmailSubject).IsUnicode(false);

            entity.Property(e => e.NotifToNextApproversTemplate)
                .IsRequired()
                .IsUnicode(false);

            entity.Property(e => e.NotifToOwnerEmailSubject).IsUnicode(false);

            entity.Property(e => e.NotifToOwnerTemplate)
                .IsRequired()
                .IsUnicode(false);

            entity.Property(e => e.NotifToPrevApproversEmailSubject).IsUnicode(false);

            entity.Property(e => e.NotifToPrevApproversTemplate)
                .IsRequired()
                .IsUnicode(false);
        }
    }
}
