// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentPTAConfiguration : IEntityTypeConfiguration<DocumentPTA>
    {
        public void Configure(EntityTypeBuilder<DocumentPTA> entity)
        {
            entity.HasKey(e => e.DocTransNo);

            entity.Property(e => e.DocTransNo).ValueGeneratedNever();

            entity.Property(e => e.BudgetCode)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.CostCenter)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CostElement)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CurrencyCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.PTAAmmount).HasColumnType("decimal(20, 0)");

            entity.Property(e => e.PTAFlag)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.PTAReason)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.PTAType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Priority)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.WBSElement)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithOne(p => p.DocumentPTA)
                .HasForeignKey<DocumentPTA>(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentPTA_Document");
        }
    }
}
