// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class DocumentITRequestChangeTypeConfiguration : IEntityTypeConfiguration<DocumentITRequestChangeType>
    {
        public void Configure(EntityTypeBuilder<DocumentITRequestChangeType> entity)
        {
            entity.HasKey(e => new { e.DocTransNo, e.ChangeType });

            entity.Property(e => e.ChangeType)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ChangeTypeNavigation)
                .WithMany(p => p.DocumentITRequestChangeType)
                .HasForeignKey(d => d.ChangeType)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentITRequestChangeType_ITRequestChangeType");

            entity.HasOne(d => d.DocTransNoNavigation)
                .WithMany(p => p.DocumentITRequestChangeType)
                .HasForeignKey(d => d.DocTransNo)
                .HasConstraintName("FK_DocumentITRequestChangeType_DocumentITRequest");
        }
    }
}
