// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class EmailContentTemplateConfiguration : IEntityTypeConfiguration<EmailContentTemplate>
    {
        public void Configure(EntityTypeBuilder<EmailContentTemplate> entity)
        {
            entity.HasKey(e => e.TemplateID);

            entity.Property(e => e.TemplateID)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.EmailContent)
                .IsRequired()
                .IsUnicode(false);
        }
    }
}
