// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class ITRequestChangeTypeConfiguration : IEntityTypeConfiguration<ITRequestChangeType>
    {
        public void Configure(EntityTypeBuilder<ITRequestChangeType> entity)
        {
            entity.HasKey(e => e.ChangeTypeID);

            entity.Property(e => e.ChangeTypeID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        }
    }
}
