// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class PDOVendorConfiguration : IEntityTypeConfiguration<PDOVendor>
    {
        public void Configure(EntityTypeBuilder<PDOVendor> entity)
        {
            entity.HasKey(e => e.VendorCode);

            entity.Property(e => e.VendorCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.AccountNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.BankAccountName)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.BankName)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CompanyCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.VendorName)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
        }
    }
}
