// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class PTACostCenterConfiguration : IEntityTypeConfiguration<PTACostCenter>
    {
        public void Configure(EntityTypeBuilder<PTACostCenter> entity)
        {
            entity.HasKey(e => e.CostCenterID);

            entity.Property(e => e.CostCenterID)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Flag)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UnitID)
                .HasMaxLength(20)
                .IsUnicode(false);
        }
    }
}
