// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class PTACostElementConfiguration : IEntityTypeConfiguration<PTACostElement>
    {
        public void Configure(EntityTypeBuilder<PTACostElement> entity)
        {
            entity.HasKey(e => e.CostElementID);

            entity.Property(e => e.CostElementID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        }
    }
}
