// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class PTATypeConfiguration : IEntityTypeConfiguration<PTAType>
    {
        public void Configure(EntityTypeBuilder<PTAType> entity)
        {
            entity.Property(e => e.PTATypeID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");

            entity.Property(e => e.LastUpdateUser)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.PTAFlag)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.WBSRelated)
                .IsRequired()
                .HasDefaultValueSql("((1))");
        }
    }
}
