// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class PTAWBSElementConfiguration : IEntityTypeConfiguration<PTAWBSElement>
    {
        public void Configure(EntityTypeBuilder<PTAWBSElement> entity)
        {
            entity.HasKey(e => e.ElementId);

            entity.Property(e => e.ElementId)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Flag)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.ObjectNo)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.ProjectType)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.UnitID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Unit)
                .WithMany(p => p.PTAWBSElement)
                .HasForeignKey(d => d.UnitID)
                .HasConstraintName("FK_PTAWBSElement_UnitStructure");
        }
    }
}
