// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class PTAWBSElement_tempConfiguration : IEntityTypeConfiguration<PTAWBSElement_temp>
    {
        public void Configure(EntityTypeBuilder<PTAWBSElement_temp> entity)
        {
            entity.HasKey(e => new { e.SessionId, e.ElementId });

            entity.Property(e => e.SessionId)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.ElementId)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Flag)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.ObjectNo)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.ProjectType)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.UnitID)
                .HasMaxLength(20)
                .IsUnicode(false);
        }
    }
}
