// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class ReferenceCodeConfiguration : IEntityTypeConfiguration<ReferenceCode>
    {
        public void Configure(EntityTypeBuilder<ReferenceCode> entity)
        {
            entity.HasKey(e => new { e.ReferenceID, e.Code })
                .HasName("PK_Reference");

            entity.Property(e => e.ReferenceID)
                .HasMaxLength(25)
                .IsUnicode(false);

            entity.Property(e => e.Code)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("((1))");
        }
    }
}
