// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class RoleDocumentTypeConfiguration : IEntityTypeConfiguration<RoleDocumentType>
    {
        public void Configure(EntityTypeBuilder<RoleDocumentType> entity)
        {
            entity.HasKey(e => new { e.RoleID, e.DocTypeID });

            entity.Property(e => e.RoleID)
                .HasMaxLength(40)
                .IsUnicode(false);

            entity.Property(e => e.DocTypeID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.DocType)
                .WithMany(p => p.RoleDocumentType)
                .HasForeignKey(d => d.DocTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleDocumentType_DocumentType");

            entity.HasOne(d => d.Role)
                .WithMany(p => p.RoleDocumentType)
                .HasForeignKey(d => d.RoleID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleDocumentType_Role");
        }
    }
}
