// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class RoleActivityConfiguration : IEntityTypeConfiguration<RoleActivity>
    {
        public void Configure(EntityTypeBuilder<RoleActivity> entity)
        {
            entity.HasKey(e => new { e.RoleID, e.ActivityID })
                .HasName("PK__tmp_ms_x__8EA5844529221CFB");

            entity.Property(e => e.RoleID)
                .HasMaxLength(40)
                .IsUnicode(false);

            entity.Property(e => e.ActivityID)
                .HasMaxLength(40)
                .IsUnicode(false);
        }
    }
}
