// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class RoleUserConfiguration : IEntityTypeConfiguration<RoleUser>
    {
        public void Configure(EntityTypeBuilder<RoleUser> entity)
        {
            entity.HasKey(e => new { e.RoleID, e.UserID })
                .HasName("PK__RoleUser__5B8242F0AD89CA17");

            entity.Property(e => e.RoleID)
                .HasMaxLength(40)
                .IsUnicode(false);

            entity.Property(e => e.UserID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Role)
                .WithMany(p => p.RoleUser)
                .HasForeignKey(d => d.RoleID)
                .HasConstraintName("FK_RoleUser_Role");
        }
    }
}
