// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class RoleUnitConfiguration : IEntityTypeConfiguration<RoleUnit>
    {
        public void Configure(EntityTypeBuilder<RoleUnit> entity)
        {
            entity.HasKey(e => new { e.RoleID, e.UnitID });

            entity.Property(e => e.RoleID)
                .HasMaxLength(40)
                .IsUnicode(false);

            entity.Property(e => e.UnitID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DummyField)
                .HasMaxLength(10)
                .IsFixedLength();

            entity.HasOne(d => d.Role)
                .WithMany(p => p.RoleUnit)
                .HasForeignKey(d => d.RoleID)
                .HasConstraintName("FK_RoleUnit_Role");

            entity.HasOne(d => d.Unit)
                .WithMany(p => p.RoleUnit)
                .HasForeignKey(d => d.UnitID)
                .HasConstraintName("FK_RoleUnit_UnitStructure");
        }
    }
}
