// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class UnitStructureConfiguration : IEntityTypeConfiguration<UnitStructure>
    {
        public void Configure(EntityTypeBuilder<UnitStructure> entity)
        {
            entity.HasKey(e => e.UnitID);

            entity.Property(e => e.UnitID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Location)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('Estate')");

            entity.Property(e => e.ParentID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UnitCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UnitName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.UnitType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Parent)
                .WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentID)
                .HasConstraintName("FK_UnitStructure_UnitStructure");
        }
    }
}
