// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class UserLoginTokenConfiguration : IEntityTypeConfiguration<UserLoginToken>
    {
        public void Configure(EntityTypeBuilder<UserLoginToken> entity)
        {
            entity.HasKey(e => e.TokenID)
                .HasName("PK__UserLogi__658FEE8A13F5AA0D");

            entity.Property(e => e.TokenID)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.LastActivityDate).HasColumnType("datetime");

            entity.Property(e => e.LoginDate).HasColumnType("datetime");

            entity.Property(e => e.OriginApp)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.OriginIP)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UserID)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        }
    }
}
