// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwAMORGANIZATIONConfiguration : IEntityTypeConfiguration<vwAMORGANIZATION>
    {
        public void Configure(EntityTypeBuilder<vwAMORGANIZATION> entity)
        {
            entity.HasKey(e=>e.ID);

            entity.Property(e => e.AREAID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.GROUPID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.REGIONID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.TYPE)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        }
    }
}
