// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwAMRELATIONConfiguration : IEntityTypeConfiguration<vwAMRELATION>
    {
        public void Configure(EntityTypeBuilder<vwAMRELATION> entity)
        {
            entity.HasKey(e=>e.ID);

            entity.Property(e => e.UPDATED).HasColumnType("datetime");
        }
    }
}
