// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwAMPROPERTYConfiguration : IEntityTypeConfiguration<vwAMPROPERTY>
    {
        public void Configure(EntityTypeBuilder<vwAMPROPERTY> entity)
        {
            entity.HasKey(e=>new { e.OBJECTID,e.PROPERTYID });


            entity.Property(e => e.UPDATED).HasColumnType("datetime");

            entity.Property(e => e.VALUE)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
        }
    }
}
