// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwAMUSERConfiguration : IEntityTypeConfiguration<vwAMUSER>
    {
        public void Configure(EntityTypeBuilder<vwAMUSER> entity)
        {
            entity.HasKey(e => e.ID);

            entity.Property(e => e.EMAIL)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.LOCID)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.NIK)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.PASSWORD)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
        }
    }
}
