// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwAMRELATIONTYPEConfiguration : IEntityTypeConfiguration<vwAMRELATIONTYPE>
    {
        public void Configure(EntityTypeBuilder<vwAMRELATIONTYPE> entity)
        {
            entity.HasKey(e=>e.ID);

            

            entity.Property(e => e.ALIAS)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.DESCRIPTION)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.NAME)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.SPACE)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.UPDATED).HasColumnType("datetime");
        }
    }
}
