// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwAMOBJECTTYPEConfiguration : IEntityTypeConfiguration<vwAMOBJECTTYPE>
    {
        public void Configure(EntityTypeBuilder<vwAMOBJECTTYPE> entity)
        {
            entity.HasKey(e=>e.ID);

            entity.Property(e => e.ALIAS)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.NAME)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        }
    }
}
