// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwApprovalInboxConfiguration : IEntityTypeConfiguration<vwApprovalInbox>
    {
        public void Configure(EntityTypeBuilder<vwApprovalInbox> entity)
        {
            entity.HasKey(e => e.DocTransNo);

            

            entity.Property(e => e.ActivityID)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.ActivityName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DepartmentID)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.DocDate).HasColumnType("date");

            entity.Property(e => e.DocNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DocOwner)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DocStatus)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DocType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.EditControllerName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.FromActivityID)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.InDate).HasColumnType("datetime");

            entity.Property(e => e.IndexControllerName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");

            entity.Property(e => e.LastUpdateUser)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.UnitID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            

            entity.Property(e => e.WorkflowStatus)
                .HasMaxLength(20)
                .IsUnicode(false);
        }
    }
}
