// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwApprovalHistoryConfiguration : IEntityTypeConfiguration<vwApprovalHistory>
    {
        public void Configure(EntityTypeBuilder<vwApprovalHistory> entity)
        {
            entity.HasKey(e=>new { e.WorkflowTransactionNo,e.SequenceNo});

            

            entity.Property(e => e.ActionName)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ActionTypeID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.ActivityID)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.ActivityName)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ApprovalDate).HasColumnType("datetime");

            entity.Property(e => e.Notes)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.QueueDate).HasColumnType("datetime");

            entity.Property(e => e.UserID)
                .HasMaxLength(50)
                .IsUnicode(false);
        }
    }
}
