// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwDocumentConfiguration : IEntityTypeConfiguration<vwDocument>
    {
        public void Configure(EntityTypeBuilder<vwDocument> entity)
        {
            entity.HasKey(e=>e.DocTransNo);


            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.DocDate).HasColumnType("date");

            entity.Property(e => e.DocNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DocOwner)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DocStatus)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DocStatusText)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DocType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DocTypeName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.LastAction)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.LastActionText)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.LastActivity)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.LastActivityName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.LastApprovalDate).HasColumnType("datetime");

            entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");

            entity.Property(e => e.LastUpdateUser)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.LastUserID)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.NextActivity)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.NextActivityName)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.UnitID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        }
    }
}
