// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwDocumentBAFConfiguration : IEntityTypeConfiguration<vwDocumentBAF>
    {
        public void Configure(EntityTypeBuilder<vwDocumentBAF> entity)
        {
            entity.HasKey(e=>e.DocTransNo);


            entity.Property(e => e.DepartmentID)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.DivisionID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DocDate).HasColumnType("date");

            entity.Property(e => e.DocNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DocOwner)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DocStatus)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DocType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.FingerDate).HasColumnType("datetime");

            entity.Property(e => e.LastActivityID)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.LastActivityName)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.LastApprovalAction)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.LastApprovalActionName)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.LastApprovalDate).HasColumnType("datetime");

            entity.Property(e => e.LastApprover)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");

            entity.Property(e => e.LastUpdateUser)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ReleaseStrategy)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.StatusText)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.UnitID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.WFFlag)
                .HasMaxLength(50)
                .IsUnicode(false);
        }
    }
}
