// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwPTAForUpdateBudgetConfiguration : IEntityTypeConfiguration<vwPTAForUpdateBudget>
    {
        public void Configure(EntityTypeBuilder<vwPTAForUpdateBudget> entity)
        {
            entity.HasKey(e => e.DocTransNo);

            

            entity.Property(e => e.CJ32DocNo)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.CJ36DocNo)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.CurrentBudgetNeeds).HasColumnType("decimal(20, 0)");

            entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");

            entity.Property(e => e.LineDescription)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.ObjectNo)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.WBSElement)
                .HasMaxLength(100)
                .IsUnicode(false);
        }
    }
}
