// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwRoleMemberConfiguration : IEntityTypeConfiguration<vwRoleMember>
    {
        public void Configure(EntityTypeBuilder<vwRoleMember> entity)
        {
            entity.HasKey(e => new { e.RoleID, e.UserID });


            entity.Property(e => e.RoleID)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.UserID)
                .HasMaxLength(100)
                .IsUnicode(false);
        }
    }
}
