// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class vwUserConfiguration : IEntityTypeConfiguration<vwUser>
    {
        public void Configure(EntityTypeBuilder<vwUser> entity)
        {
            entity.HasKey(e => e.UserID);

            

            entity.Property(e => e.EmailAddress)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.EncryptedPassword)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.UserID)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        }
    }
}
