// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class WorkflowActivityConfiguration : IEntityTypeConfiguration<WorkflowActivity>
    {
        public void Configure(EntityTypeBuilder<WorkflowActivity> entity)
        {
            entity.HasKey(e => e.ActivityID)
                .HasName("PK_Activity");

            entity.Property(e => e.ActivityID)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.AMAlias)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.AMPermission)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ActivityType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.DocViewID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.WorkflowID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.DocView)
                .WithMany(p => p.WorkflowActivity)
                .HasForeignKey(d => d.DocViewID)
                .HasConstraintName("FK_WorkflowActivity_DocumentViewType");

            entity.HasOne(d => d.Workflow)
                .WithMany(p => p.WorkflowActivity)
                .HasForeignKey(d => d.WorkflowID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkflowActivity_Workflow");
        }
    }
}
