// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class WorkflowRouteConfiguration : IEntityTypeConfiguration<WorkflowRoute>
    {
        public void Configure(EntityTypeBuilder<WorkflowRoute> entity)
        {
            entity.HasKey(e => new { e.ActivityID, e.ActionTypeID, e.WFFlag });

            entity.Property(e => e.ActivityID)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.ActionTypeID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.WFFlag)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.NextActivity)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.WorkflowStatus)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ActionType)
                .WithMany(p => p.WorkflowRoute)
                .HasForeignKey(d => d.ActionTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkflowRoute_WorkflowAction");

            entity.HasOne(d => d.Activity)
                .WithMany(p => p.WorkflowRouteActivity)
                .HasForeignKey(d => d.ActivityID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkflowRoute_WorkflowActivity");

            entity.HasOne(d => d.NextActivityNavigation)
                .WithMany(p => p.WorkflowRouteNextActivityNavigation)
                .HasForeignKey(d => d.NextActivity)
                .HasConstraintName("FK_WorkflowRoute_WorkflowActivityNext");

            entity.HasOne(d => d.WorkflowStatusNavigation)
                .WithMany(p => p.WorkflowRoute)
                .HasForeignKey(d => d.WorkflowStatus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkflowRoute_DocumentStatus");
        }
    }
}
