// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class WorkflowActionConfiguration : IEntityTypeConfiguration<WorkflowAction>
    {
        public void Configure(EntityTypeBuilder<WorkflowAction> entity)
        {
            entity.HasKey(e => e.ActionTypeID);

            entity.Property(e => e.ActionTypeID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.NextApproverNotifType)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.OwnerNotifType)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.PrevApproverNotifType)
                .HasMaxLength(10)
                .IsUnicode(false);
        }
    }
}
