// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using WF.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WF.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace WF.EFCore.Data
{
    public class WorkflowTransactionConfiguration : IEntityTypeConfiguration<WorkflowTransaction>
    {
        public void Configure(EntityTypeBuilder<WorkflowTransaction> entity)
        {
            entity.HasKey(e => e.TransactionNo);

            entity.Property(e => e.Creator)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.LastActivityDate).HasColumnType("datetime");

            entity.Property(e => e.LastActivityID)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.LastStatus)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.StartActivity)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.SubmissionDate).HasColumnType("datetime");

            
            entity.Property(e => e.DocType)                
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Title)            
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.UnitID)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DepartmentID)
                .HasMaxLength(10)
                .IsUnicode(false);


            entity.Property(e => e.ReleaseStrategy)
                .HasMaxLength(8000)
                .IsUnicode(false);



            entity.Property(e => e.WorkflowID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.LastStatusNavigation)
                .WithMany(p => p.WorkflowTransaction)
                .HasForeignKey(d => d.LastStatus)
                .HasConstraintName("FK_WorkflowTransaction_DocumentStatus");

            entity.HasOne(d => d.Workflow)
                .WithMany(p => p.WorkflowTransaction)
                .HasForeignKey(d => d.WorkflowID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkflowTransaction_Workflow");


        }
    }
}
