// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMS.EFCore.Model
{
    public partial class TUPKEEPEMPLOYEE
    {
        [NotMapped()]
        public string EMPNAME { get; set; }
        [NotMapped()]
        public string EMPTYPE { get; set; }
        [NotMapped()]
        public string UNITCODE { get; set; }
        [NotMapped()]
        public string UNITNAME { get; set; }
        [NotMapped()]
        public string UOM { get; set; }
        
    }
}