// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class AutoNumberHistory
    {
        public string DocNo { get; set; }
        public string DocTypeID { get; set; }
        public DateTime DocDate { get; set; }
        public string UnitID { get; set; }
        public int SequenceNo { get; set; }
    }
}