// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class Company
    {
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string UnitId { get; set; }
        public bool? IsActive { get; set; }
    }
}