// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class Delegation
    {
        public Delegation()
        {
            DelegationDocument = new HashSet<DelegationDocument>();
        }

        public long DelegationNo { get; set; }
        public string Reason { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
        public string ClosedReason { get; set; }

        public virtual ICollection<DelegationDocument> DelegationDocument { get; set; }
    }
}