// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DelegationDocument
    {
        public long DelegationNo { get; set; }
        public long DocTransNo { get; set; }

        public virtual Delegation DelegationNoNavigation { get; set; }
        public virtual Document DocTransNoNavigation { get; set; }
    }
}