// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class Department
    {
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string CostCenter { get; set; }
        public string WBSGroup { get; set; }
        public bool? IsActive { get; set; }
    }
}