// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentType
    {
        public DocumentType()
        {
            Document = new HashSet<Document>();
            DocumentViewType = new HashSet<DocumentViewType>();
            RoleDocumentType = new HashSet<RoleDocumentType>();
            SenderUrl = string.Empty;
        }

        public string DocTypeID { get; set; }
        public string Description { get; set; }
        public string WorkflowID { get; set; }
        public string DefaultControllerName { get; set; }
        public string IndexControllerName { get; set; }
        public string ANPrefix { get; set; }
        public string ANPostFix { get; set; }
        public string ANPeriodPartition { get; set; }
        public bool ANUnitPartition { get; set; }
        public string ANNumberFormat { get; set; }
        public string ANPeriodFormat { get; set; }
        public string ANFormat { get; set; }
        public bool InternalSource { get; set; }
        public bool ExternalSource { get; set; }
        public bool IsActive { get; set; }
        public string EmailTemplateID { get; set; }
        public string AMAlias { get; set; }

        public string SenderUrl { get; set; }

        public string UITokenProcessorUrl { get; set; }
        public string UIApprovalUrl { get; set; }

        public virtual EmailContentTemplate EmailTemplate { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<DocumentViewType> DocumentViewType { get; set; }
        public virtual ICollection<RoleDocumentType> RoleDocumentType { get; set; }
    }
}