// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentTypeNotificationTemplate
    {
        public string DocTypeID { get; set; }
        public string ActionTypeID { get; set; }
        public string NotifToOwnerTemplate { get; set; }
        public string NotifToNextApproversTemplate { get; set; }
        public string NotifToPrevApproversTemplate { get; set; }
        public string NotifToOwnerEmailSubject { get; set; }
        public string NotifToNextApproversEmailSubject { get; set; }
        public string NotifToPrevApproversEmailSubject { get; set; }
    }
}