// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentPremiNonPanen
    {
        public long DocTransNo { get; set; }
        public string No { get; set; }
        public string DivisionID { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }

        public virtual Document DocTransNoNavigation { get; set; }
    }
}