// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentITRequest
    {
        public DocumentITRequest()
        {
            DocumentITRequestAppType = new HashSet<DocumentITRequestAppType>();
            DocumentITRequestChangeType = new HashSet<DocumentITRequestChangeType>();
        }

        public long DocTransNo { get; set; }
        public string Reason { get; set; }
        public int ChangePriority { get; set; }
        public int ChangeImpact { get; set; }
        public string Action { get; set; }
        public string ResourceReq { get; set; }
        public string TestPlanDesc { get; set; }
        public string RollbackDesc { get; set; }

        public virtual Document DocTransNoNavigation { get; set; }
        public virtual ICollection<DocumentITRequestAppType> DocumentITRequestAppType { get; set; }
        public virtual ICollection<DocumentITRequestChangeType> DocumentITRequestChangeType { get; set; }
    }
}