// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentPTA
    {
        public DocumentPTA()
        {
            DocumentPTADetails = new HashSet<DocumentPTADetails>();
        }

        public long DocTransNo { get; set; }
        public string PTAType { get; set; }
        public string PTAFlag { get; set; }
        public string PTAReason { get; set; }
        public decimal PTAAmmount { get; set; }
        public string CurrencyCode { get; set; }
        public string BudgetCode { get; set; }
        public string WBSElement { get; set; }
        public string CostCenter { get; set; }
        public string CostElement { get; set; }
        public string Priority { get; set; }

        public virtual Document DocTransNoNavigation { get; set; }
        public virtual ICollection<DocumentPTADetails> DocumentPTADetails { get; set; }
    }
}