// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentPTADetails
    {
        public DocumentPTADetails()
        {
            DocumentPTADetailAttachments = new HashSet<DocumentPTADetailAttachments>();
        }

        public long DocTransNo { get; set; }
        public long LineItem { get; set; }
        public string BudgetCode { get; set; }
        public string WBSElement { get; set; }
        public string CostCenter { get; set; }
        public string CostElement { get; set; }
        public decimal TotalBudget { get; set; }
        public decimal PrevRealizedBudget { get; set; }
        public decimal CurrentBudgetNeeds { get; set; }
        public string LineDescription { get; set; }
        public string CJ36DocNo { get; set; }
        public string CJ32DocNo { get; set; }
        public string LastError { get; set; }

        public virtual PTACostElement CostElementNavigation { get; set; }
        public virtual DocumentPTA DocTransNoNavigation { get; set; }
        public virtual PTAWBSElement WBSElementNavigation { get; set; }
        public virtual ICollection<DocumentPTADetailAttachments> DocumentPTADetailAttachments { get; set; }
    }
}