// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentHistory
    {
        public long DocTransNo { get; set; }
        public int SequenceNo { get; set; }
        public string Description { get; set; }
        public string UserID { get; set; }
        public DateTime? Date { get; set; }

        public virtual Document DocTransNoNavigation { get; set; }
    }
}