// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentBAFinger
    {
        public long DocTransNo { get; set; }
        public DateTime FingerDate { get; set; }
        public string DivisionID { get; set; }

        public virtual Document DocTransNoNavigation { get; set; }
    }
}