// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class Document
    {
        public Document()
        {
            DelegationDocument = new HashSet<DelegationDocument>();
            DocumentAttachment = new HashSet<DocumentAttachment>();
            DocumentBAFingerDetail = new HashSet<DocumentBAFingerDetail>();
            DocumentHistory = new HashSet<DocumentHistory>();
        }

        public long DocTransNo { get; set; }
        public string DocNo { get; set; }
        public DateTime DocDate { get; set; }
        public string DocType { get; set; }
        public string DocOwner { get; set; }
        public string DocStatus { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string UnitID { get; set; }
        public string DepartmentID { get; set; }
        public string WFFlag { get; set; }
        public long? WorkflowTransactionNo { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public string ReleaseStrategy { get; set; }
        public long? OriginalDocTransNo { get; set; }

        public virtual DocumentStatus DocumentStatus { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual UnitStructure Unit { get; set; }
        public virtual WorkflowTransaction WorkflowTransaction { get; set; }
        public virtual DocumentBAFinger DocumentBAFinger { get; set; }
        public virtual DocumentITAkses DocumentITAkses { get; set; }
        public virtual DocumentITRequest DocumentITRequest { get; set; }
        public virtual DocumentITService DocumentITService { get; set; }
        public virtual DocumentPDO DocumentPDO { get; set; }
        public virtual DocumentPTA DocumentPTA { get; set; }
        public virtual DocumentPremiNonPanen DocumentPremiNonPanen { get; set; }
        public virtual ICollection<DelegationDocument> DelegationDocument { get; set; }
        public virtual ICollection<DocumentAttachment> DocumentAttachment { get; set; }
        public virtual ICollection<DocumentBAFingerDetail> DocumentBAFingerDetail { get; set; }
        public virtual ICollection<DocumentHistory> DocumentHistory { get; set; }
    }
}