// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentITService
    {
        public long DocTransNo { get; set; }
        public string Type { get; set; }
        public string ToolType { get; set; }
        public string DeviceSN { get; set; }
        public string AssetNo { get; set; }
        public DateTime? CheckingDate { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public bool Warranty { get; set; }
        public string DeviceOwner { get; set; }
        public string Specification { get; set; }
        public string CheckingResult { get; set; }
        public string ITOfficerRec { get; set; }
        public string ITInfraRec { get; set; }
        public string ITAssetManagerRec { get; set; }
        public string ITAssetManagerActionRec { get; set; }
        public string PRNo { get; set; }

        public virtual Document DocTransNoNavigation { get; set; }
    }
}