// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentPDO
    {
        public DocumentPDO()
        {
            DocumentPDODetails = new HashSet<DocumentPDODetails>();
        }

        public long DocTransNo { get; set; }
        public DateTime Period { get; set; }

        public virtual Document DocTransNoNavigation { get; set; }
        public virtual ICollection<DocumentPDODetails> DocumentPDODetails { get; set; }
    }
}