// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentBAFingerDetail
    {
        public long DocTransNo { get; set; }
        public DateTime FingerDate { get; set; }
        public string EmployeeID { get; set; }
        public string NIK { get; set; }
        public string EmployeeName { get; set; }
        public string MandorID { get; set; }
        public string MandorName { get; set; }
        public string DivisionID { get; set; }
        public string Card { get; set; }
        public string Reason { get; set; }
        public bool Status { get; set; }

        public virtual Document DocTransNoNavigation { get; set; }
    }
}