// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentPTADetailAttachments
    {
        public long DocTransNo { get; set; }
        public long LineItem { get; set; }
        public long FileID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public long FileSize { get; set; }
        public string Description { get; set; }

        public virtual DocumentPTADetails DocumentPTADetails { get; set; }
        public virtual File File { get; set; }
    }
}