// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentAccessToken
    {
        public string TokenID { get; set; }
        public string UserID { get; set; }
        public long DocTransNo { get; set; }
        public string AccessType { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ExpiredDate { get; set; }
        public bool IsActive { get; set; }
        public string SessionID { get; set; }
        public string To { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool? IsHTML { get; set; }
        public string Status { get; set; }
        public string LastErrorText { get; set; }
        public DateTime? SentDate { get; set; }
    }
}