// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentITAkses
    {
        public long DocTransNo { get; set; }
        public string NIK { get; set; }
        public string Name { get; set; }
        public string Grade { get; set; }
        public string Position { get; set; }
        public string AccessTypes { get; set; }
        public string Email { get; set; }
        public string Internet { get; set; }
        public string Printer { get; set; }
        public string Telp { get; set; }

        public virtual Document DocTransNoNavigation { get; set; }
    }
}