// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentViewType
    {
        public DocumentViewType()
        {
            WorkflowActivity = new HashSet<WorkflowActivity>();
        }

        public string DocViewID { get; set; }
        public string DocViewName { get; set; }
        public string Description { get; set; }
        public string DocTypeID { get; set; }
        public string EditControllerName { get; set; }
        public string IndexControllerName { get; set; }
        public bool IsActive { get; set; }
        public string ViewDocumentName { get; set; }

        public virtual DocumentType DocType { get; set; }
        public virtual ICollection<WorkflowActivity> WorkflowActivity { get; set; }
    }
}