// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentStatus
    {
        public DocumentStatus()
        {
            Document = new HashSet<Document>();
            WorkflowRoute = new HashSet<WorkflowRoute>();
            WorkflowTransaction = new HashSet<WorkflowTransaction>();
            WorkflowTransactionHistory = new HashSet<WorkflowTransactionHistory>();
        }

        public string StatusID { get; set; }
        public string Description { get; set; }
        public string StatusType { get; set; }

        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<WorkflowRoute> WorkflowRoute { get; set; }
        public virtual ICollection<WorkflowTransaction> WorkflowTransaction { get; set; }
        public virtual ICollection<WorkflowTransactionHistory> WorkflowTransactionHistory { get; set; }
    }
}