// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentITRequestAppType
    {
        public long DocTransNo { get; set; }
        public string AppType { get; set; }

        public virtual ITRequestAppType AppTypeNavigation { get; set; }
        public virtual DocumentITRequest DocTransNoNavigation { get; set; }
    }
}