// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class DocumentITRequestChangeType
    {
        public long DocTransNo { get; set; }
        public string ChangeType { get; set; }

        public virtual ITRequestChangeType ChangeTypeNavigation { get; set; }
        public virtual DocumentITRequest DocTransNoNavigation { get; set; }
    }
}