// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class EmailContentTemplate
    {
        public EmailContentTemplate()
        {
            DocumentType = new HashSet<DocumentType>();
        }

        public string TemplateID { get; set; }
        public bool IsHTML { get; set; }
        public string EmailContent { get; set; }

        public virtual ICollection<DocumentType> DocumentType { get; set; }
    }
}