// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class Employee
    {
        public string NIK { get; set; }
        public string Name { get; set; }
        public string DepartmentId { get; set; }
        public string Grade { get; set; }
        public string Position { get; set; }
        public string UnitID { get; set; }
    }
}