// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class File
    {
        public File()
        {
            DocumentAttachment = new HashSet<DocumentAttachment>();
            DocumentPDODetailAttachments = new HashSet<DocumentPDODetailAttachments>();
            DocumentPTADetailAttachments = new HashSet<DocumentPTADetailAttachments>();
        }

        public long FileID { get; set; }
        public byte[] FileContents { get; set; }
        public DateTime? UploadDate { get; set; }

        public virtual ICollection<DocumentAttachment> DocumentAttachment { get; set; }
        public virtual ICollection<DocumentPDODetailAttachments> DocumentPDODetailAttachments { get; set; }
        public virtual ICollection<DocumentPTADetailAttachments> DocumentPTADetailAttachments { get; set; }
    }
}