// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class FileAttachmentFromPTA
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public byte[] Contents { get; set; }
        public string MimeType { get; set; }
        public int FileSize { get; set; }
        public string FileName { get; set; }
        public int? AttachmentGroupID { get; set; }
    }
}