// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class ITRequestChangeType
    {
        public ITRequestChangeType()
        {
            DocumentITRequestChangeType = new HashSet<DocumentITRequestChangeType>();
        }

        public string ChangeTypeID { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<DocumentITRequestChangeType> DocumentITRequestChangeType { get; set; }
    }
}