// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class ITRequestAppType
    {
        public ITRequestAppType()
        {
            DocumentITRequestAppType = new HashSet<DocumentITRequestAppType>();
        }

        public string AppTypeID { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<DocumentITRequestAppType> DocumentITRequestAppType { get; set; }
    }
}