// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class PDOVendor
    {
        public PDOVendor()
        {
            DocumentPDODetails = new HashSet<DocumentPDODetails>();
        }

        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string AccountNo { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public bool? IsActive { get; set; }
        public string CompanyCode { get; set; }

        public virtual ICollection<DocumentPDODetails> DocumentPDODetails { get; set; }
    }
}