// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class PTAType
    {
        public string PTATypeID { get; set; }
        public string Description { get; set; }
        public string PTAFlag { get; set; }
        public bool? WBSRelated { get; set; }
        public bool CostElementRelated { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
    }
}