// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class PTAWBSElement_temp
    {
        public string SessionId { get; set; }
        public string ElementId { get; set; }
        public string Description { get; set; }
        public string UnitID { get; set; }
        public string Flag { get; set; }
        public string ObjectNo { get; set; }
        public string ProjectType { get; set; }
        public bool IsActive { get; set; }
    }
}