// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class PTAWBSElement
    {
        public PTAWBSElement()
        {
            DocumentPTADetails = new HashSet<DocumentPTADetails>();
        }

        public string ElementId { get; set; }
        public string Description { get; set; }
        public string UnitID { get; set; }
        public string Flag { get; set; }
        public string ObjectNo { get; set; }
        public string ProjectType { get; set; }
        public bool? IsActive { get; set; }

        public virtual UnitStructure Unit { get; set; }
        public virtual ICollection<DocumentPTADetails> DocumentPTADetails { get; set; }
    }
}