// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class ReportDocType
    {
        public string ReportName { get; set; }
        public string ReportDesc { get; set; }
        public string DocType { get; set; }
        public bool? IsActive { get; set; }
    }
}