// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class RoleActivity
    {
        public string RoleID { get; set; }
        public string ActivityID { get; set; }
        public bool IsApprover { get; set; }
    }
}