// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class RoleUnit
    {
        public string RoleID { get; set; }
        public string UnitID { get; set; }
        public string DummyField { get; set; }

        public virtual Role Role { get; set; }
        public virtual UnitStructure Unit { get; set; }
    }
}