// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class Role
    {
        public Role()
        {
            RoleDocumentType = new HashSet<RoleDocumentType>();
            RoleUnit = new HashSet<RoleUnit>();
            RoleUser = new HashSet<RoleUser>();
        }

        public string RoleID { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<RoleDocumentType> RoleDocumentType { get; set; }
        public virtual ICollection<RoleUnit> RoleUnit { get; set; }
        public virtual ICollection<RoleUser> RoleUser { get; set; }
    }
}