// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class RoleDocumentType
    {
        public string RoleID { get; set; }
        public string DocTypeID { get; set; }

        public virtual DocumentType DocType { get; set; }
        public virtual Role Role { get; set; }
    }
}