// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class UnitStructure
    {
        public UnitStructure()
        {
            Document = new HashSet<Document>();
            InverseParent = new HashSet<UnitStructure>();
            PTAWBSElement = new HashSet<PTAWBSElement>();
            RoleUnit = new HashSet<RoleUnit>();
        }

        public string UnitID { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public string UnitType { get; set; }
        public string ParentID { get; set; }
        public bool IsActive { get; set; }
        public string Location { get; set; }

        public virtual UnitStructure Parent { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<UnitStructure> InverseParent { get; set; }
        public virtual ICollection<PTAWBSElement> PTAWBSElement { get; set; }
        public virtual ICollection<RoleUnit> RoleUnit { get; set; }
    }
}