// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class UserLoginToken
    {
        public string TokenID { get; set; }
        public string UserID { get; set; }
        public DateTime LoginDate { get; set; }
        public DateTime LastActivityDate { get; set; }
        public int Expiration { get; set; }
        public string OriginIP { get; set; }
        public string OriginApp { get; set; }
        public bool IsExpired { get; set; }
    }
}