// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwAMUSER
    {
        public int ID { get; set; }
        public string PASSWORD { get; set; }
        public string NIK { get; set; }
        public string EMAIL { get; set; }
        public string LOCID { get; set; }
    }
}