// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwAMRELATION
    {
        public int ID { get; set; }
        public int TYPEID { get; set; }
        public int PARENTID { get; set; }
        public int CHILDID { get; set; }
        public bool ACTIVE { get; set; }
        public DateTime UPDATED { get; set; }
    }
}