// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwAMORGANIZATION
    {
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string GROUPID { get; set; }
        public string REGIONID { get; set; }
        public string AREAID { get; set; }
    }
}