// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwAMPROPERTY
    {
        public int OBJECTID { get; set; }
        public int PROPERTYID { get; set; }
        public string VALUE { get; set; }
        public DateTime UPDATED { get; set; }
    }
}