// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwAMRELATIONTYPE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ALIAS { get; set; }
        public string DESCRIPTION { get; set; }
        public string SPACE { get; set; }
        public DateTime UPDATED { get; set; }
    }
}