// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwApprovalInbox
    {
        public long DocTransNo { get; set; }
        public string DocNo { get; set; }
        public DateTime DocDate { get; set; }
        public string DocType { get; set; }
        public string DocOwner { get; set; }
        public string DocStatus { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string UnitID { get; set; }
        public string DepartmentID { get; set; }
        public long? WorkflowTransactionNo { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public int SequenceNo { get; set; }
        public string ActivityID { get; set; }
        public string FromActivityID { get; set; }
        public string WorkflowStatus { get; set; }
        public DateTime? InDate { get; set; }
        public string ActivityName { get; set; }
        public string EditControllerName { get; set; }
        public string IndexControllerName { get; set; }
        public string DocStatusText { get; set; }
    }
}