// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwApprovalHistory
    {
        public long DocTransNo { get; set; }
        public long? WorkflowTransactionNo { get; set; }
        public string ActivityID { get; set; }
        public string ActivityName { get; set; }
        public string ActionTypeID { get; set; }
        public string ActionName { get; set; }
        public string UserID { get; set; }
        public string Notes { get; set; }
        public DateTime? ApprovalDate { get; set; }
        public DateTime? QueueDate { get; set; }

        public int SequenceNo { get; set; }
    }
}