// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwDocumentBAF
    {
        public long DocTransNo { get; set; }
        public string DocNo { get; set; }
        public DateTime DocDate { get; set; }
        public string DocType { get; set; }
        public string DocOwner { get; set; }
        public string DocStatus { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string UnitID { get; set; }
        public string DepartmentID { get; set; }
        public string WFFlag { get; set; }
        public long? WorkflowTransactionNo { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public string ReleaseStrategy { get; set; }
        public long? OriginalDocTransNo { get; set; }
        public DateTime FingerDate { get; set; }
        public string DivisionID { get; set; }
        public string StatusText { get; set; }
        public DateTime? LastApprovalDate { get; set; }
        public string LastApprovalActionName { get; set; }
        public string LastApprovalAction { get; set; }
        public string LastApprover { get; set; }
        public string LastActivityID { get; set; }
        public string LastActivityName { get; set; }
    }
}