// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwDocument
    {
        public long DocTransNo { get; set; }
        public string DocNo { get; set; }
        public DateTime DocDate { get; set; }
        public string DocType { get; set; }
        public string DocOwner { get; set; }
        public string DocStatus { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string UnitID { get; set; }
        public long? WorkflowTransactionNo { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public string DocTypeName { get; set; }
        public string DocStatusText { get; set; }
        public int? ApprovalSequenceNo { get; set; }
        public DateTime? LastApprovalDate { get; set; }
        public string LastActivity { get; set; }
        public string LastActivityName { get; set; }
        public string LastUserID { get; set; }
        public string LastAction { get; set; }
        public string LastActionText { get; set; }
        public string NextActivity { get; set; }
        public string NextActivityName { get; set; }
    }
}