// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwPDOApprovedJournal
    {
        public long DocTransNo { get; set; }
        public long LineItem { get; set; }
        public string VendorCode { get; set; }
        public string SAPJournalNo { get; set; }
        public string JobDesc { get; set; }
        public string AccountNo { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public decimal Amount { get; set; }
        public decimal ApprovedAmount { get; set; }
        public DateTime? PaidDate { get; set; }
        public short Status { get; set; }
        public string LastUpdateBy { get; set; }
        public DateTime LastUpdateDate { get; set; }
        public string CompanyCode { get; set; }
    }
}