// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwPTAForUpdateBudget
    {
        public long DocTransNo { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public long LineItem { get; set; }
        public string WBSElement { get; set; }
        public string LineDescription { get; set; }
        public decimal CurrentBudgetNeeds { get; set; }
        public string ObjectNo { get; set; }
        public string CJ32DocNo { get; set; }
        public string CJ36DocNo { get; set; }
    }
}