// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwRoleMember
    {
        public string RoleID { get; set; }
        public string UserID { get; set; }
    }
}