// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class vwUser
    {
        public string UserID { get; set; }
        public string FullName { get; set; }
        public string EncryptedPassword { get; set; }
        public string Title { get; set; }
        public string EmailAddress { get; set; }
        public bool? IsAdmin { get; set; }
        public bool IsActive { get; set; }
        public bool? IsLocked { get; set; }
    }
}