// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class WorkflowTransactionHistory
    {
        public long TransactionNo { get; set; }
        public int SequenceNo { get; set; }
        public string ActivityID { get; set; }
        public string FromActivityID { get; set; }
        public string FromActionID { get; set; }
        public string FromUserID { get; set; }
        public string NextActivityID { get; set; }
        public string ActionTypeID { get; set; }
        public string UserID { get; set; }
        public string Notes { get; set; }
        public string WorkflowStatus { get; set; }
        public DateTime? InDate { get; set; }
        public DateTime? OutDate { get; set; }

        public virtual WorkflowAction ActionType { get; set; }
        public virtual WorkflowActivity Activity { get; set; }
        public virtual WorkflowActivity FromActivity { get; set; }
        public virtual WorkflowActivity NextActivity { get; set; }
        public virtual WorkflowTransaction TransactionNoNavigation { get; set; }
        public virtual DocumentStatus WorkflowStatusNavigation { get; set; }
    }
}