// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class WorkflowActivity
    {
        public WorkflowActivity()
        {
            WorkflowRouteActivity = new HashSet<WorkflowRoute>();
            WorkflowRouteNextActivityNavigation = new HashSet<WorkflowRoute>();
            WorkflowTransactionHistoryActivity = new HashSet<WorkflowTransactionHistory>();
            WorkflowTransactionHistoryFromActivity = new HashSet<WorkflowTransactionHistory>();
            WorkflowTransactionHistoryNextActivity = new HashSet<WorkflowTransactionHistory>();
        }

        public string ActivityID { get; set; }
        public string WorkflowID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DocViewID { get; set; }
        public string ActivityType { get; set; }
        public string AMPermission { get; set; }
        public bool IsActive { get; set; }
        public string AMAlias { get; set; }

        public virtual DocumentViewType DocView { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<WorkflowRoute> WorkflowRouteActivity { get; set; }
        public virtual ICollection<WorkflowRoute> WorkflowRouteNextActivityNavigation { get; set; }
        public virtual ICollection<WorkflowTransactionHistory> WorkflowTransactionHistoryActivity { get; set; }
        public virtual ICollection<WorkflowTransactionHistory> WorkflowTransactionHistoryFromActivity { get; set; }
        public virtual ICollection<WorkflowTransactionHistory> WorkflowTransactionHistoryNextActivity { get; set; }
    }
}