// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WF.EFCore.Models
{
    public enum EActionType 
    { 
        NextActivity=0,
        Reject,
        Revision,
        FirstSubmit
    }
    public partial class WorkflowAction
    {
        public WorkflowAction()
        {
            WorkflowRoute = new HashSet<WorkflowRoute>();
            WorkflowTransactionHistory = new HashSet<WorkflowTransactionHistory>();
        }

        public string ActionTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ActionType { get; set; }
        public bool RequireApprovalNotes { get; set; }
        public bool SendNotifToOwner { get; set; }
        public string OwnerNotifType { get; set; }
        public bool SendNotifToNextApprovers { get; set; }
        public string NextApproverNotifType { get; set; }
        public bool SendNotifToPrevApprovers { get; set; }
        public string PrevApproverNotifType { get; set; }

        public virtual ICollection<WorkflowRoute> WorkflowRoute { get; set; }
        public virtual ICollection<WorkflowTransactionHistory> WorkflowTransactionHistory { get; set; }

        [NotMapped()]
        public EActionType EActionType 
        { 
            get 
            {

                if (ActionType.Equals("N"))
                    return EActionType.NextActivity;
                if (ActionType.Equals("R1"))
                    return EActionType.Reject;
                if (ActionType.Equals("R2"))
                    return EActionType.Revision;
                if (ActionType.Equals("FS"))
                    return EActionType.FirstSubmit;
                return EActionType.NextActivity;
            }
            set 
            {
                switch (value)
                {
                    case EActionType.NextActivity:
                        ActionType = "N";
                        break;
                    case EActionType.Reject:
                        ActionType = "R1";
                        break;
                    case EActionType.Revision:
                        ActionType = "R2";
                        break;
                    case EActionType.FirstSubmit:
                        ActionType = "FS";
                        break;
                    default:
                        ActionType = "N";
                        break;
                }
            }
        }
    }
}