// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class WorkflowRoute
    {
        public string ActivityID { get; set; }
        public string ActionTypeID { get; set; }
        public string WFFlag { get; set; }
        public string NextActivity { get; set; }
        public string WorkflowStatus { get; set; }

        public virtual WorkflowAction ActionType { get; set; }
        public virtual WorkflowActivity Activity { get; set; }
        public virtual WorkflowActivity NextActivityNavigation { get; set; }
        public virtual DocumentStatus WorkflowStatusNavigation { get; set; }
    }
}