// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class Workflow
    {
        public Workflow()
        {
            DocumentType = new HashSet<DocumentType>();
            WorkflowActivity = new HashSet<WorkflowActivity>();
            WorkflowTransaction = new HashSet<WorkflowTransaction>();
        }

        public string WorkflowID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public bool IsActive { get; set; }
        public string AMAlias { get; set; }

        public virtual ICollection<DocumentType> DocumentType { get; set; }
        public virtual ICollection<WorkflowActivity> WorkflowActivity { get; set; }
        public virtual ICollection<WorkflowTransaction> WorkflowTransaction { get; set; }
    }
}