// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WF.EFCore.Models
{
    public partial class WorkflowTransaction
    {
        public WorkflowTransaction()
        {
            Document = new HashSet<Document>();
            WorkflowTransactionHistory = new HashSet<WorkflowTransactionHistory>();
        }

        public long TransactionNo { get; set; }
        public string WorkflowID { get; set; }
        public string Creator { get; set; }
        public string StartActivity { get; set; }
        public DateTime SubmissionDate { get; set; }
        public string LastStatus { get; set; }
        public string LastActivityID { get; set; }
        public DateTime? LastActivityDate { get; set; }

        public string DocType { get; set; }
        
        public string Title { get; set; }        
        public string UnitID { get; set; }
        public string DepartmentID { get; set; }
        public string ReleaseStrategy { get; set; }

        public virtual DocumentStatus LastStatusNavigation { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<WorkflowTransactionHistory> WorkflowTransactionHistory { get; set; }
    }
}