// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AM.EFCore.Models
{
    public partial class AMOBJECTTYPE
    {
        public AMOBJECTTYPE()
        {
            AMOBJECT = new HashSet<AMOBJECT>();
        }

        public short ID { get; set; }
        public string NAME { get; set; }
        public string ALIAS { get; set; }

        public virtual ICollection<AMOBJECT> AMOBJECT { get; set; }
    }
}