// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AM.EFCore.Models
{
    public partial class AMOBJECT
    {
        public AMOBJECT()
        {
            AMPROPERTYOBJECT = new HashSet<AMPROPERTY>();
            AMPROPERTYPROPERTY = new HashSet<AMPROPERTY>();
            AMRELATIONCHILD = new HashSet<AMRELATION>();
            AMRELATIONPARENT = new HashSet<AMRELATION>();
        }

        public int ID { get; set; }
        public string NAME { get; set; }
        public string ALIAS { get; set; }
        public string DESCRIPTION { get; set; }
        public short TYPEID { get; set; }
        public bool ACTIVE { get; set; }
        public DateTime VALIDFROM { get; set; }
        public DateTime VALIDTO { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual AMOBJECTTYPE TYPE { get; set; }
        public virtual AMUSER AMUSER { get; set; }
        public virtual ICollection<AMPROPERTY> AMPROPERTYOBJECT { get; set; }
        public virtual ICollection<AMPROPERTY> AMPROPERTYPROPERTY { get; set; }
        public virtual ICollection<AMRELATION> AMRELATIONCHILD { get; set; }
        public virtual ICollection<AMRELATION> AMRELATIONPARENT { get; set; }
    }
}