// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AM.EFCore.Models
{
    public partial class AMPROPERTY
    {
        public int OBJECTID { get; set; }
        public int PROPERTYID { get; set; }
        public string VALUE { get; set; }
        public DateTime VALIDFROM { get; set; }
        public DateTime VALIDTO { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual AMOBJECT OBJECT { get; set; }
        public virtual AMOBJECT PROPERTY { get; set; }
    }
}