// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AM.EFCore.Models
{
    public partial class AMRELATIONTYPE
    {
        public AMRELATIONTYPE()
        {
            AMRELATION = new HashSet<AMRELATION>();
        }

        public int ID { get; set; }
        public string NAME { get; set; }
        public string ALIAS { get; set; }
        public string DESCRIPTION { get; set; }
        public string SPACE { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual ICollection<AMRELATION> AMRELATION { get; set; }
    }
}