// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AM.EFCore.Models
{
    public partial class AMRELATION
    {
        public int ID { get; set; }
        public int TYPEID { get; set; }
        public int PARENTID { get; set; }
        public int CHILDID { get; set; }
        public bool ACTIVE { get; set; }
        public DateTime VALIDFROM { get; set; }
        public DateTime VALIDTO { get; set; }
        public DateTime UPDATED { get; set; }

        public virtual AMOBJECT CHILD { get; set; }
        public virtual AMOBJECT PARENT { get; set; }
        public virtual AMRELATIONTYPE TYPE { get; set; }
    }
}