// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AM.EFCore.Models
{
    public partial class AMUSER
    {
        public int ID { get; set; }
        public string PASSWORD { get; set; }
        public DateTime PASSEXPIRED { get; set; }
        public string NIK { get; set; }
        public string EMAIL { get; set; }
        public string LOCID { get; set; }
        public short INVALID { get; set; }
        public bool LOCKED { get; set; }

        public virtual AMOBJECT IDNavigation { get; set; }
    }
}