// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AM.EFCore.Models
{
    public partial class AMUSERLOCATION
    {
        public int USERID { get; set; }
        public string LOCID { get; set; }
        public DateTime VALIDFROM { get; set; }
        public DateTime VALIDTO { get; set; }
    }
}