// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AM.EFCore.Models
{
    public partial class VAMPROPERTYVALID
    {
        public int OBJECTID { get; set; }
        public string OBJECTNAME { get; set; }
        public string OBJECTALIAS { get; set; }
        public DateTime? OBJECTVALIDFROM { get; set; }
        public DateTime? OBJECTVALIDTO { get; set; }
        public int PROPERTYID { get; set; }
        public string PROPERTYNAME { get; set; }
        public string PROPERTYALIAS { get; set; }
        public DateTime? PROPERTYVALIDFROM { get; set; }
        public DateTime? PROPERTYVALIDTO { get; set; }
        public string VALUE { get; set; }
        public DateTime VALUEVALIDFROM { get; set; }
        public DateTime VALUEVALIDTO { get; set; }
        public DateTime UPDATED { get; set; }
    }
}