// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AM.EFCore.Models
{
    public partial class VAMRELATION
    {
        public int ID { get; set; }
        public int PARENTID { get; set; }
        public string PARENTNAME { get; set; }
        public string PARENTALIAS { get; set; }
        public DateTime? PARENTVALIDFROM { get; set; }
        public DateTime? PARENTVALIDTO { get; set; }
        public int CHILDID { get; set; }
        public string CHILDNAME { get; set; }
        public string CHILDALIAS { get; set; }
        public DateTime? CHILDVALIDFROM { get; set; }
        public DateTime? CHILDVALIDTO { get; set; }
        public int RELATIONID { get; set; }
        public string RELATIONNAME { get; set; }
        public string RELATIONALIAS { get; set; }
        public string RELATIONSPACE { get; set; }
        public DateTime RELATIONVALIDFROM { get; set; }
        public DateTime RELATIONVALIDTO { get; set; }
        public DateTime UPDATED { get; set; }
        public bool ACTIVE { get; set; }
    }
}