// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using PMS.Shared.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AM.EFCore.Models
{
    public partial class WebSession
    {
        public string Token { get; set; }
        public DateTime LastAccess { get; set; }
        public bool ForResetPassword { get; set; }        
        public int LifeTimeInSeconds { get; set; }
        public DateTime? ExpiredDate { get; set; }
        public string Password { get; set; }

        [NotMapped()]
        public DecodedToken DecodedToken { get; set; }
    }
}