// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace FP.EFCore.Model
{
    public partial class MEMPLOYEEFP
    {
        public string EMPID { get; set; }
        public string EMPCODE { get; set; }
        public string UNITCODE { get; set; }
        public byte[] FOTO { get; set; }
        public byte[] FP1 { get; set; }
        public byte[] FP2 { get; set; }
        public byte[] FP3 { get; set; }
        public string STATUS { get; set; }
        public bool? ISMASTER { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime CREATED { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime UPDATED { get; set; }
    }
}