// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;


namespace AM.EFCore.Data
{
    public partial class AMContextBase : DbContext
    {
        private string _connectionString;
        public string ConnectionString { get { return _connectionString; } }

        public AMContextBase(DbContextOptions options)
           : base(options)
        {
            ReadOptions(options);
        }



        private void ReadOptions(DbContextOptions options)
        {
            foreach (var extension in options.Extensions)
            {
                if (extension.GetType() == typeof(Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerOptionsExtension))
                {
                    _connectionString = ((Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerOptionsExtension)extension).ConnectionString;
                    break;
                }
            }
        }

        public virtual DbSet<AMUSERLOCATION> AMUSERLOCATION { get; set; }
        public virtual DbSet<AMOBJECT> AMOBJECT { get; set; }
        public virtual DbSet<AMOBJECTTYPE> AMOBJECTTYPE { get; set; }
        public virtual DbSet<AMORGANIZATION> AMORGANIZATION { get; set; }
        public virtual DbSet<AMPROPERTY> AMPROPERTY { get; set; }
        public virtual DbSet<AMRELATION> AMRELATION { get; set; }
        public virtual DbSet<AMRELATIONTYPE> AMRELATIONTYPE { get; set; }
        public virtual DbSet<AMUSER> AMUSER { get; set; }
        public virtual DbSet<VAMPERMISSIONALL> VAMPERMISSIONALL { get; set; }
        public virtual DbSet<VAMPERMISSIONALLVALID> VAMPERMISSIONALLVALID { get; set; }
        public virtual DbSet<VAMPROPERTY> VAMPROPERTY { get; set; }
        public virtual DbSet<VAMPROPERTYVALID> VAMPROPERTYVALID { get; set; }
        public virtual DbSet<VAMRELATION> VAMRELATION { get; set; }
        public virtual DbSet<VAMRELATIONMEMBERSHIP> VAMRELATIONMEMBERSHIP { get; set; }
        public virtual DbSet<VAMRELATIONORGANIZATIONVALID> VAMRELATIONORGANIZATIONVALID { get; set; }
        public virtual DbSet<VAMUSER> VAMUSER { get; set; }

        public virtual DbSet<WebSession> WebSession { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new AMOBJECTConfiguration());
            modelBuilder.ApplyConfiguration(new AMOBJECTTYPEConfiguration());
            modelBuilder.ApplyConfiguration(new AMORGANIZATIONConfiguration());
            modelBuilder.ApplyConfiguration(new AMPROPERTYConfiguration());
            modelBuilder.ApplyConfiguration(new AMRELATIONConfiguration());
            modelBuilder.ApplyConfiguration(new AMRELATIONTYPEConfiguration());
            modelBuilder.ApplyConfiguration(new AMUSERConfiguration());
            modelBuilder.ApplyConfiguration(new VAMPERMISSIONALLConfiguration());
            modelBuilder.ApplyConfiguration(new VAMPERMISSIONALLVALIDConfiguration());
            modelBuilder.ApplyConfiguration(new VAMPROPERTYConfiguration());
            modelBuilder.ApplyConfiguration(new VAMPROPERTYVALIDConfiguration());
            modelBuilder.ApplyConfiguration(new VAMRELATIONConfiguration());
            modelBuilder.ApplyConfiguration(new VAMRELATIONMEMBERSHIPConfiguration());
            modelBuilder.ApplyConfiguration(new VAMRELATIONORGANIZATIONVALIDConfiguration());
            modelBuilder.ApplyConfiguration(new VAMUSERConfiguration());
            modelBuilder.ApplyConfiguration(new WebSessionConfiguration());
            modelBuilder.ApplyConfiguration(new AMUSERLOCATIONConfiguration());


            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }


    
}
