// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class AMOBJECTTYPEConfiguration : IEntityTypeConfiguration<AMOBJECTTYPE>
    {
        public void Configure(EntityTypeBuilder<AMOBJECTTYPE> entity)
        {
            entity.Property(e => e.ID).ValueGeneratedNever();

            entity.Property(e => e.ALIAS)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.NAME)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        }
    }
}
