// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class AMOBJECTConfiguration : IEntityTypeConfiguration<AMOBJECT>
    {
        public void Configure(EntityTypeBuilder<AMOBJECT> entity)
        {
            entity.Property(e => e.ID).ValueGeneratedNever();

            entity.Property(e => e.ALIAS)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.DESCRIPTION)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.NAME)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.UPDATED).HasColumnType("datetime");

            entity.Property(e => e.VALIDFROM)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(((1)/(1))/(90))");

            entity.Property(e => e.VALIDTO)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(((1)/(1))/(90))");

            entity.HasOne(d => d.TYPE)
                .WithMany(p => p.AMOBJECT)
                .HasForeignKey(d => d.TYPEID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AMOBJECT_AMOBJECTTYPE");
        }
    }
}
