// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class AMORGANIZATIONConfiguration : IEntityTypeConfiguration<AMORGANIZATION>
    {
        public void Configure(EntityTypeBuilder<AMORGANIZATION> entity)
        {
            entity.Property(e => e.ID).ValueGeneratedNever();

            entity.Property(e => e.AREAID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.GROUPID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.REGIONID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.TYPE)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        }
    }
}
