// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class AMPROPERTYConfiguration : IEntityTypeConfiguration<AMPROPERTY>
    {
        public void Configure(EntityTypeBuilder<AMPROPERTY> entity)
        {
            entity.HasKey(e => new { e.OBJECTID, e.PROPERTYID });

            entity.Property(e => e.UPDATED).HasColumnType("datetime");

            entity.Property(e => e.VALIDFROM)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(((1)/(1))/(90))");

            entity.Property(e => e.VALIDTO)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(((1)/(1))/(90))");

            entity.Property(e => e.VALUE)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.OBJECT)
                .WithMany(p => p.AMPROPERTYOBJECT)
                .HasForeignKey(d => d.OBJECTID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AMPROPERTY_AMOBJECT");

            entity.HasOne(d => d.PROPERTY)
                .WithMany(p => p.AMPROPERTYPROPERTY)
                .HasForeignKey(d => d.PROPERTYID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AMPROPERTY_AMOBJECT1");
        }
    }
}
