// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class AMRELATIONConfiguration : IEntityTypeConfiguration<AMRELATION>
    {
        public void Configure(EntityTypeBuilder<AMRELATION> entity)
        {
            entity.Property(e => e.ID).ValueGeneratedNever();

            entity.Property(e => e.UPDATED).HasColumnType("datetime");

            entity.Property(e => e.VALIDFROM)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(((1)/(1))/(90))");

            entity.Property(e => e.VALIDTO)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(((1)/(1))/(90))");

            entity.HasOne(d => d.CHILD)
                .WithMany(p => p.AMRELATIONCHILD)
                .HasForeignKey(d => d.CHILDID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AMRELATION_AMOBJECT1");

            entity.HasOne(d => d.PARENT)
                .WithMany(p => p.AMRELATIONPARENT)
                .HasForeignKey(d => d.PARENTID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AMRELATION_AMOBJECT");

            entity.HasOne(d => d.TYPE)
                .WithMany(p => p.AMRELATION)
                .HasForeignKey(d => d.TYPEID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AMRELATION_AMRELATIONTYPE");
        }
    }
}
