// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class AMUSERConfiguration : IEntityTypeConfiguration<AMUSER>
    {
        public void Configure(EntityTypeBuilder<AMUSER> entity)
        {
            entity.Property(e => e.ID).ValueGeneratedNever();

            entity.Property(e => e.EMAIL)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.LOCID)
                .IsRequired()
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.NIK)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.PASSEXPIRED)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(((1)/(1))/(90))");

            entity.Property(e => e.PASSWORD)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.IDNavigation)
                .WithOne(p => p.AMUSER)
                .HasForeignKey<AMUSER>(d => d.ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AMUSER_AMOBJECT");
        }
    }
}
