// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class AMUSERLOCATIONConfiguration : IEntityTypeConfiguration<AMUSERLOCATION>
    {
        public void Configure(EntityTypeBuilder<AMUSERLOCATION> entity)
        {
            entity.HasKey(e => new { e.USERID, e.LOCID });

            entity.Property(e => e.LOCID)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.VALIDFROM)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(((1900)-(1))-(1))");

            entity.Property(e => e.VALIDTO)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(((1900)-(1))-(1))");
        }
    }
}
