// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class VAMPERMISSIONALLConfiguration : IEntityTypeConfiguration<VAMPERMISSIONALL>
    {
        public void Configure(EntityTypeBuilder<VAMPERMISSIONALL> entity)
        {
            entity.HasKey(e => new { e.ID,e.PARENTID,e.CHILDID,e.RELATIONID});
            entity.Property(e => e.CHILDALIAS)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.CHILDNAME)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.CHILDVALIDFROM).HasColumnType("datetime");

            entity.Property(e => e.CHILDVALIDTO).HasColumnType("datetime");

            entity.Property(e => e.PARENTALIAS)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.PARENTNAME)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.PARENTVALIDFROM).HasColumnType("datetime");

            entity.Property(e => e.PARENTVALIDTO).HasColumnType("datetime");

            entity.Property(e => e.RELATIONALIAS)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.RELATIONNAME)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.RELATIONVALIDFROM).HasColumnType("datetime");

            entity.Property(e => e.RELATIONVALIDTO).HasColumnType("datetime");
        }
    }
}
