// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class VAMPROPERTYConfiguration : IEntityTypeConfiguration<VAMPROPERTY>
    {
        public void Configure(EntityTypeBuilder<VAMPROPERTY> entity)
        {
            entity.HasKey(e => new { e.OBJECTID, e.PROPERTYID });




            entity.Property(e => e.OBJECTALIAS)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.OBJECTNAME)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.OBJECTVALIDFROM).HasColumnType("datetime");

            entity.Property(e => e.OBJECTVALIDTO).HasColumnType("datetime");

            entity.Property(e => e.PROPERTYALIAS)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.PROPERTYNAME)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.PROPERTYVALIDFROM).HasColumnType("datetime");

            entity.Property(e => e.PROPERTYVALIDTO).HasColumnType("datetime");

            entity.Property(e => e.UPDATED).HasColumnType("datetime");

            entity.Property(e => e.VALUE)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.VALUEVALIDFROM).HasColumnType("datetime");

            entity.Property(e => e.VALUEVALIDTO).HasColumnType("datetime");
        }
    }
}
