// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AM.EFCore.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AM.EFCore.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AM.EFCore.Data
{
    public class VAMUSERConfiguration : IEntityTypeConfiguration<VAMUSER>
    {
        public void Configure(EntityTypeBuilder<VAMUSER> entity)
        {
            entity.HasKey(e=>e.ID);

            entity.Property(e => e.ALIAS)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.DESCRIPTION)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.EMAIL)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.LOCID)
                .IsRequired()
                .IsUnicode(false);

            entity.Property(e => e.NAME)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.NIK)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.PASSEXPIRED).HasColumnType("datetime");

            entity.Property(e => e.PASSWORD)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.UPDATED).HasColumnType("datetime");

            entity.Property(e => e.VALIDFROM).HasColumnType("datetime");

            entity.Property(e => e.VALIDTO).HasColumnType("datetime");
        }
    }
}
